// Generated by autowire plugin wishbone (soc_wb). Do not edit.
// uvm_reg_block: one sub-block per child bus, one leaf block per regfile hang.
// TagFromAddr aliases are separate submap instances; broadcast windows are comments (no frontdoor).

`ifndef RAL_BLOCK_SOC_WB_SV
`define RAL_BLOCK_SOC_WB_SV

import uvm_pkg::*;
`include "uvm_macros.svh"

`include "ral_SHA256.sv"
`include "ral_SMOKE.sv"

`include "ral_block_sd_sha.sv"

class ral_block_soc_wb extends uvm_reg_block;
	rand ral_block_sd_sha ch0_bank0;
	rand ral_block_sd_sha ch0_bank1;
	rand ral_block_sd_sha ch0_bank2;
	rand ral_block_sd_sha ch0_bank3;
	rand ral_block_sd_sha ch1_bank0;
	rand ral_block_sd_sha ch1_bank1;
	rand ral_block_sd_sha ch1_bank2;
	rand ral_block_sd_sha ch1_bank3;
	rand ral_block_smoke smoke_bank0;
	rand ral_block_smoke smoke_bank1;
	rand ral_block_smoke smoke_bank2;
	rand ral_block_smoke smoke_bank3;

	function new(string name = "ral_block_soc_wb");
		super.new(name, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		default_map = create_map("default_map", 0, 4, UVM_LITTLE_ENDIAN);
		// ch0_bank0: bank=0
		this.ch0_bank0 = ral_block_sd_sha::type_id::create("ch0_bank0",, get_full_name());
		this.ch0_bank0.configure(this, "");
		this.ch0_bank0.build();
		default_map.add_submap(this.ch0_bank0.default_map, 32'h03000000);
		// ch0_bank1: bank=1
		this.ch0_bank1 = ral_block_sd_sha::type_id::create("ch0_bank1",, get_full_name());
		this.ch0_bank1.configure(this, "");
		this.ch0_bank1.build();
		default_map.add_submap(this.ch0_bank1.default_map, 32'h07000000);
		// ch0_bank2: bank=2
		this.ch0_bank2 = ral_block_sd_sha::type_id::create("ch0_bank2",, get_full_name());
		this.ch0_bank2.configure(this, "");
		this.ch0_bank2.build();
		default_map.add_submap(this.ch0_bank2.default_map, 32'h0b000000);
		// ch0_bank3: bank=3
		this.ch0_bank3 = ral_block_sd_sha::type_id::create("ch0_bank3",, get_full_name());
		this.ch0_bank3.configure(this, "");
		this.ch0_bank3.build();
		default_map.add_submap(this.ch0_bank3.default_map, 32'h0f000000);
		// ch1_bank0: bank=0
		this.ch1_bank0 = ral_block_sd_sha::type_id::create("ch1_bank0",, get_full_name());
		this.ch1_bank0.configure(this, "");
		this.ch1_bank0.build();
		default_map.add_submap(this.ch1_bank0.default_map, 32'h03001000);
		// ch1_bank1: bank=1
		this.ch1_bank1 = ral_block_sd_sha::type_id::create("ch1_bank1",, get_full_name());
		this.ch1_bank1.configure(this, "");
		this.ch1_bank1.build();
		default_map.add_submap(this.ch1_bank1.default_map, 32'h07001000);
		// ch1_bank2: bank=2
		this.ch1_bank2 = ral_block_sd_sha::type_id::create("ch1_bank2",, get_full_name());
		this.ch1_bank2.configure(this, "");
		this.ch1_bank2.build();
		default_map.add_submap(this.ch1_bank2.default_map, 32'h0b001000);
		// ch1_bank3: bank=3
		this.ch1_bank3 = ral_block_sd_sha::type_id::create("ch1_bank3",, get_full_name());
		this.ch1_bank3.configure(this, "");
		this.ch1_bank3.build();
		default_map.add_submap(this.ch1_bank3.default_map, 32'h0f001000);
		// smoke_bank0: bank=0
		this.smoke_bank0 = ral_block_smoke::type_id::create("smoke_bank0",, get_full_name());
		this.smoke_bank0.configure(this, "");
		this.smoke_bank0.build();
		default_map.add_submap(this.smoke_bank0.default_map, 32'h03006000);
		// smoke_bank1: bank=1
		this.smoke_bank1 = ral_block_smoke::type_id::create("smoke_bank1",, get_full_name());
		this.smoke_bank1.configure(this, "");
		this.smoke_bank1.build();
		default_map.add_submap(this.smoke_bank1.default_map, 32'h07006000);
		// smoke_bank2: bank=2
		this.smoke_bank2 = ral_block_smoke::type_id::create("smoke_bank2",, get_full_name());
		this.smoke_bank2.configure(this, "");
		this.smoke_bank2.build();
		default_map.add_submap(this.smoke_bank2.default_map, 32'h0b006000);
		// smoke_bank3: bank=3
		this.smoke_bank3 = ral_block_smoke::type_id::create("smoke_bank3",, get_full_name());
		this.smoke_bank3.configure(this, "");
		this.smoke_bank3.build();
		default_map.add_submap(this.smoke_bank3.default_map, 32'h0f006000);
	endfunction: build

	`uvm_object_utils(ral_block_soc_wb)
endclass : ral_block_soc_wb

`endif // RAL_BLOCK_SOC_WB_SV
