// Generated by autowire plugin wishbone-regfile (table sha256). Do not edit.
// uvm_reg: field layout only. Address map and shadow tag belong to wishbone-bus.

`ifndef RAL_SHA256_SV
`define RAL_SHA256_SV

import uvm_pkg::*;
`include "uvm_macros.svh"

// Cell CTRL — Control / status
class ral_reg_sha256_CTRL extends uvm_reg;
	rand uvm_reg_field soft_reset ; // bit [0]
	     uvm_reg_field done_clear ; // bit [1]
	     uvm_reg_field reserved_2 ; // bit [7:2]
	     uvm_reg_field busy       ; // bit [8]
	     uvm_reg_field done       ; // bit [9]
	     uvm_reg_field reserved_10; // bit [31:10]

	function new(string name = "ral_reg_sha256_CTRL");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.soft_reset = uvm_reg_field::type_id::create("soft_reset",, get_full_name());
		this.soft_reset.configure(this, 1, 0, "RW", 0, 1'h0, 1, 1, 0);
		this.done_clear = uvm_reg_field::type_id::create("done_clear",, get_full_name());
		this.done_clear.configure(this, 1, 1, "W1C", 0, 1'h0, 1, 0, 0);
		this.reserved_2 = uvm_reg_field::type_id::create("reserved_2",, get_full_name());
		this.reserved_2.configure(this, 6, 2, "RO", 0, 6'h0, 1, 0, 0);
		this.busy = uvm_reg_field::type_id::create("busy",, get_full_name());
		this.busy.configure(this, 1, 8, "RO", 0, 1'h0, 1, 0, 0);
		this.done = uvm_reg_field::type_id::create("done",, get_full_name());
		this.done.configure(this, 1, 9, "RO", 0, 1'h0, 1, 0, 0);
		this.reserved_10 = uvm_reg_field::type_id::create("reserved_10",, get_full_name());
		this.reserved_10.configure(this, 22, 10, "RO", 0, 22'h0, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_sha256_CTRL)
endclass : ral_reg_sha256_CTRL

// Cell HASH0 — Digest word 0
class ral_reg_sha256_HASH0 extends uvm_reg;
	     uvm_reg_field hash0; // bit [31:0]

	function new(string name = "ral_reg_sha256_HASH0");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.hash0 = uvm_reg_field::type_id::create("hash0",, get_full_name());
		this.hash0.configure(this, 32, 0, "RO", 0, 32'h0, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_sha256_HASH0)
endclass : ral_reg_sha256_HASH0

// Cell HASH1 — Digest word 1
class ral_reg_sha256_HASH1 extends uvm_reg;
	     uvm_reg_field hash1; // bit [31:0]

	function new(string name = "ral_reg_sha256_HASH1");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.hash1 = uvm_reg_field::type_id::create("hash1",, get_full_name());
		this.hash1.configure(this, 32, 0, "RO", 0, 32'h0, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_sha256_HASH1)
endclass : ral_reg_sha256_HASH1

// Cell HASH2 — Digest word 2
class ral_reg_sha256_HASH2 extends uvm_reg;
	     uvm_reg_field hash2; // bit [31:0]

	function new(string name = "ral_reg_sha256_HASH2");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.hash2 = uvm_reg_field::type_id::create("hash2",, get_full_name());
		this.hash2.configure(this, 32, 0, "RO", 0, 32'h0, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_sha256_HASH2)
endclass : ral_reg_sha256_HASH2

// Cell HASH3 — Digest word 3
class ral_reg_sha256_HASH3 extends uvm_reg;
	     uvm_reg_field hash3; // bit [31:0]

	function new(string name = "ral_reg_sha256_HASH3");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.hash3 = uvm_reg_field::type_id::create("hash3",, get_full_name());
		this.hash3.configure(this, 32, 0, "RO", 0, 32'h0, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_sha256_HASH3)
endclass : ral_reg_sha256_HASH3

// Cell HASH4 — Digest word 4
class ral_reg_sha256_HASH4 extends uvm_reg;
	     uvm_reg_field hash4; // bit [31:0]

	function new(string name = "ral_reg_sha256_HASH4");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.hash4 = uvm_reg_field::type_id::create("hash4",, get_full_name());
		this.hash4.configure(this, 32, 0, "RO", 0, 32'h0, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_sha256_HASH4)
endclass : ral_reg_sha256_HASH4

// Cell HASH5 — Digest word 5
class ral_reg_sha256_HASH5 extends uvm_reg;
	     uvm_reg_field hash5; // bit [31:0]

	function new(string name = "ral_reg_sha256_HASH5");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.hash5 = uvm_reg_field::type_id::create("hash5",, get_full_name());
		this.hash5.configure(this, 32, 0, "RO", 0, 32'h0, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_sha256_HASH5)
endclass : ral_reg_sha256_HASH5

// Cell HASH6 — Digest word 6
class ral_reg_sha256_HASH6 extends uvm_reg;
	     uvm_reg_field hash6; // bit [31:0]

	function new(string name = "ral_reg_sha256_HASH6");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.hash6 = uvm_reg_field::type_id::create("hash6",, get_full_name());
		this.hash6.configure(this, 32, 0, "RO", 0, 32'h0, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_sha256_HASH6)
endclass : ral_reg_sha256_HASH6

// Cell HASH7 — Digest word 7
class ral_reg_sha256_HASH7 extends uvm_reg;
	     uvm_reg_field hash7; // bit [31:0]

	function new(string name = "ral_reg_sha256_HASH7");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.hash7 = uvm_reg_field::type_id::create("hash7",, get_full_name());
		this.hash7.configure(this, 32, 0, "RO", 0, 32'h0, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_sha256_HASH7)
endclass : ral_reg_sha256_HASH7

`endif // RAL_SHA256_SV
