// Generated by autowire plugin wishbone (sd_sha). Do not edit.
// uvm_reg_block: one sub-block per child bus, one leaf block per regfile hang.
// TagFromAddr aliases are separate submap instances; broadcast windows are comments (no frontdoor).

`ifndef RAL_BLOCK_SD_SHA_SV
`define RAL_BLOCK_SD_SHA_SV

import uvm_pkg::*;
`include "uvm_macros.svh"

`include "ral_SHA256.sv"

class ral_block_sd_sha extends uvm_reg_block;
	rand ral_block_sha256 sha256;

	function new(string name = "ral_block_sd_sha");
		super.new(name, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		default_map = create_map("default_map", 0, 4, UVM_LITTLE_ENDIAN);
		this.sha256 = ral_block_sha256::type_id::create("sha256",, get_full_name());
		this.sha256.configure(this, "");
		this.sha256.build();
		default_map.add_submap(this.sha256.default_map, 32'h00000040);
	endfunction: build

	`uvm_object_utils(ral_block_sd_sha)
endclass : ral_block_sd_sha

`endif // RAL_BLOCK_SD_SHA_SV
