// Generated by autowire plugin wishbone (sd_sha). Do not edit.
// uvm_reg_block map: Slave.base + cell offset. Cell classes are packed beside this file.

`ifndef RAL_BLOCK_SD_SHA_SV
`define RAL_BLOCK_SD_SHA_SV

import uvm_pkg::*;
`include "uvm_macros.svh"

`include "ral_SHA256.sv"

class ral_block_sd_sha extends uvm_reg_block;
	rand ral_reg_sha256_CTRL sha256_CTRL;
	rand ral_reg_sha256_HASH0 sha256_HASH0;
	rand ral_reg_sha256_HASH1 sha256_HASH1;
	rand ral_reg_sha256_HASH2 sha256_HASH2;
	rand ral_reg_sha256_HASH3 sha256_HASH3;
	rand ral_reg_sha256_HASH4 sha256_HASH4;
	rand ral_reg_sha256_HASH5 sha256_HASH5;
	rand ral_reg_sha256_HASH6 sha256_HASH6;
	rand ral_reg_sha256_HASH7 sha256_HASH7;

	function new(string name = "ral_block_sd_sha");
		super.new(name, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		default_map = create_map("default_map", 0, 4, UVM_LITTLE_ENDIAN);
		this.sha256_CTRL = ral_reg_sha256_CTRL::type_id::create("sha256_CTRL",, get_full_name());
		this.sha256_CTRL.configure(this);
		this.sha256_CTRL.build();
		default_map.add_reg(this.sha256_CTRL, 32'h00000040, "RW");
		this.sha256_HASH0 = ral_reg_sha256_HASH0::type_id::create("sha256_HASH0",, get_full_name());
		this.sha256_HASH0.configure(this);
		this.sha256_HASH0.build();
		default_map.add_reg(this.sha256_HASH0, 32'h00000044, "RO");
		this.sha256_HASH1 = ral_reg_sha256_HASH1::type_id::create("sha256_HASH1",, get_full_name());
		this.sha256_HASH1.configure(this);
		this.sha256_HASH1.build();
		default_map.add_reg(this.sha256_HASH1, 32'h00000048, "RO");
		this.sha256_HASH2 = ral_reg_sha256_HASH2::type_id::create("sha256_HASH2",, get_full_name());
		this.sha256_HASH2.configure(this);
		this.sha256_HASH2.build();
		default_map.add_reg(this.sha256_HASH2, 32'h0000004c, "RO");
		this.sha256_HASH3 = ral_reg_sha256_HASH3::type_id::create("sha256_HASH3",, get_full_name());
		this.sha256_HASH3.configure(this);
		this.sha256_HASH3.build();
		default_map.add_reg(this.sha256_HASH3, 32'h00000050, "RO");
		this.sha256_HASH4 = ral_reg_sha256_HASH4::type_id::create("sha256_HASH4",, get_full_name());
		this.sha256_HASH4.configure(this);
		this.sha256_HASH4.build();
		default_map.add_reg(this.sha256_HASH4, 32'h00000054, "RO");
		this.sha256_HASH5 = ral_reg_sha256_HASH5::type_id::create("sha256_HASH5",, get_full_name());
		this.sha256_HASH5.configure(this);
		this.sha256_HASH5.build();
		default_map.add_reg(this.sha256_HASH5, 32'h00000058, "RO");
		this.sha256_HASH6 = ral_reg_sha256_HASH6::type_id::create("sha256_HASH6",, get_full_name());
		this.sha256_HASH6.configure(this);
		this.sha256_HASH6.build();
		default_map.add_reg(this.sha256_HASH6, 32'h0000005c, "RO");
		this.sha256_HASH7 = ral_reg_sha256_HASH7::type_id::create("sha256_HASH7",, get_full_name());
		this.sha256_HASH7.configure(this);
		this.sha256_HASH7.build();
		default_map.add_reg(this.sha256_HASH7, 32'h00000060, "RO");
	endfunction: build

	`uvm_object_utils(ral_block_sd_sha)
endclass : ral_block_sd_sha

`endif // RAL_BLOCK_SD_SHA_SV
