// Generated by autowire plugin wishbone. Do not edit.
// Packed uvm_reg: cell classes + ral_block maps. RALF is <bus>.ralf.

`ifndef RAL_WISHBONE_SV
`define RAL_WISHBONE_SV

`include "ral_SHA256.sv"
`include "ral_SMOKE.sv"
`include "ral_block_sd_sha.sv"
`include "ral_block_soc_wb.sv"

`endif
