// Generated by autowire plugin wishbone (soc_wb). Do not edit.
// uvm_reg_block map: Slave.base + cell offset. Cell classes are packed beside this file.

`ifndef RAL_BLOCK_SOC_WB_SV
`define RAL_BLOCK_SOC_WB_SV

import uvm_pkg::*;
`include "uvm_macros.svh"

`include "ral_SHA256.sv"
`include "ral_SMOKE.sv"

class ral_block_soc_wb extends uvm_reg_block;
	rand ral_reg_sha256_CTRL ch0_sha256_CTRL;
	rand ral_reg_sha256_HASH0 ch0_sha256_HASH0;
	rand ral_reg_sha256_HASH1 ch0_sha256_HASH1;
	rand ral_reg_sha256_HASH2 ch0_sha256_HASH2;
	rand ral_reg_sha256_HASH3 ch0_sha256_HASH3;
	rand ral_reg_sha256_HASH4 ch0_sha256_HASH4;
	rand ral_reg_sha256_HASH5 ch0_sha256_HASH5;
	rand ral_reg_sha256_HASH6 ch0_sha256_HASH6;
	rand ral_reg_sha256_HASH7 ch0_sha256_HASH7;
	rand ral_reg_sha256_CTRL ch1_sha256_CTRL;
	rand ral_reg_sha256_HASH0 ch1_sha256_HASH0;
	rand ral_reg_sha256_HASH1 ch1_sha256_HASH1;
	rand ral_reg_sha256_HASH2 ch1_sha256_HASH2;
	rand ral_reg_sha256_HASH3 ch1_sha256_HASH3;
	rand ral_reg_sha256_HASH4 ch1_sha256_HASH4;
	rand ral_reg_sha256_HASH5 ch1_sha256_HASH5;
	rand ral_reg_sha256_HASH6 ch1_sha256_HASH6;
	rand ral_reg_sha256_HASH7 ch1_sha256_HASH7;
	rand ral_reg_smoke_ID smoke_ID;
	rand ral_reg_smoke_STATUS smoke_STATUS;
	rand ral_reg_smoke_CFG smoke_CFG;
	rand ral_reg_smoke_FEED smoke_FEED;
	rand ral_reg_smoke_FIFO smoke_FIFO;
	rand ral_reg_smoke_CMD smoke_CMD;
	rand ral_reg_smoke_IRQ smoke_IRQ;
	rand ral_reg_smoke_BANK smoke_BANK;
	rand ral_reg_smoke_BANKSEL smoke_BANKSEL;
	rand ral_reg_smoke_FABRIC smoke_FABRIC;
	rand ral_reg_smoke_key_key_0 smoke_key_key_0;
	rand ral_reg_smoke_key_key_1 smoke_key_key_1;
	rand ral_reg_smoke_key_key_2 smoke_key_key_2;

	function new(string name = "ral_block_soc_wb");
		super.new(name, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		default_map = create_map("default_map", 0, 4, UVM_LITTLE_ENDIAN);
		this.ch0_sha256_CTRL = ral_reg_sha256_CTRL::type_id::create("ch0_sha256_CTRL",, get_full_name());
		this.ch0_sha256_CTRL.configure(this);
		this.ch0_sha256_CTRL.build();
		default_map.add_reg(this.ch0_sha256_CTRL, 32'h03000040, "RW");
		this.ch0_sha256_HASH0 = ral_reg_sha256_HASH0::type_id::create("ch0_sha256_HASH0",, get_full_name());
		this.ch0_sha256_HASH0.configure(this);
		this.ch0_sha256_HASH0.build();
		default_map.add_reg(this.ch0_sha256_HASH0, 32'h03000044, "RO");
		this.ch0_sha256_HASH1 = ral_reg_sha256_HASH1::type_id::create("ch0_sha256_HASH1",, get_full_name());
		this.ch0_sha256_HASH1.configure(this);
		this.ch0_sha256_HASH1.build();
		default_map.add_reg(this.ch0_sha256_HASH1, 32'h03000048, "RO");
		this.ch0_sha256_HASH2 = ral_reg_sha256_HASH2::type_id::create("ch0_sha256_HASH2",, get_full_name());
		this.ch0_sha256_HASH2.configure(this);
		this.ch0_sha256_HASH2.build();
		default_map.add_reg(this.ch0_sha256_HASH2, 32'h0300004c, "RO");
		this.ch0_sha256_HASH3 = ral_reg_sha256_HASH3::type_id::create("ch0_sha256_HASH3",, get_full_name());
		this.ch0_sha256_HASH3.configure(this);
		this.ch0_sha256_HASH3.build();
		default_map.add_reg(this.ch0_sha256_HASH3, 32'h03000050, "RO");
		this.ch0_sha256_HASH4 = ral_reg_sha256_HASH4::type_id::create("ch0_sha256_HASH4",, get_full_name());
		this.ch0_sha256_HASH4.configure(this);
		this.ch0_sha256_HASH4.build();
		default_map.add_reg(this.ch0_sha256_HASH4, 32'h03000054, "RO");
		this.ch0_sha256_HASH5 = ral_reg_sha256_HASH5::type_id::create("ch0_sha256_HASH5",, get_full_name());
		this.ch0_sha256_HASH5.configure(this);
		this.ch0_sha256_HASH5.build();
		default_map.add_reg(this.ch0_sha256_HASH5, 32'h03000058, "RO");
		this.ch0_sha256_HASH6 = ral_reg_sha256_HASH6::type_id::create("ch0_sha256_HASH6",, get_full_name());
		this.ch0_sha256_HASH6.configure(this);
		this.ch0_sha256_HASH6.build();
		default_map.add_reg(this.ch0_sha256_HASH6, 32'h0300005c, "RO");
		this.ch0_sha256_HASH7 = ral_reg_sha256_HASH7::type_id::create("ch0_sha256_HASH7",, get_full_name());
		this.ch0_sha256_HASH7.configure(this);
		this.ch0_sha256_HASH7.build();
		default_map.add_reg(this.ch0_sha256_HASH7, 32'h03000060, "RO");
		this.ch1_sha256_CTRL = ral_reg_sha256_CTRL::type_id::create("ch1_sha256_CTRL",, get_full_name());
		this.ch1_sha256_CTRL.configure(this);
		this.ch1_sha256_CTRL.build();
		default_map.add_reg(this.ch1_sha256_CTRL, 32'h03001040, "RW");
		this.ch1_sha256_HASH0 = ral_reg_sha256_HASH0::type_id::create("ch1_sha256_HASH0",, get_full_name());
		this.ch1_sha256_HASH0.configure(this);
		this.ch1_sha256_HASH0.build();
		default_map.add_reg(this.ch1_sha256_HASH0, 32'h03001044, "RO");
		this.ch1_sha256_HASH1 = ral_reg_sha256_HASH1::type_id::create("ch1_sha256_HASH1",, get_full_name());
		this.ch1_sha256_HASH1.configure(this);
		this.ch1_sha256_HASH1.build();
		default_map.add_reg(this.ch1_sha256_HASH1, 32'h03001048, "RO");
		this.ch1_sha256_HASH2 = ral_reg_sha256_HASH2::type_id::create("ch1_sha256_HASH2",, get_full_name());
		this.ch1_sha256_HASH2.configure(this);
		this.ch1_sha256_HASH2.build();
		default_map.add_reg(this.ch1_sha256_HASH2, 32'h0300104c, "RO");
		this.ch1_sha256_HASH3 = ral_reg_sha256_HASH3::type_id::create("ch1_sha256_HASH3",, get_full_name());
		this.ch1_sha256_HASH3.configure(this);
		this.ch1_sha256_HASH3.build();
		default_map.add_reg(this.ch1_sha256_HASH3, 32'h03001050, "RO");
		this.ch1_sha256_HASH4 = ral_reg_sha256_HASH4::type_id::create("ch1_sha256_HASH4",, get_full_name());
		this.ch1_sha256_HASH4.configure(this);
		this.ch1_sha256_HASH4.build();
		default_map.add_reg(this.ch1_sha256_HASH4, 32'h03001054, "RO");
		this.ch1_sha256_HASH5 = ral_reg_sha256_HASH5::type_id::create("ch1_sha256_HASH5",, get_full_name());
		this.ch1_sha256_HASH5.configure(this);
		this.ch1_sha256_HASH5.build();
		default_map.add_reg(this.ch1_sha256_HASH5, 32'h03001058, "RO");
		this.ch1_sha256_HASH6 = ral_reg_sha256_HASH6::type_id::create("ch1_sha256_HASH6",, get_full_name());
		this.ch1_sha256_HASH6.configure(this);
		this.ch1_sha256_HASH6.build();
		default_map.add_reg(this.ch1_sha256_HASH6, 32'h0300105c, "RO");
		this.ch1_sha256_HASH7 = ral_reg_sha256_HASH7::type_id::create("ch1_sha256_HASH7",, get_full_name());
		this.ch1_sha256_HASH7.configure(this);
		this.ch1_sha256_HASH7.build();
		default_map.add_reg(this.ch1_sha256_HASH7, 32'h03001060, "RO");
		this.smoke_ID = ral_reg_smoke_ID::type_id::create("smoke_ID",, get_full_name());
		this.smoke_ID.configure(this);
		this.smoke_ID.build();
		default_map.add_reg(this.smoke_ID, 32'h03006000, "RO");
		this.smoke_STATUS = ral_reg_smoke_STATUS::type_id::create("smoke_STATUS",, get_full_name());
		this.smoke_STATUS.configure(this);
		this.smoke_STATUS.build();
		default_map.add_reg(this.smoke_STATUS, 32'h03006004, "RO");
		this.smoke_CFG = ral_reg_smoke_CFG::type_id::create("smoke_CFG",, get_full_name());
		this.smoke_CFG.configure(this);
		this.smoke_CFG.build();
		default_map.add_reg(this.smoke_CFG, 32'h03006008, "RW");
		this.smoke_FEED = ral_reg_smoke_FEED::type_id::create("smoke_FEED",, get_full_name());
		this.smoke_FEED.configure(this);
		this.smoke_FEED.build();
		default_map.add_reg(this.smoke_FEED, 32'h0300600c, "RW");
		this.smoke_FIFO = ral_reg_smoke_FIFO::type_id::create("smoke_FIFO",, get_full_name());
		this.smoke_FIFO.configure(this);
		this.smoke_FIFO.build();
		default_map.add_reg(this.smoke_FIFO, 32'h03006010, "RW");
		this.smoke_CMD = ral_reg_smoke_CMD::type_id::create("smoke_CMD",, get_full_name());
		this.smoke_CMD.configure(this);
		this.smoke_CMD.build();
		default_map.add_reg(this.smoke_CMD, 32'h03006014, "RW");
		this.smoke_IRQ = ral_reg_smoke_IRQ::type_id::create("smoke_IRQ",, get_full_name());
		this.smoke_IRQ.configure(this);
		this.smoke_IRQ.build();
		default_map.add_reg(this.smoke_IRQ, 32'h03006018, "RW");
		// smoke.BANK: shadow bank, 4 copies; bank select is fabric TGA (2 bit)
		this.smoke_BANK = ral_reg_smoke_BANK::type_id::create("smoke_BANK",, get_full_name());
		this.smoke_BANK.configure(this);
		this.smoke_BANK.build();
		default_map.add_reg(this.smoke_BANK, 32'h0300601c, "RW");
		this.smoke_BANKSEL = ral_reg_smoke_BANKSEL::type_id::create("smoke_BANKSEL",, get_full_name());
		this.smoke_BANKSEL.configure(this);
		this.smoke_BANKSEL.build();
		default_map.add_reg(this.smoke_BANKSEL, 32'h0300602c, "RW");
		this.smoke_FABRIC = ral_reg_smoke_FABRIC::type_id::create("smoke_FABRIC",, get_full_name());
		this.smoke_FABRIC.configure(this);
		this.smoke_FABRIC.build();
		default_map.add_reg(this.smoke_FABRIC, 32'h03006030, "RW");
		this.smoke_key_key_0 = ral_reg_smoke_key_key_0::type_id::create("smoke_key_key_0",, get_full_name());
		this.smoke_key_key_0.configure(this);
		this.smoke_key_key_0.build();
		default_map.add_reg(this.smoke_key_key_0, 32'h03006020, "RW");
		this.smoke_key_key_1 = ral_reg_smoke_key_key_1::type_id::create("smoke_key_key_1",, get_full_name());
		this.smoke_key_key_1.configure(this);
		this.smoke_key_key_1.build();
		default_map.add_reg(this.smoke_key_key_1, 32'h03006024, "RW");
		this.smoke_key_key_2 = ral_reg_smoke_key_key_2::type_id::create("smoke_key_key_2",, get_full_name());
		this.smoke_key_key_2.configure(this);
		this.smoke_key_key_2.build();
		default_map.add_reg(this.smoke_key_key_2, 32'h03006028, "RW");
	endfunction: build

	`uvm_object_utils(ral_block_soc_wb)
endclass : ral_block_soc_wb

`endif // RAL_BLOCK_SOC_WB_SV
