// Generated by autowire plugin wishbone. Do not edit.
// Packed uvm_reg: cell classes + ral_block maps.

`ifndef RAL_WISHBONE_SV
`define RAL_WISHBONE_SV

`include "regfile/ral_SHA256.sv"
`include "regfile/ral_SMOKE.sv"
`include "bus/ral_block_sd_sha.sv"
`include "bus/ral_block_soc_wb.sv"

`endif
