// Generated by autowire plugin wishbone (table smoke). Do not edit.
// uvm_reg: field layout only. Address map and shadow tag are packed with the bus.

`ifndef RAL_SMOKE_SV
`define RAL_SMOKE_SV

import uvm_pkg::*;
`include "uvm_macros.svh"

// Cell ID — RC identity
class ral_reg_smoke_ID extends uvm_reg;
	     uvm_reg_field magic  ; // bit [15:0]
	     uvm_reg_field version; // bit [31:16]

	function new(string name = "ral_reg_smoke_ID");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.magic = uvm_reg_field::type_id::create("magic",, get_full_name());
		this.magic.configure(this, 16, 0, "RO", 0, 16'ha55a, 1, 0, 0);
		this.version = uvm_reg_field::type_id::create("version",, get_full_name());
		this.version.configure(this, 16, 16, "RO", 0, 16'h1, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_smoke_ID)
endclass : ral_reg_smoke_ID

// Cell STATUS — RO status
class ral_reg_smoke_STATUS extends uvm_reg;
	     uvm_reg_field busy       ; // bit [0]
	     uvm_reg_field reserved_1 ; // bit [7:1]
	     uvm_reg_field code       ; // bit [15:8]
	     uvm_reg_field reserved_16; // bit [31:16]

	function new(string name = "ral_reg_smoke_STATUS");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.busy = uvm_reg_field::type_id::create("busy",, get_full_name());
		this.busy.configure(this, 1, 0, "RO", 0, 1'h0, 1, 0, 0);
		this.reserved_1 = uvm_reg_field::type_id::create("reserved_1",, get_full_name());
		this.reserved_1.configure(this, 7, 1, "RO", 0, 7'h0, 1, 0, 0);
		this.code = uvm_reg_field::type_id::create("code",, get_full_name());
		this.code.configure(this, 8, 8, "RO", 0, 8'h0, 1, 0, 0);
		this.reserved_16 = uvm_reg_field::type_id::create("reserved_16",, get_full_name());
		this.reserved_16.configure(this, 16, 16, "RO", 0, 16'h0, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_smoke_STATUS)
endclass : ral_reg_smoke_STATUS

// Cell CFG — RW config
class ral_reg_smoke_CFG extends uvm_reg;
	rand uvm_reg_field enable     ; // bit [0]
	     uvm_reg_field reserved_1 ; // bit [7:1]
	rand uvm_reg_field mode       ; // bit [10:8]
	     uvm_reg_field reserved_11; // bit [31:11]

	function new(string name = "ral_reg_smoke_CFG");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.enable = uvm_reg_field::type_id::create("enable",, get_full_name());
		this.enable.configure(this, 1, 0, "RW", 0, 1'h0, 1, 1, 0);
		this.reserved_1 = uvm_reg_field::type_id::create("reserved_1",, get_full_name());
		this.reserved_1.configure(this, 7, 1, "RO", 0, 7'h0, 1, 0, 0);
		this.mode = uvm_reg_field::type_id::create("mode",, get_full_name());
		this.mode.configure(this, 3, 8, "RW", 0, 3'h1, 1, 1, 0);
		this.reserved_11 = uvm_reg_field::type_id::create("reserved_11",, get_full_name());
		this.reserved_11.configure(this, 21, 11, "RO", 0, 21'h0, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_smoke_CFG)
endclass : ral_reg_smoke_CFG

// Cell FEED — RWW capture
class ral_reg_smoke_FEED extends uvm_reg;
	rand uvm_reg_field capture    ; // bit [15:0]
	     uvm_reg_field reserved_16; // bit [31:16]

	function new(string name = "ral_reg_smoke_FEED");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.capture = uvm_reg_field::type_id::create("capture",, get_full_name());
		this.capture.configure(this, 16, 0, "RW", 0, 16'h0, 1, 1, 0);
		this.reserved_16 = uvm_reg_field::type_id::create("reserved_16",, get_full_name());
		this.reserved_16.configure(this, 16, 16, "RO", 0, 16'h0, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_smoke_FEED)
endclass : ral_reg_smoke_FEED

// Cell FIFO — RWE window
class ral_reg_smoke_FIFO extends uvm_reg;
	rand uvm_reg_field data; // bit [31:0]

	function new(string name = "ral_reg_smoke_FIFO");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.data = uvm_reg_field::type_id::create("data",, get_full_name());
		this.data.configure(this, 32, 0, "RW", 0, 32'h0, 1, 1, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_smoke_FIFO)
endclass : ral_reg_smoke_FIFO

// Cell CMD — W1P pulse
class ral_reg_smoke_CMD extends uvm_reg;
	     uvm_reg_field go        ; // bit [0]
	     uvm_reg_field reserved_1; // bit [31:1]

	function new(string name = "ral_reg_smoke_CMD");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.go = uvm_reg_field::type_id::create("go",, get_full_name());
		this.go.configure(this, 1, 0, "W1C", 0, 1'h0, 1, 0, 0);
		this.reserved_1 = uvm_reg_field::type_id::create("reserved_1",, get_full_name());
		this.reserved_1.configure(this, 31, 1, "RO", 0, 31'h0, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_smoke_CMD)
endclass : ral_reg_smoke_CMD

// Cell IRQ — W1C sticky
class ral_reg_smoke_IRQ extends uvm_reg;
	     uvm_reg_field sticky    ; // bit [0]
	     uvm_reg_field reserved_1; // bit [31:1]

	function new(string name = "ral_reg_smoke_IRQ");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.sticky = uvm_reg_field::type_id::create("sticky",, get_full_name());
		this.sticky.configure(this, 1, 0, "W1C", 0, 1'h0, 1, 0, 0);
		this.reserved_1 = uvm_reg_field::type_id::create("reserved_1",, get_full_name());
		this.reserved_1.configure(this, 31, 1, "RO", 0, 31'h0, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_smoke_IRQ)
endclass : ral_reg_smoke_IRQ

// Cell BANK — Shadowed RW
// shadow: bank, 4 copies (bank select is a bus TGA concern)
class ral_reg_smoke_BANK extends uvm_reg;
	rand uvm_reg_field cfg       ; // bit [7:0]
	     uvm_reg_field reserved_8; // bit [31:8]

	function new(string name = "ral_reg_smoke_BANK");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.cfg = uvm_reg_field::type_id::create("cfg",, get_full_name());
		this.cfg.configure(this, 8, 0, "RW", 0, 8'h10, 1, 1, 0);
		this.reserved_8 = uvm_reg_field::type_id::create("reserved_8",, get_full_name());
		this.reserved_8.configure(this, 24, 8, "RO", 0, 24'h0, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_smoke_BANK)
endclass : ral_reg_smoke_BANK

// Cell BANKSEL — Saved working bank
class ral_reg_smoke_BANKSEL extends uvm_reg;
	rand uvm_reg_field bank_sel  ; // bit [1:0]
	     uvm_reg_field reserved_2; // bit [31:2]

	function new(string name = "ral_reg_smoke_BANKSEL");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.bank_sel = uvm_reg_field::type_id::create("bank_sel",, get_full_name());
		this.bank_sel.configure(this, 2, 0, "RW", 0, 2'h0, 1, 1, 0);
		this.reserved_2 = uvm_reg_field::type_id::create("reserved_2",, get_full_name());
		this.reserved_2.configure(this, 30, 2, "RO", 0, 30'h0, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_smoke_BANKSEL)
endclass : ral_reg_smoke_BANKSEL

// Cell ACTIVE — Muxed working cfg
class ral_reg_smoke_ACTIVE extends uvm_reg;
	     uvm_reg_field value     ; // bit [7:0]
	     uvm_reg_field reserved_8; // bit [31:8]

	function new(string name = "ral_reg_smoke_ACTIVE");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.value = uvm_reg_field::type_id::create("value",, get_full_name());
		this.value.configure(this, 8, 0, "RO", 0, 8'h0, 1, 0, 0);
		this.reserved_8 = uvm_reg_field::type_id::create("reserved_8",, get_full_name());
		this.reserved_8.configure(this, 24, 8, "RO", 0, 24'h0, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_smoke_ACTIVE)
endclass : ral_reg_smoke_ACTIVE

// Cell FABRIC — Wishbone interconnect fabric controls
class ral_reg_smoke_FABRIC extends uvm_reg;
	rand uvm_reg_field rb_grant_en; // bit [0]
	     uvm_reg_field reserved_1 ; // bit [31:1]

	function new(string name = "ral_reg_smoke_FABRIC");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.rb_grant_en = uvm_reg_field::type_id::create("rb_grant_en",, get_full_name());
		this.rb_grant_en.configure(this, 1, 0, "RW", 0, 1'h0, 1, 1, 0);
		this.reserved_1 = uvm_reg_field::type_id::create("reserved_1",, get_full_name());
		this.reserved_1.configure(this, 31, 1, "RO", 0, 31'h0, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_smoke_FABRIC)
endclass : ral_reg_smoke_FABRIC

// Cell key_key_0 — 96-bit key (key[31:0] of [95:0])
class ral_reg_smoke_key_key_0 extends uvm_reg;
	rand uvm_reg_field key_0; // bit [31:0]

	function new(string name = "ral_reg_smoke_key_key_0");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.key_0 = uvm_reg_field::type_id::create("key_0",, get_full_name());
		this.key_0.configure(this, 32, 0, "RW", 0, 32'h0, 1, 1, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_smoke_key_key_0)
endclass : ral_reg_smoke_key_key_0

// Cell key_key_1 — 96-bit key (key[63:32] of [95:0])
class ral_reg_smoke_key_key_1 extends uvm_reg;
	rand uvm_reg_field key_1; // bit [31:0]

	function new(string name = "ral_reg_smoke_key_key_1");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.key_1 = uvm_reg_field::type_id::create("key_1",, get_full_name());
		this.key_1.configure(this, 32, 0, "RW", 0, 32'h0, 1, 1, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_smoke_key_key_1)
endclass : ral_reg_smoke_key_key_1

// Cell key_key_2 — 96-bit key (key[95:64] of [95:0])
class ral_reg_smoke_key_key_2 extends uvm_reg;
	rand uvm_reg_field key_2; // bit [31:0]

	function new(string name = "ral_reg_smoke_key_key_2");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.key_2 = uvm_reg_field::type_id::create("key_2",, get_full_name());
		this.key_2.configure(this, 32, 0, "RW", 0, 32'h0, 1, 1, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_smoke_key_key_2)
endclass : ral_reg_smoke_key_key_2

`endif // RAL_SMOKE_SV
