// Generated by autowire plugin wishbone (hbm_ch). Do not edit.
// uvm_reg_block: one sub-block per child bus, one leaf block per regfile hang.
// TagFromAddr aliases are separate submap instances; broadcast windows are comments (no frontdoor).

`ifndef RAL_BLOCK_HBM_CH_SV
`define RAL_BLOCK_HBM_CH_SV

import uvm_pkg::*;
`include "uvm_macros.svh"

`include "../regfile/ral_AWORD.sv"
`include "../regfile/ral_DWORD.sv"

class ral_block_hbm_ch extends uvm_reg_block;
	rand ral_block_aword aword;
	rand ral_block_dword dword0;
	rand ral_block_dword dword1;

	function new(string name = "ral_block_hbm_ch");
		super.new(name, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		default_map = create_map("default_map", 0, 4, UVM_LITTLE_ENDIAN);
		// dword_bcast @ 32'h00000300: broadcast dword_all: one write at this window hits every subscriber
		this.aword = ral_block_aword::type_id::create("aword",, get_full_name());
		this.aword.configure(this, "");
		this.aword.build();
		default_map.add_submap(this.aword.default_map, 32'h00000000);
		this.dword0 = ral_block_dword::type_id::create("dword0",, get_full_name());
		this.dword0.configure(this, "");
		this.dword0.build();
		default_map.add_submap(this.dword0.default_map, 32'h00000100);
		this.dword1 = ral_block_dword::type_id::create("dword1",, get_full_name());
		this.dword1.configure(this, "");
		this.dword1.build();
		default_map.add_submap(this.dword1.default_map, 32'h00000200);
	endfunction: build

	`uvm_object_utils(ral_block_hbm_ch)
endclass : ral_block_hbm_ch

`endif // RAL_BLOCK_HBM_CH_SV
