// HBM demo UVM environment: WB (800 MHz fabric) + APB (100 MHz host, CDC) agents,
// RAL frontdoor on the WB master, directed raw sequences for broadcast windows.
// DUT: hbm_system + 16x hbm_ch_system (generated by plugin wishbone).

`ifndef HBM_TB_PKG_SV
`define HBM_TB_PKG_SV

package hbm_tb_pkg;

	import uvm_pkg::*;
	`include "uvm_macros.svh"
	`include "ral_hbm.sv"

	//----------------------------------------------------------------------
	// Wishbone agent (fabric clock domain)
	//----------------------------------------------------------------------

	class wb_txn extends uvm_sequence_item;
		rand bit [18:0] addr;
		rand bit [31:0] data;
		rand bit        write;
		`uvm_object_utils(wb_txn)
		function new(string name = "wb_txn");
			super.new(name);
		endfunction
	endclass

	typedef uvm_sequencer #(wb_txn) wb_sequencer;

	class wb_driver extends uvm_driver #(wb_txn);
		`uvm_component_utils(wb_driver)
		virtual hbm_wb_if vif;

		function new(string name, uvm_component parent);
			super.new(name, parent);
		endfunction

		function void build_phase(uvm_phase phase);
			if (!uvm_config_db#(virtual hbm_wb_if)::get(this, "", "vif", vif))
				`uvm_fatal("WB/NOVIF", "hbm_wb_if not in config_db")
		endfunction

		task run_phase(uvm_phase phase);
			vif.adr <= '0;
			vif.dat_o <= '0;
			vif.sel <= '0;
			vif.we <= 1'b0;
			vif.cyc <= 1'b0;
			vif.stb <= 1'b0;
			forever begin
				seq_item_port.get_next_item(req);
				@(negedge vif.clk);
				vif.adr   <= req.addr;
				vif.dat_o <= req.data;
				vif.sel   <= 4'hF;
				vif.we    <= req.write;
				vif.cyc   <= 1'b1;
				vif.stb   <= 1'b1;
				do @(posedge vif.clk); while (vif.ack !== 1'b1);
				if (!req.write) req.data = vif.dat_i;
				@(negedge vif.clk);
				vif.cyc <= 1'b0;
				vif.stb <= 1'b0;
				vif.we  <= 1'b0;
				seq_item_port.item_done();
			end
		endtask
	endclass

	class wb_monitor extends uvm_monitor;
		`uvm_component_utils(wb_monitor)
		virtual hbm_wb_if vif;
		uvm_analysis_port #(wb_txn) ap;

		function new(string name, uvm_component parent);
			super.new(name, parent);
			ap = new("ap", this);
		endfunction

		function void build_phase(uvm_phase phase);
			if (!uvm_config_db#(virtual hbm_wb_if)::get(this, "", "vif", vif))
				`uvm_fatal("WB/NOVIF", "hbm_wb_if not in config_db")
		endfunction

		task run_phase(uvm_phase phase);
			wb_txn tr;
			forever begin
				@(posedge vif.clk);
				if (vif.rst_n === 1'b1 && vif.cyc === 1'b1 && vif.stb === 1'b1 && vif.ack === 1'b1) begin
					tr = wb_txn::type_id::create("tr", this);
					tr.addr  = vif.adr;
					tr.write = vif.we;
					tr.data  = vif.we ? vif.dat_o : vif.dat_i;
					ap.write(tr);
				end
			end
		endtask
	endclass

	class wb_agent extends uvm_agent;
		`uvm_component_utils(wb_agent)
		wb_sequencer sqr;
		wb_driver    drv;
		wb_monitor   mon;

		function new(string name, uvm_component parent);
			super.new(name, parent);
		endfunction

		function void build_phase(uvm_phase phase);
			sqr = wb_sequencer::type_id::create("sqr", this);
			drv = wb_driver::type_id::create("drv", this);
			mon = wb_monitor::type_id::create("mon", this);
		endfunction

		function void connect_phase(uvm_phase phase);
			drv.seq_item_port.connect(sqr.seq_item_export);
		endfunction
	endclass

	class wb_reg_adapter extends uvm_reg_adapter;
		`uvm_object_utils(wb_reg_adapter)
		function new(string name = "wb_reg_adapter");
			super.new(name);
		endfunction
		virtual function uvm_sequence_item reg2bus(const ref uvm_reg_bus_op rw);
			wb_txn t = wb_txn::type_id::create("t");
			t.write = (rw.kind == UVM_WRITE);
			t.addr  = rw.addr[18:0];
			t.data  = rw.data;
			return t;
		endfunction
		virtual function void bus2reg(uvm_sequence_item bus_item, ref uvm_reg_bus_op rw);
			wb_txn t;
			if (!$cast(t, bus_item)) `uvm_fatal("WB/ADAPT", "bus_item is not wb_txn")
			rw.kind   = t.write ? UVM_WRITE : UVM_READ;
			rw.addr   = t.addr;
			rw.data   = t.data;
			rw.status = UVM_IS_OK;
		endfunction
	endclass

	//----------------------------------------------------------------------
	// APB agent (PCLK domain, through wb_apb2wb + wb_cdc)
	//----------------------------------------------------------------------

	class apb_txn extends uvm_sequence_item;
		rand bit [18:0] addr;
		rand bit [31:0] data;
		rand bit        write;
		bit             slverr;
		`uvm_object_utils(apb_txn)
		function new(string name = "apb_txn");
			super.new(name);
		endfunction
	endclass

	typedef uvm_sequencer #(apb_txn) apb_sequencer;

	class apb_driver extends uvm_driver #(apb_txn);
		`uvm_component_utils(apb_driver)
		virtual hbm_apb_if vif;

		function new(string name, uvm_component parent);
			super.new(name, parent);
		endfunction

		function void build_phase(uvm_phase phase);
			if (!uvm_config_db#(virtual hbm_apb_if)::get(this, "", "vif", vif))
				`uvm_fatal("APB/NOVIF", "hbm_apb_if not in config_db")
		endfunction

		task run_phase(uvm_phase phase);
			vif.paddr <= '0;
			vif.pwdata <= '0;
			vif.pstrb <= '0;
			vif.pprot <= '0;
			vif.pwrite <= 1'b0;
			vif.psel <= 1'b0;
			vif.penable <= 1'b0;
			forever begin
				seq_item_port.get_next_item(req);
				@(negedge vif.pclk);
				vif.paddr   <= req.addr;
				vif.pwrite  <= req.write;
				vif.pwdata  <= req.data;
				vif.pstrb   <= 4'hF;
				vif.pprot   <= 3'b000;
				vif.psel    <= 1'b1;
				vif.penable <= 1'b0;
				@(negedge vif.pclk);
				vif.penable <= 1'b1;
				do @(posedge vif.pclk); while (vif.pready !== 1'b1);
				if (!req.write) req.data = vif.prdata;
				req.slverr = vif.pslverr;
				@(negedge vif.pclk);
				vif.psel    <= 1'b0;
				vif.penable <= 1'b0;
				seq_item_port.item_done();
			end
		endtask
	endclass

	class apb_monitor extends uvm_monitor;
		`uvm_component_utils(apb_monitor)
		virtual hbm_apb_if vif;
		uvm_analysis_port #(apb_txn) ap;

		function new(string name, uvm_component parent);
			super.new(name, parent);
			ap = new("ap", this);
		endfunction

		function void build_phase(uvm_phase phase);
			if (!uvm_config_db#(virtual hbm_apb_if)::get(this, "", "vif", vif))
				`uvm_fatal("APB/NOVIF", "hbm_apb_if not in config_db")
		endfunction

		task run_phase(uvm_phase phase);
			apb_txn tr;
			forever begin
				@(posedge vif.pclk);
				if (vif.presetn === 1'b1 && vif.psel === 1'b1 && vif.penable === 1'b1 && vif.pready === 1'b1) begin
					tr = apb_txn::type_id::create("tr", this);
					tr.addr   = vif.paddr;
					tr.write  = vif.pwrite;
					tr.data   = vif.pwrite ? vif.pwdata : vif.prdata;
					tr.slverr = vif.pslverr;
					ap.write(tr);
				end
			end
		endtask
	endclass

	class apb_agent extends uvm_agent;
		`uvm_component_utils(apb_agent)
		apb_sequencer sqr;
		apb_driver    drv;
		apb_monitor   mon;

		function new(string name, uvm_component parent);
			super.new(name, parent);
		endfunction

		function void build_phase(uvm_phase phase);
			sqr = apb_sequencer::type_id::create("sqr", this);
			drv = apb_driver::type_id::create("drv", this);
			mon = apb_monitor::type_id::create("mon", this);
		endfunction

		function void connect_phase(uvm_phase phase);
			drv.seq_item_port.connect(sqr.seq_item_export);
		endfunction
	endclass

	class apb_reg_adapter extends uvm_reg_adapter;
		`uvm_object_utils(apb_reg_adapter)
		function new(string name = "apb_reg_adapter");
			super.new(name);
		endfunction
		virtual function uvm_sequence_item reg2bus(const ref uvm_reg_bus_op rw);
			apb_txn t = apb_txn::type_id::create("t");
			t.write = (rw.kind == UVM_WRITE);
			t.addr  = rw.addr[18:0];
			t.data  = rw.data;
			return t;
		endfunction
		virtual function void bus2reg(uvm_sequence_item bus_item, ref uvm_reg_bus_op rw);
			apb_txn t;
			if (!$cast(t, bus_item)) `uvm_fatal("APB/ADAPT", "bus_item is not apb_txn")
			rw.kind   = t.write ? UVM_WRITE : UVM_READ;
			rw.addr   = t.addr;
			rw.data   = t.data;
			rw.status = t.slverr ? UVM_NOT_OK : UVM_IS_OK;
		endfunction
	endclass

	//----------------------------------------------------------------------
	// Environment
	//----------------------------------------------------------------------

	class hbm_env extends uvm_env;
		`uvm_component_utils(hbm_env)
		wb_agent  wb_agt;
		apb_agent apb_agt;
		ral_block_hbm ral;
		uvm_reg_predictor #(wb_txn)  wb_pred;
		uvm_reg_predictor #(apb_txn) apb_pred;
		wb_reg_adapter  wb_adapter;
		apb_reg_adapter apb_adapter;

		function new(string name, uvm_component parent);
			super.new(name, parent);
		endfunction

		function void build_phase(uvm_phase phase);
			wb_agt  = wb_agent::type_id::create("wb_agt", this);
			apb_agt = apb_agent::type_id::create("apb_agt", this);
			wb_adapter  = wb_reg_adapter::type_id::create("wb_adapter");
			apb_adapter = apb_reg_adapter::type_id::create("apb_adapter");
			ral = ral_block_hbm::type_id::create("ral");
			ral.build();
			ral.lock_model();
			ral.reset();
			wb_pred  = uvm_reg_predictor #(wb_txn)::type_id::create("wb_pred", this);
			apb_pred = uvm_reg_predictor #(apb_txn)::type_id::create("apb_pred", this);
		endfunction

		function void connect_phase(uvm_phase phase);
			ral.default_map.set_sequencer(wb_agt.sqr, wb_adapter);
			wb_pred.map     = ral.default_map;
			wb_pred.adapter = wb_adapter;
			wb_agt.mon.ap.connect(wb_pred.bus_in);
			apb_pred.map     = ral.default_map;
			apb_pred.adapter = apb_adapter;
			apb_agt.mon.ap.connect(apb_pred.bus_in);
		endfunction
	endclass

	//----------------------------------------------------------------------
	// Sequences
	//----------------------------------------------------------------------

	// Raw single Wishbone transaction (for broadcast windows, which have no
	// uvm_reg frontdoor).
	class wb_single_seq extends uvm_sequence #(wb_txn);
		`uvm_object_utils(wb_single_seq)
		bit [18:0] addr;
		bit [31:0] data;
		bit        write;
		bit [31:0] rdata;

		function new(string name = "wb_single_seq");
			super.new(name);
		endfunction

		task body();
			wb_txn t = wb_txn::type_id::create("t");
			start_item(t);
			t.addr  = this.addr;
			t.data  = this.data;
			t.write = this.write;
			finish_item(t);
			if (!this.write) this.rdata = t.data;
		endtask
	endclass

	class apb_single_seq extends uvm_sequence #(apb_txn);
		`uvm_object_utils(apb_single_seq)
		bit [18:0] addr;
		bit [31:0] data;
		bit        write;
		bit [31:0] rdata;
		bit        slverr;

		function new(string name = "apb_single_seq");
			super.new(name);
		endfunction

		task body();
			apb_txn t = apb_txn::type_id::create("t");
			start_item(t);
			t.addr  = this.addr;
			t.data  = this.data;
			t.write = this.write;
			finish_item(t);
			if (!this.write) this.rdata = t.data;
			this.slverr = t.slverr;
		endtask
	endclass

	// Base: RAL handle + raw-access helpers + read/compare.
	class hbm_base_seq extends uvm_sequence #(wb_txn);
		`uvm_object_utils(hbm_base_seq)
		ral_block_hbm ral;
		wb_sequencer  wb_sqr;
		apb_sequencer apb_sqr;

		function new(string name = "hbm_base_seq");
			super.new(name);
		endfunction

		// Look up ch<ch>_pstate<ps> by name; block order is not guaranteed
		// (the fabric also hangs a center block).
		function ral_block_hbm_ch chan(int ch, int ps);
			uvm_reg_block q[$];
			ral_block_hbm_ch b;
			ral.get_blocks(q, UVM_NO_HIER);
			foreach (q[i]) begin
				if (q[i].get_name() == $sformatf("ch%0d_pstate%0d", ch, ps)) begin
					if (!$cast(b, q[i])) `uvm_fatal("RAL/CAST", "sub-block is not ral_block_hbm_ch")
					return b;
				end
			end
			`uvm_fatal("RAL/LOOKUP", $sformatf("no sub-block ch%0d_pstate%0d", ch, ps))
		endfunction

		task check_reg(uvm_reg rg, bit [31:0] exp, string what);
			uvm_status_e st;
			uvm_reg_data_t val;
			rg.read(st, val, UVM_FRONTDOOR);
			if (st != UVM_IS_OK)
				`uvm_error("RAL/READ", $sformatf("%s: bus error", what))
			else if (val[31:0] !== exp)
				`uvm_error("RAL/CHECK", $sformatf("%s: exp 32'h%08h got 32'h%08h", what, exp, val[31:0]))
		endtask

		task wb_raw(bit [18:0] addr, bit [31:0] data, bit write, output bit [31:0] rdata);
			wb_single_seq s = wb_single_seq::type_id::create("s");
			s.addr  = addr;
			s.data  = data;
			s.write = write;
			s.start(wb_sqr);
			rdata = s.rdata;
		endtask

		task apb_raw(bit [18:0] addr, bit [31:0] data, bit write, output bit [31:0] rdata);
			apb_single_seq s = apb_single_seq::type_id::create("s");
			s.addr  = addr;
			s.data  = data;
			s.write = write;
			s.start(apb_sqr);
			rdata = s.rdata;
			if (s.slverr)
				`uvm_error("APB/SLVERR", $sformatf("apb %s 19'h%05h -> PSLVERR",
					write ? "write" : "read", addr))
		endtask
	endclass

	// Reset values: pstate0 from the RAL mirror set, pstate1..3 per-copy
	// constants (the RAL carries only the pstate0 reset for a shadowed cell).
	class hbm_reset_seq extends hbm_base_seq;
		`uvm_object_utils(hbm_reset_seq)
		function new(string name = "hbm_reset_seq");
			super.new(name);
		endfunction

		task body();
			// Center CSR in front of channel 0: one instance for all channels and
			// pstates. STATUS mirrors the tb_top RO ties (all_cal_done=1, err_ch=5).
			check_reg(ral.center.ID,     32'h0001_c0de, "center_ID");
			check_reg(ral.center.CH_EN,  32'h0000_ffff, "center_CH_EN");
			check_reg(ral.center.STATUS, 32'h0000_0501, "center_STATUS");
			for (int ch = 0; ch < 16; ch++) begin
				ral_block_hbm_ch b0 = chan(ch, 0);
				string tag = $sformatf("ch%0d", ch);
				check_reg(b0.aword.ID,     32'h0001_a570, {tag, " aword_ID"});
				check_reg(b0.aword.TIMING, 32'h0000_0c0c, {tag, " aword_TIMING@ps0"});
				check_reg(b0.aword.DRIVE,  32'h0000_0004, {tag, " aword_DRIVE@ps0"});
				check_reg(b0.dword0.ID,    32'h0001_d010, {tag, " dword0_ID"});
				check_reg(b0.dword0.VREF,  32'h0000_0030, {tag, " dword0_VREF@ps0"});
				check_reg(b0.dword0.EQ,    32'h0000_0102, {tag, " dword0_EQ@ps0"});
				check_reg(b0.dword1.VREF,  32'h0000_0030, {tag, " dword1_VREF@ps0"});
				check_reg(b0.dword1.EQ,    32'h0000_0102, {tag, " dword1_EQ@ps0"});
				check_reg(b0.dword0.TRAIN, 32'h0000_0000, {tag, " dword0_TRAIN"});
				check_reg(b0.dword1.TRAIN, 32'h0000_0000, {tag, " dword1_TRAIN"});
				for (int ps = 1; ps < 4; ps++) begin
					ral_block_hbm_ch bp = chan(ch, ps);
					bit [7:0] t = 8'(12 + 4*ps);
					string ptag = $sformatf("ch%0d ps%0d", ch, ps);
					check_reg(bp.aword.TIMING, {16'h0, t, t}, {ptag, " aword_TIMING"});
					check_reg(bp.aword.DRIVE,  32'(4 + 2*ps), {ptag, " aword_DRIVE"});
					check_reg(bp.dword0.VREF,  32'(16'h30 + 8*ps), {ptag, " dword0_VREF"});
					check_reg(bp.dword0.EQ,    32'(((ps+1) << 8) | 2*(ps+1)), {ptag, " dword0_EQ"});
					check_reg(bp.dword1.VREF,  32'(16'h30 + 8*ps), {ptag, " dword1_VREF"});
					check_reg(bp.dword1.EQ,    32'(((ps+1) << 8) | 2*(ps+1)), {ptag, " dword1_EQ"});
				end
			end
		endtask
	endclass

	// RO sidebands: tb_top drives a deterministic per-channel pattern, so a
	// STATUS/ID read doubles as a channel-select wiring check.
	class hbm_ro_seq extends hbm_base_seq;
		`uvm_object_utils(hbm_ro_seq)
		function new(string name = "hbm_ro_seq");
			super.new(name);
		endfunction

		task body();
			for (int ch = 0; ch < 16; ch++) begin
				ral_block_hbm_ch b0 = chan(ch, 0);
				string tag = $sformatf("ch%0d", ch);
				check_reg(b0.aword.ID, 32'h0001_a570, {tag, " aword_ID"});
				check_reg(b0.aword.STATUS, 32'(((16'h40 + ch) << 8) | (ch & 1)), {tag, " aword_STATUS"});
				check_reg(b0.dword0.ID, 32'h0001_d010, {tag, " dword0_ID"});
				check_reg(b0.dword0.STATUS, 32'(((16'h80 + ch) << 8) | ((ch >> 1) & 1)), {tag, " dword0_STATUS"});
				check_reg(b0.dword1.ID, 32'h0001_d010, {tag, " dword1_ID"});
				check_reg(b0.dword1.STATUS, 32'(((16'hC0 + ch) << 8) | ((ch + 1) & 1)), {tag, " dword1_STATUS"});
			end
		endtask
	endclass

	// Write + readback of every RW register in all 64 channel/pstate aliases.
	class hbm_rw_seq extends hbm_base_seq;
		`uvm_object_utils(hbm_rw_seq)
		function new(string name = "hbm_rw_seq");
			super.new(name);
		endfunction

		task wr_rd(uvm_reg rg, bit [31:0] mask, string what);
			uvm_status_e st;
			bit [31:0] v = $urandom & mask;
			rg.write(st, v, UVM_FRONTDOOR);
			if (st != UVM_IS_OK) `uvm_error("RAL/WRITE", $sformatf("%s: bus error", what))
			check_reg(rg, v, what);
		endtask

		task body();
			for (int ch = 0; ch < 16; ch++) begin
				for (int ps = 0; ps < 4; ps++) begin
					ral_block_hbm_ch b = chan(ch, ps);
					string tag = $sformatf("ch%0d ps%0d", ch, ps);
					wr_rd(b.aword.TIMING, 32'h0000_ffff, {tag, " aword_TIMING"});
					wr_rd(b.aword.DRIVE,  32'h0000_000f, {tag, " aword_DRIVE"});
					wr_rd(b.dword0.VREF,  32'h0000_007f, {tag, " dword0_VREF"});
					wr_rd(b.dword0.EQ,    32'h0000_1f1f, {tag, " dword0_EQ"});
					wr_rd(b.dword1.VREF,  32'h0000_007f, {tag, " dword1_VREF"});
					wr_rd(b.dword1.EQ,    32'h0000_1f1f, {tag, " dword1_EQ"});
				end
			end
		endtask
	endclass

	// Broadcast writes (no RAL frontdoor): ch_bcast hits all 16 channels;
	// dword_bcast hits both dwords of one channel. Scoped by the pstate tag.
	class hbm_bcast_write_seq extends hbm_base_seq;
		`uvm_object_utils(hbm_bcast_write_seq)
		function new(string name = "hbm_bcast_write_seq");
			super.new(name);
		endfunction

		task body();
			bit [31:0] rd;
			// All channels, dword0+dword1, VREF pstate0: ch_bcast | 0x308.
			wb_raw(19'h11308, 32'h0000_002a, 1'b1, rd);
			for (int ch = 0; ch < 16; ch++) begin
				string tag = $sformatf("ch%0d", ch);
				check_reg(chan(ch, 0).dword0.VREF, 32'h2a, {tag, " ps0 dword0_VREF after ch_bcast"});
				check_reg(chan(ch, 0).dword1.VREF, 32'h2a, {tag, " ps0 dword1_VREF after ch_bcast"});
				// Tag scoping: pstate1 copies keep their reset value.
				check_reg(chan(ch, 1).dword0.VREF, 32'h38, {tag, " ps1 dword0_VREF untouched"});
				// aword does not subscribe to dword_all.
				check_reg(chan(ch, 0).aword.TIMING, 32'h0000_0c0c, {tag, " aword_TIMING untouched"});
			end
			// Channel-local dword broadcast: ch3 window + 0x308.
			wb_raw(19'h04308, 32'h0000_0055, 1'b1, rd);
			check_reg(chan(3, 0).dword0.VREF, 32'h55, "ch3 dword0_VREF after dword_bcast");
			check_reg(chan(3, 0).dword1.VREF, 32'h55, "ch3 dword1_VREF after dword_bcast");
			check_reg(chan(2, 0).dword0.VREF, 32'h2a, "ch2 dword0_VREF untouched");
		endtask
	endclass

	// Broadcast read OR: train_pass_n is one active-low RO bit per lane
	// (16 ch x 2 dword = lane bit [2*ch+dw] of tb_top.train_pass_n).
	// Reading ch_bcast|dword_bcast|TRAIN (0x11310) ORs all 32 lanes into bit 0.
	class hbm_bcast_read_seq extends hbm_base_seq;
		`uvm_object_utils(hbm_bcast_read_seq)
		function new(string name = "hbm_bcast_read_seq");
			super.new(name);
		endfunction

		task body();
			bit [31:0] rd;
			// All lanes pass.
			if (!uvm_hdl_deposit("tb_top.train_pass_n", 32'h0000_0000))
				`uvm_fatal("HDL", "cannot deposit tb_top.train_pass_n")
			wb_raw(19'h11310, 0, 1'b0, rd);
			if (rd !== 32'h0) `uvm_error("BCAST_RD", $sformatf("all-pass: exp 0 got %08h", rd))
			// Lane 7 (ch3 dword1) fails -> OR bit set, via both masters.
			if (!uvm_hdl_deposit("tb_top.train_pass_n", 32'h0000_0080))
				`uvm_fatal("HDL", "cannot deposit tb_top.train_pass_n")
			wb_raw(19'h11310, 0, 1'b0, rd);
			if (rd !== 32'h1) `uvm_error("BCAST_RD", $sformatf("lane7 via WB: exp 1 got %08h", rd))
			apb_raw(19'h11310, 0, 1'b0, rd);
			if (rd !== 32'h1) `uvm_error("BCAST_RD", $sformatf("lane7 via APB: exp 1 got %08h", rd))
			// The failing lane is visible in its own RAL register, others stay 0.
			check_reg(chan(3, 0).dword1.TRAIN, 32'h1, "ch3 dword1_TRAIN");
			check_reg(chan(3, 0).dword0.TRAIN, 32'h0, "ch3 dword0_TRAIN");
			// Channel-local dword broadcast read: lane 10 (ch5 dword0).
			if (!uvm_hdl_deposit("tb_top.train_pass_n", 32'h0000_0400))
				`uvm_fatal("HDL", "cannot deposit tb_top.train_pass_n")
			wb_raw(19'h06310, 0, 1'b0, rd);
			if (rd !== 32'h1) `uvm_error("BCAST_RD", $sformatf("ch5 dword_bcast: exp 1 got %08h", rd))
			wb_raw(19'h05310, 0, 1'b0, rd);
			if (rd !== 32'h0) `uvm_error("BCAST_RD", $sformatf("ch4 dword_bcast: exp 0 got %08h", rd))
			wb_raw(19'h11310, 0, 1'b0, rd);
			if (rd !== 32'h1) `uvm_error("BCAST_RD", $sformatf("ch_bcast sees ch5: exp 1 got %08h", rd))
			// Back to all-pass.
			if (!uvm_hdl_deposit("tb_top.train_pass_n", 32'h0000_0000))
				`uvm_fatal("HDL", "cannot deposit tb_top.train_pass_n")
			wb_raw(19'h11310, 0, 1'b0, rd);
			if (rd !== 32'h0) `uvm_error("BCAST_RD", $sformatf("recovered: exp 0 got %08h", rd))
		endtask
	endclass

	// Concurrency: WB (800 MHz) and APB (100 MHz, CDC) hammer the fabric at
	// the same time. Disjoint registers are data-checked; a shared register
	// is completion-checked (arbiter must block one master, never drop one).
	class hbm_concurrent_seq extends hbm_base_seq;
		`uvm_object_utils(hbm_concurrent_seq)
		function new(string name = "hbm_concurrent_seq");
			super.new(name);
		endfunction

		task body();
			bit [31:0] wb_exp [16][4];
			bit [31:0] apb_exp [16][4];
			bit [31:0] cont_wb;
			bit [31:0] cont_apb;
			fork
				begin : wb_thread
					uvm_status_e st;
					// Sweep repeatedly so WB traffic overlaps the slow CDC/APB stream.
					for (int rep = 0; rep < 20; rep++) begin
						for (int ch = 0; ch < 16; ch++) begin
							for (int ps = 0; ps < 4; ps++) begin
								bit [31:0] v = $urandom & 32'h0000_ffff;
								chan(ch, ps).aword.TIMING.write(st, v, UVM_FRONTDOOR);
								if (st != UVM_IS_OK) `uvm_error("WB/WRITE", "aword_TIMING bus error")
								wb_exp[ch][ps] = v;
							end
						end
					end
					for (int k = 0; k < 8; k++) begin
						bit [31:0] v = $urandom & 32'h0000_ffff;
						chan(0, 0).aword.TIMING.write(st, v, UVM_FRONTDOOR);
						if (st != UVM_IS_OK) `uvm_error("WB/WRITE", "contention bus error")
						cont_wb = v;
					end
				end
				begin : apb_thread
					bit [31:0] rd;
					for (int ch = 0; ch < 16; ch++) begin
						for (int ps = 0; ps < 4; ps++) begin
							bit [31:0] v = $urandom & 32'h0000_1f1f;
							bit [18:0] a = 19'((ch+1)*19'h1000 + ps*19'h20000 + 19'h10c);
							apb_raw(a, v, 1'b1, rd);
							apb_exp[ch][ps] = v;
							apb_raw(a, 0, 1'b0, rd);
							if (rd !== v)
								`uvm_error("APB/RD", $sformatf("ch%0d ps%0d dword0_EQ: exp %08h got %08h", ch, ps, v, rd))
						end
					end
					for (int k = 0; k < 8; k++) begin
						bit [31:0] v = $urandom & 32'h0000_ffff;
						apb_raw(19'h01008, v, 1'b1, rd);
						cont_apb = v;
					end
				end
			join
			// Disjoint registers: every write landed and survived.
			for (int ch = 0; ch < 16; ch++) begin
				for (int ps = 0; ps < 4; ps++) begin
					if (ch != 0 || ps != 0)
						check_reg(chan(ch, ps).aword.TIMING, wb_exp[ch][ps],
							$sformatf("ch%0d ps%0d aword_TIMING after concurrent run", ch, ps));
					check_reg(chan(ch, ps).dword0.EQ, apb_exp[ch][ps],
						$sformatf("ch%0d ps%0d dword0_EQ after concurrent run", ch, ps));
				end
			end
			// Contended register: the last landed write is one of the two masters'.
			begin
				uvm_status_e st;
				uvm_reg_data_t val;
				chan(0, 0).aword.TIMING.read(st, val, UVM_FRONTDOOR);
				if (val[31:0] !== cont_wb && val[31:0] !== cont_apb)
					`uvm_error("ARBIT", $sformatf("ch0 ps0 aword_TIMING: %08h is neither WB %08h nor APB %08h",
						val[31:0], cont_wb, cont_apb))
			end
		endtask
	endclass

	//----------------------------------------------------------------------
	// Tests
	//----------------------------------------------------------------------

	class hbm_base_test extends uvm_test;
		`uvm_component_utils(hbm_base_test)
		hbm_env env;

		function new(string name, uvm_component parent);
			super.new(name, parent);
		endfunction

		virtual hbm_wb_if  wb_vif;
		virtual hbm_apb_if apb_vif;

		function void build_phase(uvm_phase phase);
			env = hbm_env::type_id::create("env", this);
			if (!uvm_config_db#(virtual hbm_wb_if)::get(this, "", "wb_vif", wb_vif))
				`uvm_fatal("TB/NOVIF", "wb_vif not in config_db")
			if (!uvm_config_db#(virtual hbm_apb_if)::get(this, "", "apb_vif", apb_vif))
				`uvm_fatal("TB/NOVIF", "apb_vif not in config_db")
		endfunction

		task run_seq(hbm_base_seq seq);
			seq.ral     = env.ral;
			seq.wb_sqr  = env.wb_agt.sqr;
			seq.apb_sqr = env.apb_agt.sqr;
			seq.start(env.wb_agt.sqr);
		endtask

		task run_phase(uvm_phase phase);
			phase.raise_objection(this);
			fork
				begin
					wait (wb_vif.rst_n === 1'b1 && apb_vif.presetn === 1'b1);
					repeat (4) @(posedge wb_vif.clk);
					main_body();
				end
				begin
					#10ms;
					`uvm_fatal("TIMEOUT", "test exceeded 10 ms")
				end
			join_any
			disable fork;
			phase.drop_objection(this);
		endtask

		virtual task main_body();
		endtask
	endclass

	class hbm_reset_test extends hbm_base_test;
		`uvm_component_utils(hbm_reset_test)
		function new(string name, uvm_component parent);
			super.new(name, parent);
		endfunction
		task main_body();
			hbm_reset_seq seq = hbm_reset_seq::type_id::create("seq");
			run_seq(seq);
		endtask
	endclass

	class hbm_ro_test extends hbm_base_test;
		`uvm_component_utils(hbm_ro_test)
		function new(string name, uvm_component parent);
			super.new(name, parent);
		endfunction
		task main_body();
			hbm_ro_seq seq = hbm_ro_seq::type_id::create("seq");
			run_seq(seq);
		endtask
	endclass

	class hbm_rw_test extends hbm_base_test;
		`uvm_component_utils(hbm_rw_test)
		function new(string name, uvm_component parent);
			super.new(name, parent);
		endfunction
		task main_body();
			hbm_rw_seq seq = hbm_rw_seq::type_id::create("seq");
			run_seq(seq);
		endtask
	endclass

	class hbm_bcast_write_test extends hbm_base_test;
		`uvm_component_utils(hbm_bcast_write_test)
		function new(string name, uvm_component parent);
			super.new(name, parent);
		endfunction
		task main_body();
			hbm_bcast_write_seq seq = hbm_bcast_write_seq::type_id::create("seq");
			run_seq(seq);
		endtask
	endclass

	class hbm_bcast_read_test extends hbm_base_test;
		`uvm_component_utils(hbm_bcast_read_test)
		function new(string name, uvm_component parent);
			super.new(name, parent);
		endfunction
		task main_body();
			hbm_bcast_read_seq seq = hbm_bcast_read_seq::type_id::create("seq");
			run_seq(seq);
		endtask
	endclass

	class hbm_concurrent_test extends hbm_base_test;
		`uvm_component_utils(hbm_concurrent_test)
		function new(string name, uvm_component parent);
			super.new(name, parent);
		endfunction
		task main_body();
			hbm_concurrent_seq seq = hbm_concurrent_seq::type_id::create("seq");
			run_seq(seq);
		endtask
	endclass

endpackage

`endif // HBM_TB_PKG_SV
