// Type-A wishbone generate: one plugin, two DSL types (RegfileDef / BusDef).

import { mkdir } from "node:fs/promises";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import type { WishboneSource, WorkspaceConfig } from "../../workspace.ts";
import { type BusDef, flattenBuses, isBusDef } from "../wishbone-bus/dsl.ts";
import { busModuleName } from "../wishbone-bus/emit.ts";
import {
	attachedSlaves,
	busMapHeaderName,
	busRalBlockName,
	emitBusMapC,
	emitBusMapUvm,
	mapHangsDeep,
} from "../wishbone-bus/emit-map.ts";
import { busNeedsMasterModules } from "../wishbone-bus/emit-master.ts";
import {
	generateDef as generateBusDef,
	generateMasterModules,
	generatePipeModule,
} from "../wishbone-bus/generate.ts";
import { isRegfileDef, type RegfileDef } from "../wishbone-regfile/dsl.ts";
import { writeRegfileExcel } from "../wishbone-regfile/emit-excel.ts";
import { swLayoutFingerprint } from "../wishbone-regfile/emit-sw.ts";
import { generateDef as generateRegfileDef } from "../wishbone-regfile/generate.ts";
import { type LaidRegfile, layoutRegfile } from "../wishbone-regfile/layout.ts";
import { PLUGIN_ID } from "./id.ts";
import { writeIfChanged } from "../../core/write.ts";

export { PLUGIN_ID };

export type WishboneExports = {
	regfiles: RegfileDef[];
	buses: BusDef[];
};

export async function loadWishboneSource(
	source: WishboneSource,
): Promise<WishboneExports> {
	const abs = resolve(source.ts);
	const mod = (await import(pathToFileURL(abs).href)) as Record<
		string,
		unknown
	>;
	const names =
		source.exports ??
		Object.keys(mod).filter((k) => isRegfileDef(mod[k]) || isBusDef(mod[k]));
	if (names.length === 0) {
		throw new Error(
			`wishbone: no RegfileDef or BusDef exports in ${abs} (source "${source.id}")`,
		);
	}
	const regfiles: RegfileDef[] = [];
	const buses: BusDef[] = [];
	const seen = new Set<string>();
	for (const name of names) {
		if (seen.has(name)) {
			throw new Error(
				`wishbone: duplicate export "${name}" in source "${source.id}"`,
			);
		}
		seen.add(name);
		const v = mod[name];
		if (v === undefined) {
			throw new Error(`wishbone: export "${name}" not found in ${abs}`);
		}
		if (isRegfileDef(v)) {
			if (v.name !== name) {
				throw new Error(
					`wishbone: RegfileDef.name "${v.name}" must equal export "${name}"`,
				);
			}
			regfiles.push(v);
		} else if (isBusDef(v)) {
			if (v.name !== name) {
				throw new Error(
					`wishbone: BusDef.name "${v.name}" must equal export "${name}"`,
				);
			}
			buses.push(v);
		} else {
			throw new Error(
				`wishbone: export "${name}" in ${abs} is not a RegfileDef or BusDef`,
			);
		}
	}
	return { regfiles, buses };
}

function emitCUmbrella(headers: readonly string[]): string {
	return [
		"// Generated by autowire plugin wishbone. Do not edit.",
		"// Packed C: field-layout headers + bus maps.",
		"",
		"#ifndef AUTOWIRE_WISHBONE_H",
		"#define AUTOWIRE_WISHBONE_H",
		"",
		...headers.map((h) => `#include "${h}"`),
		"",
		"#endif /* AUTOWIRE_WISHBONE_H */",
		"",
	].join("\n");
}

function emitUvmUmbrella(files: readonly string[]): string {
	return [
		"// Generated by autowire plugin wishbone. Do not edit.",
		"// Packed uvm_reg: cell classes + ral_block maps (not .ralf).",
		"",
		"`ifndef RAL_WISHBONE_SV",
		"`define RAL_WISHBONE_SV",
		"",
		...files.map((f) => `\`include "${f}"`),
		"",
		"`endif",
		"",
	].join("\n");
}

async function packSoftware(
	ws: WorkspaceConfig,
	excelBySheet: Map<string, LaidRegfile>,
	buses: readonly BusDef[],
	force = false,
): Promise<string[]> {
	const paths: string[] = [];
	const mapped = buses.filter((b) => mapHangsDeep(b).length > 0);
	if (ws.wishboneCExport) {
		await mkdir(ws.wishboneCExport, { recursive: true });
		const headers: string[] = [...excelBySheet.keys()].map((s) => `${s}.h`);
		for (const bus of mapped) {
			const name = busMapHeaderName(bus);
			const cPath = join(ws.wishboneCExport, name);
			if (await writeIfChanged(cPath, emitBusMapC(bus), force)) paths.push(cPath);
			headers.push(name);
		}
		if (headers.length > 0) {
			const uPath = join(ws.wishboneCExport, "wishbone.h");
			if (await writeIfChanged(uPath, emitCUmbrella(headers), force)) paths.push(uPath);
		}
	}
	if (ws.wishboneUvmExport) {
		await mkdir(ws.wishboneUvmExport, { recursive: true });
		const files: string[] = [...excelBySheet.keys()].map(
			(s) => `ral_${s.toUpperCase()}.sv`,
		);
		for (const bus of mapped) {
			const name = `${busRalBlockName(bus)}.sv`;
			const uPath = join(ws.wishboneUvmExport, name);
			if (await writeIfChanged(uPath, emitBusMapUvm(bus), force)) paths.push(uPath);
			files.push(name);
		}
		if (files.length > 0) {
			const uPath = join(ws.wishboneUvmExport, "ral_wishbone.sv");
			if (await writeIfChanged(uPath, emitUvmUmbrella(files), force)) paths.push(uPath);
		}
	}
	if (ws.wishboneExcelExport && (excelBySheet.size > 0 || mapped.length > 0)) {
		await writeRegfileExcel(
			ws.wishboneExcelExport,
			[...excelBySheet.values()],
			mapped,
		);
		paths.push(ws.wishboneExcelExport);
	}
	return paths;
}

async function emitRegfile(
	ws: WorkspaceConfig,
	def: RegfileDef,
	leafNames: Map<string, string>,
	swSheets: Map<string, string>,
	excelBySheet: Map<string, LaidRegfile>,
	force = false,
): Promise<string[]> {
	const fp = swLayoutFingerprint(layoutRegfile(def));
	const prev = leafNames.get(def.name);
	if (prev !== undefined) {
		if (prev !== fp) {
			throw new Error(
				`wishbone: duplicate RegfileDef.name "${def.name}" with a different field layout`,
			);
		}
		return [];
	}
	leafNames.set(def.name, fp);
	return generateRegfileDef(ws, def, swSheets, excelBySheet, force);
}

export async function generateAll(
	ws: WorkspaceConfig,
	only?: string,
	force = false,
): Promise<string[]> {
	const paths: string[] = [];
	let sources = ws.wishboneSources;
	if (only) {
		sources = sources.filter((s) => s.id === only);
		if (sources.length === 0) {
			throw new Error(
				`wishbone: no [wishbone.${only}] in autowire.toml (have: ${ws.wishboneSources.map((s) => s.id).join(", ")})`,
			);
		}
	}
	const listedRf: RegfileDef[] = [];
	const buses: BusDef[] = [];
	for (const src of sources) {
		const loaded = await loadWishboneSource(src);
		listedRf.push(...loaded.regfiles);
		buses.push(...loaded.buses);
	}
	const leafNames = new Map<string, string>();
	const swSheets = new Map<string, string>();
	const excelBySheet = new Map<string, LaidRegfile>();
	for (const def of listedRf) {
		paths.push(
			...(await emitRegfile(ws, def, leafNames, swSheets, excelBySheet, force)),
		);
	}
	const fabricNames = new Set<string>();
	const allBuses = flattenBuses(buses);
	if (allBuses.length > 0) {
		const outDir = join(ws.pluginsDir, PLUGIN_ID);
		await mkdir(outDir, { recursive: true });
		const pipe = await generatePipeModule(outDir, force);
		if (pipe) paths.push(pipe);
		if (allBuses.some(busNeedsMasterModules)) {
			paths.push(...(await generateMasterModules(outDir, force)));
		}
	}
	for (const def of allBuses) {
		const mod = busModuleName(def);
		if (fabricNames.has(mod)) {
			throw new Error(`wishbone: duplicate module "${mod}" across sources`);
		}
		fabricNames.add(mod);
		for (const slave of attachedSlaves(def)) {
			const rf = slave.regfile;
			if (!rf) continue;
			paths.push(
				...(await emitRegfile(ws, rf, leafNames, swSheets, excelBySheet)),
			);
		}
		paths.push(...(await generateBusDef(ws, def, force)));
	}
	paths.push(...(await packSoftware(ws, excelBySheet, allBuses, force)));
	return paths;
}
