// Type-A wishbone generate: one plugin, two DSL types (RegfileDef / BusDef).

import { mkdir, rm } from "node:fs/promises";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { writeIfChanged } from "../../core/write.ts";
import type { WishboneSource, WorkspaceConfig } from "../../workspace.ts";
import { type BusDef, flattenBuses, isBusDef } from "../wishbone-bus/dsl.ts";
import { busModuleName } from "../wishbone-bus/emit.ts";
import {
	attachedSlaves,
	busMapHeaderName,
	busMapPkgName,
	busRalBlockName,
	emitBusMapC,
	emitBusMapPkg,
	emitBusMapUvm,
	mapHangsDeep,
} from "../wishbone-bus/emit-map.ts";
import { busNeedsMasterModules } from "../wishbone-bus/emit-master.ts";
import {
	generateDef as generateBusDef,
	generateMasterModules,
	generatePipeModule,
} from "../wishbone-bus/generate.ts";
import { printBusTree } from "../wishbone-bus/print-tree.ts";
import { isRegfileDef, type RegfileDef } from "../wishbone-regfile/dsl.ts";
import { writeRegfileExcel } from "../wishbone-regfile/emit-excel.ts";
import {
	regfilePkgName,
	swLayoutFingerprint,
} from "../wishbone-regfile/emit-sw.ts";
import { generateDef as generateRegfileDef } from "../wishbone-regfile/generate.ts";
import { type LaidRegfile, layoutRegfile } from "../wishbone-regfile/layout.ts";
import { BUS_DIR, PLUGIN_ID, REGFILE_DIR } from "./id.ts";

export { PLUGIN_ID };

export type WishboneExports = {
	regfiles: RegfileDef[];
	buses: BusDef[];
};

export async function loadWishboneSource(
	source: WishboneSource,
): Promise<WishboneExports> {
	const abs = resolve(source.ts);
	const mod = (await import(pathToFileURL(abs).href)) as Record<
		string,
		unknown
	>;
	const names =
		source.exports ??
		Object.keys(mod).filter((k) => isRegfileDef(mod[k]) || isBusDef(mod[k]));
	if (names.length === 0) {
		throw new Error(
			`wishbone: no RegfileDef or BusDef exports in ${abs} (source "${source.id}")`,
		);
	}
	const regfiles: RegfileDef[] = [];
	const buses: BusDef[] = [];
	const seen = new Set<string>();
	for (const name of names) {
		if (seen.has(name)) {
			throw new Error(
				`wishbone: duplicate export "${name}" in source "${source.id}"`,
			);
		}
		seen.add(name);
		const v = mod[name];
		if (v === undefined) {
			throw new Error(`wishbone: export "${name}" not found in ${abs}`);
		}
		if (isRegfileDef(v)) {
			if (v.name !== name) {
				throw new Error(
					`wishbone: RegfileDef.name "${v.name}" must equal export "${name}"`,
				);
			}
			regfiles.push(v);
		} else if (isBusDef(v)) {
			if (v.name !== name) {
				throw new Error(
					`wishbone: BusDef.name "${v.name}" must equal export "${name}"`,
				);
			}
			buses.push(v);
		} else {
			throw new Error(
				`wishbone: export "${name}" in ${abs} is not a RegfileDef or BusDef`,
			);
		}
	}
	return { regfiles, buses };
}

/** Uppercase C-macro stem from the workspace name (a validated C-identifier). */
function guardStem(name: string): string {
	return name.replace(/[^A-Za-z0-9]/g, "_").toUpperCase();
}

function emitCUmbrella(name: string, headers: readonly string[]): string {
	const guard = `${guardStem(name)}_H`;
	return [
		"// Generated by autowire plugin wishbone. Do not edit.",
		"// Packed C: field-layout headers + bus maps.",
		"",
		`#ifndef ${guard}`,
		`#define ${guard}`,
		"",
		...headers.map((h) => `#include "${h}"`),
		"",
		`#endif /* ${guard} */`,
		"",
	].join("\n");
}

function emitUvmUmbrella(name: string, files: readonly string[]): string {
	const guard = `RAL_${guardStem(name)}_SV`;
	return [
		"// Generated by autowire plugin wishbone. Do not edit.",
		"// Packed uvm_reg: cell classes + ral_block maps.",
		"",
		`\`ifndef ${guard}`,
		`\`define ${guard}`,
		"",
		...files.filter((f) => f.endsWith(".sv")).map((f) => `\`include "${f}"`),
		"",
		"`endif",
		"",
	].join("\n");
}

function emitPkgUmbrella(name: string, files: readonly string[]): string {
	const guard = `${guardStem(name)}_PKG_SV`;
	return [
		"// Generated by autowire plugin wishbone. Do not edit.",
		"// Packed SV packages: field bit/mask + bus address maps for non-UVM checks.",
		"",
		`\`ifndef ${guard}`,
		`\`define ${guard}`,
		"",
		...files.filter((f) => f.endsWith(".sv")).map((f) => `\`include "${f}"`),
		"",
		"`endif",
		"",
	].join("\n");
}

async function packSoftware(
	ws: WorkspaceConfig,
	excelBySheet: Map<string, LaidRegfile>,
	buses: readonly BusDef[],
	force = false,
): Promise<string[]> {
	const paths: string[] = [];
	const mapped = buses.filter((b) => mapHangsDeep(b).length > 0);
	if (ws.wishboneCExport) {
		const busDir = join(ws.wishboneCExport, BUS_DIR);
		await mkdir(busDir, { recursive: true });
		const headers: string[] = [...excelBySheet.keys()].map(
			(s) => `${REGFILE_DIR}/${s}.h`,
		);
		for (const bus of mapped) {
			const name = busMapHeaderName(bus);
			const cPath = join(busDir, name);
			if (await writeIfChanged(cPath, emitBusMapC(bus), force))
				paths.push(cPath);
			headers.push(`${BUS_DIR}/${name}`);
		}
		if (headers.length > 0) {
			if (ws.name !== "wishbone")
				await rm(join(ws.wishboneCExport, "wishbone.h"), { force: true });
			const uPath = join(ws.wishboneCExport, `${ws.name}.h`);
			if (await writeIfChanged(uPath, emitCUmbrella(ws.name, headers), force))
				paths.push(uPath);
		}
	}
	if (ws.wishboneUvmExport) {
		const busDir = join(ws.wishboneUvmExport, BUS_DIR);
		await mkdir(busDir, { recursive: true });
		const files: string[] = [...excelBySheet.keys()].map(
			(s) => `${REGFILE_DIR}/ral_${s.toUpperCase()}.sv`,
		);
		for (const bus of mapped) {
			const name = `${busRalBlockName(bus)}.sv`;
			const uPath = join(busDir, name);
			if (await writeIfChanged(uPath, emitBusMapUvm(bus), force))
				paths.push(uPath);
			files.push(`${BUS_DIR}/${name}`);
		}
		if (files.length > 0) {
			if (ws.name !== "wishbone")
				await rm(join(ws.wishboneUvmExport, "ral_wishbone.sv"), {
					force: true,
				});
			const uPath = join(ws.wishboneUvmExport, `ral_${ws.name}.sv`);
			if (await writeIfChanged(uPath, emitUvmUmbrella(ws.name, files), force))
				paths.push(uPath);
		}
	}
	if (ws.wishboneSvRegExport) {
		const busDir = join(ws.wishboneSvRegExport, BUS_DIR);
		await mkdir(busDir, { recursive: true });
		const files: string[] = [...excelBySheet.keys()].map(
			(s) => `${REGFILE_DIR}/${regfilePkgName(s)}.sv`,
		);
		for (const bus of mapped) {
			const name = `${busMapPkgName(bus)}.sv`;
			const pPath = join(busDir, name);
			if (await writeIfChanged(pPath, emitBusMapPkg(bus), force))
				paths.push(pPath);
			files.push(`${BUS_DIR}/${name}`);
		}
		if (files.length > 0) {
			if (ws.name !== "wishbone")
				await rm(join(ws.wishboneSvRegExport, "wishbone_pkg.sv"), {
					force: true,
				});
			const uPath = join(ws.wishboneSvRegExport, `${ws.name}_pkg.sv`);
			if (await writeIfChanged(uPath, emitPkgUmbrella(ws.name, files), force))
				paths.push(uPath);
		}
	}
	if (ws.wishboneExcelExport && (excelBySheet.size > 0 || mapped.length > 0)) {
		await writeRegfileExcel(
			ws.wishboneExcelExport,
			[...excelBySheet.values()],
			mapped,
		);
		paths.push(ws.wishboneExcelExport);
	}
	return paths;
}

async function emitRegfile(
	ws: WorkspaceConfig,
	def: RegfileDef,
	leafNames: Map<string, string>,
	swSheets: Map<string, string>,
	excelBySheet: Map<string, LaidRegfile>,
	force = false,
): Promise<string[]> {
	const fp = swLayoutFingerprint(layoutRegfile(def));
	const prev = leafNames.get(def.name);
	if (prev !== undefined) {
		if (prev !== fp) {
			throw new Error(
				`wishbone: duplicate RegfileDef.name "${def.name}" with a different field layout`,
			);
		}
		return [];
	}
	leafNames.set(def.name, fp);
	return generateRegfileDef(ws, def, swSheets, excelBySheet, force);
}

export async function generateAll(
	ws: WorkspaceConfig,
	only?: string,
	force = false,
): Promise<string[]> {
	const paths: string[] = [];
	let sources = ws.wishboneSources;
	if (only) {
		sources = sources.filter((s) => s.id === only);
		if (sources.length === 0) {
			throw new Error(
				`wishbone: no [wishbone.${only}] in autowire.toml (have: ${ws.wishboneSources.map((s) => s.id).join(", ")})`,
			);
		}
	}
	const listedRf: RegfileDef[] = [];
	const buses: BusDef[] = [];
	for (const src of sources) {
		const loaded = await loadWishboneSource(src);
		listedRf.push(...loaded.regfiles);
		buses.push(...loaded.buses);
	}
	const leafNames = new Map<string, string>();
	const swSheets = new Map<string, string>();
	const excelBySheet = new Map<string, LaidRegfile>();
	for (const def of listedRf) {
		paths.push(
			...(await emitRegfile(ws, def, leafNames, swSheets, excelBySheet, force)),
		);
	}
	const fabricNames = new Set<string>();
	const allBuses = flattenBuses(buses);
	if (allBuses.length > 0) {
		const outDir = join(ws.pluginsDir, PLUGIN_ID, BUS_DIR);
		await mkdir(outDir, { recursive: true });
		const pipe = await generatePipeModule(outDir, force);
		if (pipe) paths.push(pipe);
		if (allBuses.some(busNeedsMasterModules)) {
			paths.push(...(await generateMasterModules(outDir, force)));
		}
	}
	for (const def of allBuses) {
		const mod = busModuleName(def);
		if (fabricNames.has(mod)) {
			throw new Error(`wishbone: duplicate module "${mod}" across sources`);
		}
		fabricNames.add(mod);
		for (const slave of attachedSlaves(def)) {
			const rf = slave.regfile;
			if (!rf) continue;
			paths.push(
				...(await emitRegfile(
					ws,
					rf,
					leafNames,
					swSheets,
					excelBySheet,
					force,
				)),
			);
		}
		paths.push(...(await generateBusDef(ws, def, force)));
		printBusTree(def);
	}
	paths.push(...(await packSoftware(ws, excelBySheet, allBuses, force)));
	return paths;
}
