// Generated by autowire plugin wishbone. Do not edit.
// Packed SV packages: field bit/mask + bus address maps for non-UVM checks.

`ifndef SOC_PKG_SV
`define SOC_PKG_SV

`include "regfile/sha256_pkg.sv"
`include "regfile/smoke_pkg.sv"
`include "bus/sd_sha_map_pkg.sv"
`include "bus/soc_wb_map_pkg.sv"

`endif
