// Pack docs/ and demo/ into the release script, and unpack them on demand.
// Dev runs read the repo. The bundle is generated by scripts/pack-docs.ts.

import { existsSync } from "node:fs";
import { mkdir, readdir, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve, sep } from "node:path";
import { gunzipSync, gzipSync } from "node:zlib";

export type PackedFile = { path: string; bytes: Uint8Array };

const ROOTS = ["docs", "demo"] as const;

function skip(path: string): boolean {
	const parts = path.split("/");
	if (parts.includes(".autowire") || parts.includes("node_modules"))
		return true;
	if (
		parts.includes("obj_dir") ||
		parts.includes("obj_dir_sd") ||
		parts.includes("obj_dir_tb")
	)
		return true;
	return parts.includes("build") && parts.includes("fw");
}

/** Files an agent can unpack. Repo layout, posix paths. */
/** Files an agent can unpack. Repo layout, posix paths. */
export async function collectPackFiles(root: string): Promise<PackedFile[]> {
	const out: PackedFile[] = [];
	const walk = async (dir: string): Promise<void> => {
		for (const entry of await readdir(dir, { withFileTypes: true })) {
			const abs = join(dir, entry.name);
			const rel = relative(root, abs).split(sep).join("/");
			if (skip(rel)) continue;
			if (entry.isDirectory()) await walk(abs);
			else if (entry.isFile())
				out.push({ path: rel, bytes: await Bun.file(abs).bytes() });
		}
	};
	for (const name of ROOTS) await walk(join(root, name));
	const contract = Bun.file(join(root, "AGENTS.md"));
	if (await contract.exists())
		out.push({ path: "AGENTS.md", bytes: await contract.bytes() });
	// DSL sources for standalone SoT authoring (init writes them under dsl/;
	// relative imports between them stay valid). Closure of wishbone-bus/dsl.ts.
	for (const dsl of [
		"src/plugins/wishbone-bus/dsl.ts",
		"src/plugins/wishbone-regfile/dsl.ts",
		"src/plugins/wishbone-regfile/layout.ts",
	]) {
		const f = Bun.file(join(root, dsl));
		if (await f.exists())
			out.push({
				path: dsl.replace(/^src\/plugins\//, "dsl/"),
				bytes: await f.bytes(),
			});
	}
	out.sort((a, b) => a.path.localeCompare(b.path));
	return out;
}

export function encodePack(files: readonly PackedFile[]): Uint8Array {
	const chunks: Uint8Array[] = [];
	const push = (text: string) => chunks.push(new TextEncoder().encode(text));
	for (const file of files) {
		push(`${file.path}\n${file.bytes.byteLength}\n`);
		chunks.push(file.bytes);
	}
	const total = chunks.reduce((sum, chunk) => sum + chunk.byteLength, 0);
	const raw = new Uint8Array(total);
	let at = 0;
	for (const chunk of chunks) {
		raw.set(chunk, at);
		at += chunk.byteLength;
	}
	return gzipSync(raw);
}

export function decodePack(packed: Uint8Array): PackedFile[] {
	const raw = gunzipSync(packed);
	const files: PackedFile[] = [];
	let at = 0;
	while (at < raw.byteLength) {
		const nl = raw.indexOf(10, at);
		if (nl < 0) throw new Error("docs pack: truncated path");
		const path = new TextDecoder().decode(raw.subarray(at, nl));
		const nl2 = raw.indexOf(10, nl + 1);
		if (nl2 < 0) throw new Error(`docs pack: truncated size for ${path}`);
		const size = Number(new TextDecoder().decode(raw.subarray(nl + 1, nl2)));
		if (!Number.isInteger(size) || size < 0) {
			throw new Error(`docs pack: bad size for ${path}`);
		}
		const start = nl2 + 1;
		files.push({ path, bytes: raw.subarray(start, start + size) });
		at = start + size;
	}
	return files;
}

let packCache: Promise<PackedFile[]> | null = null;

/** Docs pack for this process. Cached: the pack cannot change mid-run, and the
 *  dev fallback walks the whole docs/+demo/ tree (too slow to repeat per call). */
export function loadPack(): Promise<PackedFile[]> {
	packCache ??= (async () => {
		const { DOC_PACK } = await import("./doc-pack.generated.ts");
		if (DOC_PACK.byteLength > 0) return decodePack(DOC_PACK);
		return collectPackFiles(join(import.meta.dir, "..", ".."));
	})();
	return packCache;
}

/** Wishbone DSL target dir inside the workspace (generated, self-healing). */
export function wishboneDslDir(root: string): string {
	return join(root, ".autowire", "dsl");
}

/** Write dsl/ pack entries into .autowire/dsl/ when missing.
 *  Self-healing: .autowire is a deletable cache, so plugin runs re-create the
 *  DSL whenever it is gone. Existing files are left untouched. */
export async function ensureWishboneDsl(root: string): Promise<string[]> {
	const pack = await loadPack();
	const written: string[] = [];
	for (const f of pack.filter((f) => f.path.startsWith("dsl/"))) {
		const target = join(
			wishboneDslDir(root),
			f.path.slice("dsl/".length),
		);
		if (existsSync(target)) continue;
		await mkdir(dirname(target), { recursive: true });
		await Bun.write(target, f.bytes);
		written.push(target);
	}
	return written;
}

export async function unpackPack(
	files: readonly PackedFile[],
	dest: string,
): Promise<string[]> {
	const root = resolve(dest);
	const written: string[] = [];
	for (const file of files) {
		if (
			file.path.includes("..") ||
			file.path.startsWith("/") ||
			file.path.includes(":")
		) {
			throw new Error(`docs pack: refused path ${file.path}`);
		}
		const abs = resolve(root, file.path);
		if (abs !== root && !abs.startsWith(`${root}${sep}`)) {
			throw new Error(`docs pack: path escapes destination: ${file.path}`);
		}
		await mkdir(dirname(abs), { recursive: true });
		await writeFile(abs, file.bytes);
		written.push(abs);
	}
	return written;
}
