// Pack docs/ and demo/ into the release script, and unpack them on demand.
// Dev runs read the repo. The bundle is generated by scripts/pack-docs.ts.

import { spawnSync } from "node:child_process";
import {
	existsSync,
	mkdirSync,
	mkdtempSync,
	rmSync,
	writeFileSync,
} from "node:fs";
import { chmod, mkdir, readdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, relative, resolve, sep } from "node:path";

export type PackedFile = { path: string; bytes: Uint8Array };

const ROOTS = ["docs", "demo"] as const;

function skip(path: string, ipFiles?: ReadonlySet<string>): boolean {
	const parts = path.split("/");
	if (parts.includes(".autowire") || parts.includes("node_modules"))
		return true;
	if (
		parts.includes("obj_dir") ||
		parts.includes("obj_dir_sd") ||
		parts.includes("obj_dir_tb")
	)
		return true;
	// IP submodules ship full upstream doc/bench trees; the demo only needs
	// the sources its filelists reference (closure computed by ipClosure).
	if (ipFiles && /^demo\/[^/]+\/ip\//.test(path) && !ipFiles.has(path))
		return true;
	// Submodule .git pointer files hold a machine-specific gitdir path; .github
	// is upstream CI config. Neither is docs/demo content. (.gitignore stays:
	// it documents which sibling files are generated.)
	if (parts.includes(".git") || parts.includes(".github")) return true;
	// Generated exports and tool junk: wishbone Excel is an export (SoT is the
	// TS), ucli.key / ~$* are VCS / Excel leftovers. All git-ignored.
	const name = parts.at(-1) ?? "";
	if (name.endsWith(".xlsx") || name === "ucli.key" || name.startsWith("~$"))
		return true;
	// Simulator work dirs (vcs/work: simv, .a/.so archives, logs) are local
	// build artifacts — git-ignored, never part of the shipped docs/demo set.
	for (let i = 0; i + 1 < parts.length; i++)
		if (parts[i] === "vcs" && parts[i + 1] === "work") return true;
	return parts.includes("build") && parts.includes("fw");
}

/** Files an agent can unpack. Repo layout, posix paths. demo/<name>/ip/ is
 *  trimmed to the filelist closure and ships with patches/ already applied. */
export async function collectPackFiles(root: string): Promise<PackedFile[]> {
	const ipFiles = await ipClosure(root);
	const out: PackedFile[] = [];
	const walk = async (dir: string): Promise<void> => {
		for (const entry of await readdir(dir, { withFileTypes: true })) {
			const abs = join(dir, entry.name);
			const rel = relative(root, abs).split(sep).join("/");
			if (skip(rel, ipFiles)) continue;
			if (entry.isDirectory()) await walk(abs);
			else if (entry.isFile())
				out.push({ path: rel, bytes: await Bun.file(abs).bytes() });
		}
	};
	for (const name of ROOTS) await walk(join(root, name));
	const contract = Bun.file(join(root, "AGENTS.md"));
	if (await contract.exists())
		out.push({ path: "AGENTS.md", bytes: await contract.bytes() });
	// DSL sources for standalone SoT authoring (init writes them under dsl/;
	// relative imports between them stay valid). Closure of wishbone-bus/dsl.ts.
	for (const dsl of [
		"src/plugins/wishbone-bus/dsl.ts",
		"src/plugins/wishbone-regfile/dsl.ts",
		"src/plugins/wishbone-regfile/layout.ts",
	]) {
		const f = Bun.file(join(root, dsl));
		if (await f.exists())
			out.push({
				path: dsl.replace(/^src\/plugins\//, "dsl/"),
				bytes: await f.bytes(),
			});
	}
	out.sort((a, b) => a.path.localeCompare(b.path));
	rewriteDemoDslImports(out);
	await applyDemoPatches(root, out);
	return out;
}

/** Repo demos import the wishbone DSL from src/plugins/...; a standalone
 *  unpacked tree has no src/. Rewrite packed sot/*.ts to the self-healing
 *  .autowire/dsl/ copy (plugin wishbone run restores it when missing). */
function rewriteDemoDslImports(files: PackedFile[]): void {
	const REPO_DSL =
		/(["'])\.\.\/\.\.\/\.\.\/src\/plugins\/(wishbone-(?:bus|regfile))\//g;
	for (const file of files) {
		if (!/^demo\/[^/]+\/sot\/.*\.ts$/.test(file.path)) continue;
		const text = new TextDecoder().decode(file.bytes);
		const rewritten = text.replace(
			REPO_DSL,
			(_m, quote: string, mod: string) => `${quote}../.autowire/dsl/${mod}/`,
		);
		if (rewritten.includes("src/plugins/"))
			throw new Error(
				`docs pack: ${file.path} has a src/plugins import at an unexpected depth`,
			);
		if (rewritten !== text) file.bytes = new TextEncoder().encode(rewritten);
	}
}

/** demo/<name>/ip/ sources referenced by that demo's .f filelists. Paths in
 *  the lists are workspace-relative; the set holds pack paths
 *  ("demo/<name>/ip/..."). Anything else under ip/ (upstream docs, benches,
 *  vendor PDFs) stays out of the pack. */
async function ipClosure(root: string): Promise<Set<string>> {
	const files = new Set<string>();
	const demosDir = join(root, "demo");
	if (!existsSync(demosDir)) return files;
	for (const demo of await readdir(demosDir, { withFileTypes: true })) {
		if (!demo.isDirectory()) continue;
		const demoAbs = join(demosDir, demo.name);
		const demoRel = `demo/${demo.name}`;
		const stack = [demoAbs];
		while (stack.length > 0) {
			const dir = stack.pop() as string;
			for (const entry of await readdir(dir, { withFileTypes: true })) {
				const abs = join(dir, entry.name);
				const rel = `${demoRel}/${relative(demoAbs, abs).split(sep).join("/")}`;
				if (skip(rel)) continue;
				if (entry.isDirectory()) {
					stack.push(abs);
				} else if (entry.isFile() && entry.name.endsWith(".f")) {
					for (const line of (await Bun.file(abs).text()).split("\n")) {
						const item = line.replace(/#.*/, "").trim();
						if (!item.startsWith("ip/")) continue;
						// Parent dirs too: skip() filters directories before the
						// walk descends into them.
						let p = `${demoRel}/${item}`;
						while (p !== demoRel) {
							files.add(p);
							p = p.slice(0, p.lastIndexOf("/"));
						}
					}
				}
			}
		}
	}
	return files;
}

/** Demo patches are the SoT for local IP fixes (submodules stay pristine
 *  upstream). The pack ships the IP with patches already applied so the
 *  unpacked demo builds out of the box; apply.sh stays, idempotent. */
async function applyDemoPatches(
	root: string,
	files: PackedFile[],
): Promise<void> {
	const demosDir = join(root, "demo");
	if (!existsSync(demosDir)) return;
	for (const demo of await readdir(demosDir, { withFileTypes: true })) {
		if (!demo.isDirectory()) continue;
		const patchesDir = join(demosDir, demo.name, "patches");
		if (!existsSync(patchesDir)) continue;
		for (const entry of await readdir(patchesDir, { withFileTypes: true })) {
			if (!entry.isFile() || !entry.name.endsWith(".patch")) continue;
			const patchAbs = join(patchesDir, entry.name);
			const patchText = await Bun.file(patchAbs).text();
			const targets = [...patchText.matchAll(/^diff --git a\/(\S+) b\//gm)].map(
				// Group 1 always matches: the regex requires it.
				(m) => m[1] as string,
			);
			const prefix = `demo/${demo.name}/ip/`;
			const hits = targets.map((target) => {
				const file = files.find(
					(f) => f.path.startsWith(prefix) && f.path.endsWith(`/${target}`),
				);
				if (!file)
					throw new Error(
						`docs pack: ${demo.name}/${entry.name} target not in pack: ${target}`,
					);
				return { file, target };
			});
			const tmp = mkdtempSync(join(tmpdir(), "aw-patch-"));
			try {
				for (const { file, target } of hits) {
					const dest = join(tmp, target);
					mkdirSync(dirname(dest), { recursive: true });
					writeFileSync(dest, file.bytes);
				}
				const gitApply = (...args: string[]) =>
					spawnSync("git", ["apply", ...args, patchAbs], { cwd: tmp });
				if (gitApply("--reverse", "--check").status === 0) {
					// Working tree already carries the patch; bytes are correct.
				} else if (gitApply("--check").status === 0) {
					const applied = gitApply();
					if (applied.status !== 0)
						throw new Error(
							`docs pack: git apply ${entry.name}: ${applied.stderr}`,
						);
					for (const { file, target } of hits)
						file.bytes = await Bun.file(join(tmp, target)).bytes();
				} else {
					throw new Error(
						`docs pack: ${entry.name} applies neither forward nor reverse (submodule not at the expected upstream?)`,
					);
				}
			} finally {
				rmSync(tmp, { recursive: true, force: true });
			}
		}
	}
}

// zstd level 22: matches brotli q11 pack size at ~7x faster build-time
// compression; decompression is native and instant at CLI scale.
// (Measured on the 11MB raw pack: zstd-22 5.47MB/3.7s, brotli-q11 5.47MB/26s.)
export function encodePack(files: readonly PackedFile[]): Uint8Array {
	const chunks: Uint8Array[] = [];
	const push = (text: string) => chunks.push(new TextEncoder().encode(text));
	for (const file of files) {
		push(`${file.path}\n${file.bytes.byteLength}\n`);
		chunks.push(file.bytes);
	}
	const total = chunks.reduce((sum, chunk) => sum + chunk.byteLength, 0);
	const raw = new Uint8Array(total);
	let at = 0;
	for (const chunk of chunks) {
		raw.set(chunk, at);
		at += chunk.byteLength;
	}
	return Bun.zstdCompressSync(raw, { level: 22 });
}

export function decodePack(packed: Uint8Array): PackedFile[] {
	const raw = Bun.zstdDecompressSync(packed);
	const files: PackedFile[] = [];
	let at = 0;
	while (at < raw.byteLength) {
		const nl = raw.indexOf(10, at);
		if (nl < 0) throw new Error("docs pack: truncated path");
		const path = new TextDecoder().decode(raw.subarray(at, nl));
		const nl2 = raw.indexOf(10, nl + 1);
		if (nl2 < 0) throw new Error(`docs pack: truncated size for ${path}`);
		const size = Number(new TextDecoder().decode(raw.subarray(nl + 1, nl2)));
		if (!Number.isInteger(size) || size < 0) {
			throw new Error(`docs pack: bad size for ${path}`);
		}
		const start = nl2 + 1;
		files.push({ path, bytes: raw.subarray(start, start + size) });
		at = start + size;
	}
	return files;
}

let packCache: Promise<PackedFile[]> | null = null;

/** Docs pack for this process. Cached: the pack cannot change mid-run, and the
 *  dev fallback walks the whole docs/+demo/ tree (too slow to repeat per call). */
export function loadPack(): Promise<PackedFile[]> {
	packCache ??= (async () => {
		// Lazy: the generated module is a multi-MB string literal; importing
		// it statically would decode it on every cold start.
		const { docPackB64 } = await import("./doc-pack.generated.ts");
		const b64 = docPackB64();
		if (b64) return decodePack(Buffer.from(b64, "base64"));
		return collectPackFiles(join(import.meta.dir, "..", ".."));
	})();
	return packCache;
}

/** Wishbone DSL target dir inside the workspace (generated, self-healing). */
export function wishboneDslDir(root: string): string {
	return join(root, ".autowire", "dsl");
}

/** Write dsl/ pack entries into .autowire/dsl/ when missing.
 *  Self-healing: .autowire is a deletable cache, so plugin runs re-create the
 *  DSL whenever it is gone. Existing files are left untouched. */
export async function ensureWishboneDsl(root: string): Promise<string[]> {
	const pack = await loadPack();
	const written: string[] = [];
	for (const f of pack.filter((f) => f.path.startsWith("dsl/"))) {
		const target = join(wishboneDslDir(root), f.path.slice("dsl/".length));
		if (existsSync(target)) continue;
		await mkdir(dirname(target), { recursive: true });
		await Bun.write(target, f.bytes);
		written.push(target);
	}
	return written;
}

export async function unpackPack(
	files: readonly PackedFile[],
	dest: string,
): Promise<string[]> {
	const root = resolve(dest);
	const written: string[] = [];
	for (const file of files) {
		if (
			file.path.includes("..") ||
			file.path.startsWith("/") ||
			file.path.includes(":")
		) {
			throw new Error(`docs pack: refused path ${file.path}`);
		}
		const abs = resolve(root, file.path);
		if (abs !== root && !abs.startsWith(`${root}${sep}`)) {
			throw new Error(`docs pack: path escapes destination: ${file.path}`);
		}
		await mkdir(dirname(abs), { recursive: true });
		await writeFile(abs, file.bytes);
		// The archive stores bytes only. Shell entry points (demo sim run.sh)
		// are executable in git; restore that bit on unpack.
		if (file.path.endsWith(".sh")) await chmod(abs, 0o755);
		written.push(abs);
	}
	return written;
}
