// Generated by autowire dump (unit "phy_wrap"). Do not edit: SoT is the connect HTML.
module gray_tap #(
	parameter TW = 16
) (
	output [TW-1:0] tap_out_o,
	input [(TW)-1:0] tap_in
);
	localparam gray_tap__u_pair__GWIDTH = TW;

	gray_pair #(.GWIDTH(gray_tap__u_pair__GWIDTH)) u_pair (
		.pair_in(tap_in),
		.pair_out(tap_out_o)
	);

endmodule
