// Generated by autowire dump (unit "phy_wrap"). Do not edit: SoT is the connect HTML.
module gray_pair #(
	parameter GWIDTH = 8
) (
	input wire [GWIDTH-1:0] pair_in,
	output wire [GWIDTH-1:0] pair_out
);
	logic [(GWIDTH)-1:0] pair_mid;

	cc_binary_to_gray #(
		.Width(GWIDTH)
	) u_b2g (
		.a_i(pair_in),
		.z_o(pair_mid)
	);
	cc_gray_to_binary #(
		.Width(GWIDTH)
	) u_g2b (
		.a_i(pair_mid),
		.z_o(pair_out)
	);

endmodule
