// Generated by autowire dump (unit "phy_wrap"). Do not edit: SoT is the connect HTML.
module gray_tap #(
	parameter TW = 16
) (
	output wire [TW-1:0] tap_out_o,
	input wire [(TW)-1:0] tap_in
);
	gray_pair #(
		.GWIDTH(TW)
	) u_pair (
		.pair_in(tap_in),
		.pair_out(tap_out_o)
	);

endmodule
