// Generated by autowire dump (unit "phy_wrap"). Do not edit: SoT is the connect HTML.
module phy_wrap #(
	parameter CNT_W = 8
) (
	output wire [2*CNT_W-1:0] phy_gray_o,
	output wire [(((CNT_W)) == 1 ? 1:$clog2(((CNT_W))))-1:0] phy_bin_o,
	input logic clk_i,
	input logic rst_ni,
	input logic cnt_0_clr,
	input logic cnt_0_en,
	input logic cnt_0_load,
	input wire [15:0] cnt_d_bus,
	input logic cnt_shared_down,
	input logic cnt_1_clr,
	input logic cnt_alt_en_1,
	input logic cnt_1_load,
	input logic [((CNT_W))-1:0] oh_onehot
);
	localparam GRAY_W = CNT_W;

	wire [15:0] cnt_q_bus;

	cc_counter #(
		.Width(CNT_W)
	) u_cnt_0 (
		.clk_i(clk_i),
		.rst_ni(rst_ni),
		.clr_i(cnt_0_clr),
		.en_i(cnt_0_en),
		.load_i(cnt_0_load),
		.down_i(cnt_shared_down),
		.d_i(cnt_d_bus[7:0]),
		.q_o(cnt_q_bus[7:0]),
		.overflow_o()
	);
	cc_counter #(
		.Width(CNT_W)
	) u_cnt_1 (
		.clk_i(clk_i),
		.rst_ni(rst_ni),
		.clr_i(cnt_1_clr),
		.en_i(cnt_alt_en_1),
		.load_i(cnt_1_load),
		.down_i(cnt_shared_down),
		.d_i(cnt_d_bus[15:8]),
		.q_o(cnt_q_bus[15:8]),
		.overflow_o()
	);
	gray_tap u_tap (
		.tap_out_o(phy_gray_o),
		.tap_in(cnt_q_bus)
	);
	cc_onehot_to_bin #(
		.OnehotWidth(GRAY_W)
	) u_oh2b (
		.onehot_i(oh_onehot),
		.bin_o(phy_bin_o)
	);

endmodule
