// Generated by autowire dump (unit "phy_wrap_tb"). Do not edit: SoT is the connect HTML.
module phy_wrap_tb #(
	parameter TB_W = 16
) (
	output wire [TB_W-1:0] tb_gray_o,
	output wire [((((TB_W/2))) == 1 ? 1:$clog2((((TB_W/2)))))-1:0] tb_bin_o,
	input wire tb_clk,
	input wire tb_rst_n,
	input wire tb_cnt0_clr,
	input wire tb_cnt0_en,
	input wire tb_cnt1_clr,
	input wire tb_alt_en,
	input wire tb_cnt0_load,
	input wire tb_cnt1_load,
	input wire [15:0] tb_d_bus,
	input wire tb_down,
	input wire [(((TB_W/2)))-1:0] tb_onehot,
	input logic lfsr_en
);
	localparam phy_wrap_tb__u_dut__CNT_W = TB_W/2;
	localparam phy_wrap_tb__u_lfsr__OutWidth = TB_W/2;

	logic [phy_wrap_tb__u_lfsr__OutWidth-1:0] lfsr_out;

	phy_wrap #(
		.CNT_W(phy_wrap_tb__u_dut__CNT_W)
	) u_dut (
		.phy_gray_o(tb_gray_o),
		.phy_bin_o(tb_bin_o),
		.clk_i(tb_clk),
		.rst_ni(tb_rst_n),
		.cnt_0_clr(tb_cnt0_clr),
		.cnt_0_en(tb_cnt0_en),
		.cnt_0_load(tb_cnt0_load),
		.cnt_d_bus(tb_d_bus),
		.cnt_shared_down(tb_down),
		.cnt_1_clr(tb_cnt1_clr),
		.cnt_alt_en_1(tb_alt_en),
		.cnt_1_load(tb_cnt1_load),
		.oh_onehot(tb_onehot)
	);
	cc_lfsr #(
		.LfsrWidth(16),
		.OutWidth(phy_wrap_tb__u_lfsr__OutWidth)
	) u_lfsr (
		.clk_i(tb_clk),
		.rst_ni(tb_rst_n),
		.clr_i(1'b0),
		.en_i(lfsr_en),
		.out_o(lfsr_out)
	);

endmodule
