// Generated by autowire plugin wishbone-regfile (table sub_module_a). Do not edit.
// Sub-module A — omit offset, auto layout
module sub_module_a_regfile (
	input  logic        i_clk,
	input  logic        i_rst_n,
	input  logic        i_wb_cyc,
	input  logic        i_wb_stb,
	input  logic        i_wb_we,
	input  logic [7:0]  i_wb_adr,
	input  logic [31:0] i_wb_dat,
	input  logic [3:0]  i_wb_sel,
	input  logic [1:0]  i_wb_tga,
	output logic        o_wb_ack,
	output logic [31:0] o_wb_dat,
	output logic        rg_enable,
	output logic [1:0]  o_lane_sel,
	output logic [2:0]  rg_mode,
	output logic [7:0]  rg_lane_cfg,
	input  logic        ro_busy,
	output logic        c_rg_irq_sticky,
	output logic        p_rg_pulse_cmd,
	output logic [31:0] rg_key_0,
	output logic [31:0] rg_key_1,
	output logic [31:0] rg_key_2,
	output logic [31:0] rg_word,
	output logic [15:0] rg_capture,
	input  logic        rg_capture_strb,
	input  logic [15:0] rg_capture_hwdata,
	input  logic [31:0] ext_data,
	output logic [31:0] ext_data_wdata,
	output logic        ext_data_wren,
	output logic        ext_data_rden,
	output logic        ext_data_rst,
	input  logic        ext_data_ready,
	output logic        rg_flag
);

	logic        hit;
	logic        wr_fire;
	logic        rd_fire;
	logic        addr_hit_0;
	logic        wr_sel_0;
	logic        rd_sel_0;
	logic        addr_hit_10;
	logic        wr_sel_10;
	logic        rd_sel_10;
	logic        addr_hit_20;
	logic        wr_sel_20;
	logic        rd_sel_20;
	logic        addr_hit_30;
	logic        wr_sel_30;
	logic        rd_sel_30;
	logic        addr_hit_40;
	logic        wr_sel_40;
	logic        rd_sel_40;
	logic        addr_hit_44;
	logic        wr_sel_44;
	logic        rd_sel_44;
	logic        addr_hit_48;
	logic        wr_sel_48;
	logic        rd_sel_48;
	logic        addr_hit_4c;
	logic        wr_sel_4c;
	logic        rd_sel_4c;
	logic        addr_hit_50;
	logic        wr_sel_50;
	logic        rd_sel_50;
	logic [1:0]  raw_lane;
	logic [3:0]  mask_lane;
	logic        rg_enable_q [4];
	logic [2:0]  rg_mode_q [4];
	logic [7:0]  rg_lane_cfg_q [4];
	logic        c_rg_irq_sticky_q;
	logic [31:0] rg_key_0_q;
	logic [31:0] rg_key_1_q;
	logic [31:0] rg_key_2_q;
	logic [31:0] rg_word_q;
	logic [15:0] rg_capture_q;
	logic        rg_flag_q;
	logic [31:0] rd_data;

	// Addr: 0x0 RegCell: CFG0 — Main config
	assign addr_hit_0 = (i_wb_adr[7:2] == 6'd0);
	// Addr: 0x10 RegCell: STATUS — Status
	assign addr_hit_10 = (i_wb_adr[7:2] == 6'd4);
	// Addr: 0x20 RegCell: ctrl_key_0 — 96-bit key; auto-split + auto offset
	assign addr_hit_20 = (i_wb_adr[7:2] == 6'd8);
	// Addr: 0x30 RegCell: ctrl_key_1 — 96-bit key; auto-split + auto offset
	assign addr_hit_30 = (i_wb_adr[7:2] == 6'd12);
	// Addr: 0x40 RegCell: ctrl_key_2 — 96-bit key; auto-split + auto offset
	assign addr_hit_40 = (i_wb_adr[7:2] == 6'd16);
	// Addr: 0x44 RegCell: SCRATCH — Scratch pad
	assign addr_hit_44 = (i_wb_adr[7:2] == 6'd17);
	// Addr: 0x48 RegCell: HW_FEED — Hardware feed
	assign addr_hit_48 = (i_wb_adr[7:2] == 6'd18);
	// Addr: 0x4c RegCell: EXT_FIFO — External FIFO window
	assign addr_hit_4c = (i_wb_adr[7:2] == 6'd19);
	// Addr: 0x50 RegCell: SOLO — Independent cell
	assign addr_hit_50 = (i_wb_adr[7:2] == 6'd20);

	assign hit = |{
		addr_hit_0,
		addr_hit_10,
		addr_hit_20,
		addr_hit_30,
		addr_hit_40,
		addr_hit_44,
		addr_hit_48,
		addr_hit_4c,
		addr_hit_50
	};
	assign wr_fire = i_wb_cyc && i_wb_stb &&  i_wb_we;
	assign rd_fire = i_wb_cyc && i_wb_stb && ~i_wb_we;

	assign wr_sel_0 = wr_fire && hit && addr_hit_0;
	assign rd_sel_0 = rd_fire && hit && addr_hit_0;
	assign wr_sel_10 = wr_fire && hit && addr_hit_10;
	assign rd_sel_10 = rd_fire && hit && addr_hit_10;
	assign wr_sel_20 = wr_fire && hit && addr_hit_20;
	assign rd_sel_20 = rd_fire && hit && addr_hit_20;
	assign wr_sel_30 = wr_fire && hit && addr_hit_30;
	assign rd_sel_30 = rd_fire && hit && addr_hit_30;
	assign wr_sel_40 = wr_fire && hit && addr_hit_40;
	assign rd_sel_40 = rd_fire && hit && addr_hit_40;
	assign wr_sel_44 = wr_fire && hit && addr_hit_44;
	assign rd_sel_44 = rd_fire && hit && addr_hit_44;
	assign wr_sel_48 = wr_fire && hit && addr_hit_48;
	assign rd_sel_48 = rd_fire && hit && addr_hit_48;
	assign wr_sel_4c = wr_fire && hit && addr_hit_4c;
	assign rd_sel_4c = rd_fire && hit && addr_hit_4c;
	assign wr_sel_50 = wr_fire && hit && addr_hit_50;
	assign rd_sel_50 = rd_fire && hit && addr_hit_50;

	assign raw_lane = i_wb_tga[1:0];
	always_comb begin
		mask_lane = 4'h0;
		unique case (raw_lane)
			2'd3: mask_lane = 4'hf;
		default: mask_lane = 4'h0; // miss → nop
		endcase
	end
	// one-hot mask → bin index (first set bit); miss keeps 0
	always_comb begin
		o_lane_sel = 2'd0;
		for (int __i = 0; __i < 4; __i++) begin
			if (mask_lane[__i]) o_lane_sel = 2'(__i);
		end
	end

	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) begin
			rg_enable_q[0] <= 1'h0;
			rg_enable_q[1] <= 1'h0;
			rg_enable_q[2] <= 1'h0;
			rg_enable_q[3] <= 1'h0;
		end else begin
			if (wr_sel_0) begin
				for (int __c = 0; __c < 4; __c++) begin
					if (mask_lane[__c]) rg_enable_q[__c] <= i_wb_dat[0:0];
				end
			end
		end
	end
	assign rg_enable = rg_enable_q[o_lane_sel];
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) begin
			rg_mode_q[0] <= 3'h0;
			rg_mode_q[1] <= 3'h0;
			rg_mode_q[2] <= 3'h0;
			rg_mode_q[3] <= 3'h0;
		end else begin
			if (wr_sel_0) begin
				for (int __c = 0; __c < 4; __c++) begin
					if (mask_lane[__c]) rg_mode_q[__c] <= i_wb_dat[10:8];
				end
			end
		end
	end
	assign rg_mode = rg_mode_q[o_lane_sel];
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) begin
			rg_lane_cfg_q[0] <= 8'h10;
			rg_lane_cfg_q[1] <= 8'h20;
			rg_lane_cfg_q[2] <= 8'h30;
			rg_lane_cfg_q[3] <= 8'h40;
		end else begin
			if (wr_sel_0) begin
				for (int __c = 0; __c < 4; __c++) begin
					if (mask_lane[__c]) rg_lane_cfg_q[__c] <= i_wb_dat[23:16];
				end
			end
		end
	end
	assign rg_lane_cfg = rg_lane_cfg_q[o_lane_sel];
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) c_rg_irq_sticky_q <= 1'h0;
		else if (wr_sel_10) c_rg_irq_sticky_q <= c_rg_irq_sticky_q & ~i_wb_dat[8:8];
	end
	assign c_rg_irq_sticky = c_rg_irq_sticky_q;
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) p_rg_pulse_cmd <= 1'h0;
		else p_rg_pulse_cmd <= wr_sel_10 ? i_wb_dat[16:16] : 1'h0;
	end
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) rg_key_0_q <= 32'h0;
		else if (wr_sel_20) rg_key_0_q <= i_wb_dat[31:0];
	end
	assign rg_key_0 = rg_key_0_q;
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) rg_key_1_q <= 32'h0;
		else if (wr_sel_30) rg_key_1_q <= i_wb_dat[31:0];
	end
	assign rg_key_1 = rg_key_1_q;
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) rg_key_2_q <= 32'h0;
		else if (wr_sel_40) rg_key_2_q <= i_wb_dat[31:0];
	end
	assign rg_key_2 = rg_key_2_q;
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) rg_word_q <= 32'h0;
		else if (wr_sel_44) rg_word_q <= i_wb_dat[31:0];
	end
	assign rg_word = rg_word_q;
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) rg_capture_q <= 16'h0;
		else if (wr_sel_48) rg_capture_q <= i_wb_dat[15:0];
		else if (rg_capture_strb) rg_capture_q <= rg_capture_hwdata;
	end
	assign rg_capture = rg_capture_q;
	assign ext_data_wdata = i_wb_dat[31:0];
	assign ext_data_wren  = wr_sel_4c;
	assign ext_data_rden  = rd_sel_4c;
	assign ext_data_rst   = ~i_rst_n;
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) rg_flag_q <= 1'h0;
		else if (wr_sel_50) rg_flag_q <= i_wb_dat[0:0];
	end
	assign rg_flag = rg_flag_q;
	always_comb begin
		rd_data = 32'h0;
		unique case (1'b1)
			rd_sel_0: begin
				rd_data = 32'h0;
				begin
					logic [0:0] __v;
					__v = 1'h0;
					for (int __c = 0; __c < 4; __c++) begin
						if (mask_lane[__c]) __v |= rg_enable_q[__c];
					end
					rd_data[0:0] = __v;
				end
				begin
					logic [2:0] __v;
					__v = 3'h0;
					for (int __c = 0; __c < 4; __c++) begin
						if (mask_lane[__c]) __v |= rg_mode_q[__c];
					end
					rd_data[10:8] = __v;
				end
				begin
					logic [7:0] __v;
					__v = 8'h0;
					for (int __c = 0; __c < 4; __c++) begin
						if (mask_lane[__c]) __v |= rg_lane_cfg_q[__c];
					end
					rd_data[23:16] = __v;
				end
			end
			rd_sel_10: begin
				rd_data = 32'h0;
				rd_data[0:0] = ro_busy;
				rd_data[8:8] = c_rg_irq_sticky_q;
				rd_data[16:16] = 1'h0;
			end
			rd_sel_20: begin
				rd_data = 32'h0;
				rd_data[31:0] = rg_key_0_q;
			end
			rd_sel_30: begin
				rd_data = 32'h0;
				rd_data[31:0] = rg_key_1_q;
			end
			rd_sel_40: begin
				rd_data = 32'h0;
				rd_data[31:0] = rg_key_2_q;
			end
			rd_sel_44: begin
				rd_data = 32'h0;
				rd_data[31:0] = rg_word_q;
			end
			rd_sel_48: begin
				rd_data = 32'h0;
				rd_data[15:0] = rg_capture_q;
			end
			rd_sel_4c: begin
				rd_data = 32'h0;
				rd_data[31:0] = ext_data;
			end
			rd_sel_50: begin
				rd_data = 32'h0;
				rd_data[0:0] = rg_flag_q;
			end
			default: rd_data = 32'h0;
		endcase
	end

	assign o_wb_ack = i_wb_cyc && i_wb_stb && hit && !(((wr_sel_4c || rd_sel_4c) && !ext_data_ready));
	assign o_wb_dat = rd_data;

endmodule
