// Generated by autowire plugin wishbone-regfile (table sub_module_b). Do not edit.
//
//------------------------------------------------------------------------------
//  Module: sub_module_b_regfile
//  Desc:   Sub-module B (nested slot)
//  Addr width: 16
//  Cells: 1
//  read_write_block: false
//------------------------------------------------------------------------------
//  Address map:
//    0x0000  ID — Identification
//------------------------------------------------------------------------------

module sub_module_b_regfile (
	// Clock
	input  logic        i_clk,
	// Active-low asynchronous reset
	input  logic        i_rst_n,
	// Wishbone classic slave (sub_module_b)
	// Wishbone CYC
	input  logic        sub_module_b_i_wb_cyc,
	// Wishbone STB
	input  logic        sub_module_b_i_wb_stb,
	// Wishbone WE (1=write, 0=read)
	input  logic        sub_module_b_i_wb_we,
	// Wishbone ADR (byte address; word decode uses [addr_width-1:2])
	input  logic [15:0] sub_module_b_i_wb_adr,
	// Wishbone write data
	input  logic [31:0] sub_module_b_i_wb_dat,
	// Wishbone byte select
	input  logic [3:0]  sub_module_b_i_wb_sel,
	// Wishbone ACK
	output logic        sub_module_b_o_wb_ack,
	// Wishbone read data
	output logic [31:0] sub_module_b_o_wb_dat
);

	//------------------------------------------------------------------------------
	//  1. Internal declarations
	//------------------------------------------------------------------------------

	logic        hit;
	logic        wr_fire;
	logic        rd_fire;
	logic        addr_hit_0;
	logic        wr_sel_0;
	logic        rd_sel_0;
	logic [31:0] rd_data;

	//------------------------------------------------------------------------------
	//  2. Address decode / hit / wr_sel / rd_sel
	//------------------------------------------------------------------------------

	// Addr: 0x0000  RegCell: ID — Identification
	//   [15:0]   RC  version — Chip / IP version (ReadConst)
	//   [31:16]  RC  magic   — Magic ID (ReadConst)
	assign addr_hit_0 = (sub_module_b_i_wb_adr[15:2] == 14'd0);

	assign hit = |{
		addr_hit_0
	};
	assign wr_fire = sub_module_b_i_wb_cyc && sub_module_b_i_wb_stb &&  sub_module_b_i_wb_we;
	assign rd_fire = sub_module_b_i_wb_cyc && sub_module_b_i_wb_stb && ~sub_module_b_i_wb_we;

	assign wr_sel_0 = wr_fire && addr_hit_0;
	assign rd_sel_0 = rd_fire && addr_hit_0;

	//------------------------------------------------------------------------------
	//  4. Field storage / sideband glue
	//------------------------------------------------------------------------------

	// Addr: 0x0000  RegCell: ID — Identification
	//   [15:0]   RC  version — Chip / IP version (ReadConst)
	//   [31:16]  RC  magic   — Magic ID (ReadConst)


	//------------------------------------------------------------------------------
	//  5. Read mux → sub_module_b_o_wb_dat / ACK
	//------------------------------------------------------------------------------

	always_comb begin
		rd_data = 32'h0;
		unique case (1'b1)
			// ID @ 0x0000
			rd_sel_0: begin
				// RC [15:0]  version — Chip / IP version (ReadConst)
				rd_data[15:0] = 16'h1;
				// RC [31:16] magic   — Magic ID (ReadConst)
				rd_data[31:16] = 16'ha55a;
			end
			default: rd_data = 32'h0;
		endcase
	end

	assign sub_module_b_o_wb_ack = sub_module_b_i_wb_cyc && sub_module_b_i_wb_stb && hit;
	assign sub_module_b_o_wb_dat = rd_data;

endmodule
