// Generated by autowire plugin wishbone-regfile (table sub_module_a). Do not edit.
//
//------------------------------------------------------------------------------
//  Module: sub_module_a_regfile
//  Desc:   Sub-module A — omit offset, auto layout
//  Addr width: 8
//  Cells: 9
//  read_write_block: true
//------------------------------------------------------------------------------
//  Address map:
//    0x00  CFG0       — Main config  shadow=lane
//    0x10  STATUS     — Status
//    0x20  ctrl_key_0 — 96-bit key; auto-split + auto offset
//    0x30  ctrl_key_1 — 96-bit key; auto-split + auto offset
//    0x40  ctrl_key_2 — 96-bit key; auto-split + auto offset
//    0x44  SCRATCH    — Scratch pad
//    0x48  HW_FEED    — Hardware feed
//    0x4c  EXT_FIFO   — External FIFO window
//    0x50  SOLO       — Independent cell
//------------------------------------------------------------------------------

module sub_module_a_regfile (
	// Clock
	input  logic        i_clk,
	// Active-low asynchronous reset
	input  logic        i_rst_n,
	// Wishbone classic slave (sub_module_a)
	// Wishbone CYC
	input  logic        sub_module_a_i_wb_cyc,
	// Wishbone STB
	input  logic        sub_module_a_i_wb_stb,
	// Wishbone WE (1=write, 0=read)
	input  logic        sub_module_a_i_wb_we,
	// Wishbone ADR (byte address; word decode uses [addr_width-1:2])
	input  logic [7:0]  sub_module_a_i_wb_adr,
	// Wishbone write data
	input  logic [31:0] sub_module_a_i_wb_dat,
	// Wishbone byte select
	input  logic [3:0]  sub_module_a_i_wb_sel,
	// Wishbone TGA (shadow / user tag)
	input  logic [1:0]  sub_module_a_i_wb_tga,
	// Wishbone ACK
	output logic        sub_module_a_o_wb_ack,
	// Wishbone read data
	output logic [31:0] sub_module_a_o_wb_dat,
	// Field / shadow sidebands
	// RW register out: enable — Soft enable
	output logic        rg_enable,
	// Shadow bank select: lane (4 copies, TGA 1:0)
	output logic [1:0]  o_lane_sel,
	// RW register out: mode — Operating mode
	output logic [2:0]  rg_mode,
	// RW register out: lane_cfg — Per-lane config (shadowed)
	output logic [7:0]  rg_lane_cfg,
	// RO status in: busy — Busy
	input  logic        ro_busy,
	// W1C write-1 clear sticky out: irq_sticky — Sticky IRQ; write 1 to clear
	output logic        c_rg_irq_sticky,
	// W1P write-1 pulse out: pulse_cmd — Write 1 → one-cycle pulse out
	output logic        p_rg_pulse_cmd,
	// RW register out: key_0 — 96-bit key; auto-split + auto offset
	output logic [31:0] rg_key_0,
	// RW register out: key_1 — 96-bit key; auto-split + auto offset
	output logic [31:0] rg_key_1,
	// RW register out: key_2 — 96-bit key; auto-split + auto offset
	output logic [31:0] rg_key_2,
	// RW register out: word — Scratch word
	output logic [31:0] rg_word,
	// RWW register out: capture — HW may update via capture_strb/capture_hwdata
	output logic [15:0] rg_capture,
	// RWW hardware write strobe: capture — HW may update via capture_strb/capture_hwdata
	input  logic        rg_capture_strb,
	// RWW hardware write data: capture — HW may update via capture_strb/capture_hwdata
	input  logic [15:0] rg_capture_hwdata,
	// RWE external window read data in: ext_data — External FIFO data
	input  logic [31:0] ext_data,
	// RWE external window write data: ext_data — External FIFO data
	output logic [31:0] ext_data_wdata,
	// RWE external window write enable: ext_data — External FIFO data
	output logic        ext_data_wren,
	// RWE external window read enable: ext_data — External FIFO data
	output logic        ext_data_rden,
	// RWE external window reset: ext_data — External FIFO data
	output logic        ext_data_rst,
	// RWE external window ready (may stall ACK): ext_data — External FIFO data
	input  logic        ext_data_ready,
	// RW register out: flag — Solo flag
	output logic        rg_flag
);

	//------------------------------------------------------------------------------
	//  1. Internal declarations
	//------------------------------------------------------------------------------

	logic        hit;
	logic        wr_fire;
	logic        rd_fire;
	logic        addr_hit_0;
	logic        wr_sel_0;
	logic        rd_sel_0;
	logic        addr_hit_10;
	logic        wr_sel_10;
	logic        rd_sel_10;
	logic        addr_hit_20;
	logic        wr_sel_20;
	logic        rd_sel_20;
	logic        addr_hit_30;
	logic        wr_sel_30;
	logic        rd_sel_30;
	logic        addr_hit_40;
	logic        wr_sel_40;
	logic        rd_sel_40;
	logic        addr_hit_44;
	logic        wr_sel_44;
	logic        rd_sel_44;
	logic        addr_hit_48;
	logic        wr_sel_48;
	logic        rd_sel_48;
	logic        addr_hit_4c;
	logic        wr_sel_4c;
	logic        rd_sel_4c;
	logic        addr_hit_50;
	logic        wr_sel_50;
	logic        rd_sel_50;
	logic [1:0]  raw_lane;
	logic [3:0]  mask_lane;
	logic        rg_enable_q [4];
	logic [2:0]  rg_mode_q [4];
	logic [7:0]  rg_lane_cfg_q [4];
	logic        c_rg_irq_sticky_q;
	logic [31:0] rg_key_0_q;
	logic [31:0] rg_key_1_q;
	logic [31:0] rg_key_2_q;
	logic [31:0] rg_word_q;
	logic [15:0] rg_capture_q;
	logic        rg_flag_q;
	logic [31:0] rd_data;
	logic        rwe_stall_ext_data;

	//------------------------------------------------------------------------------
	//  2. Address decode / hit / wr_sel / rd_sel
	//------------------------------------------------------------------------------

	// Addr: 0x00  RegCell: CFG0       — Main config
	//   shadow=lane
	//   [0]      RW   enable     — Soft enable
	//   [10:8]   RW   mode       — Operating mode
	//   [23:16]  RW   lane_cfg   — Per-lane config (shadowed)
	assign addr_hit_0 = (sub_module_a_i_wb_adr[7:2] == 6'd0);
	// Addr: 0x10  RegCell: STATUS     — Status
	//   [0]      RO   busy       — Busy
	//   [8]      W1C  irq_sticky — Sticky IRQ; write 1 to clear
	//   [16]     W1P  pulse_cmd  — Write 1 → one-cycle pulse out
	assign addr_hit_10 = (sub_module_a_i_wb_adr[7:2] == 6'd4);
	// Addr: 0x20  RegCell: ctrl_key_0 — 96-bit key; auto-split + auto offset
	//   [31:0]   RW   key_0      — 96-bit key; auto-split + auto offset (slice0 of key)
	assign addr_hit_20 = (sub_module_a_i_wb_adr[7:2] == 6'd8);
	// Addr: 0x30  RegCell: ctrl_key_1 — 96-bit key; auto-split + auto offset
	//   [31:0]   RW   key_1      — 96-bit key; auto-split + auto offset (slice1 of key)
	assign addr_hit_30 = (sub_module_a_i_wb_adr[7:2] == 6'd12);
	// Addr: 0x40  RegCell: ctrl_key_2 — 96-bit key; auto-split + auto offset
	//   [31:0]   RW   key_2      — 96-bit key; auto-split + auto offset (slice2 of key)
	assign addr_hit_40 = (sub_module_a_i_wb_adr[7:2] == 6'd16);
	// Addr: 0x44  RegCell: SCRATCH    — Scratch pad
	//   [31:0]   RW   word       — Scratch word
	assign addr_hit_44 = (sub_module_a_i_wb_adr[7:2] == 6'd17);
	// Addr: 0x48  RegCell: HW_FEED    — Hardware feed
	//   [15:0]   RWW  capture    — HW may update via capture_strb/capture_hwdata
	assign addr_hit_48 = (sub_module_a_i_wb_adr[7:2] == 6'd18);
	// Addr: 0x4c  RegCell: EXT_FIFO   — External FIFO window
	//   [31:0]   RWE  ext_data   — External FIFO data
	assign addr_hit_4c = (sub_module_a_i_wb_adr[7:2] == 6'd19);
	// Addr: 0x50  RegCell: SOLO       — Independent cell
	//   [0]      RW   flag       — Solo flag
	assign addr_hit_50 = (sub_module_a_i_wb_adr[7:2] == 6'd20);

	assign hit = |{
		addr_hit_0,
		addr_hit_10,
		addr_hit_20,
		addr_hit_30,
		addr_hit_40,
		addr_hit_44,
		addr_hit_48,
		addr_hit_4c,
		addr_hit_50
	};
	assign wr_fire = sub_module_a_i_wb_cyc && sub_module_a_i_wb_stb &&  sub_module_a_i_wb_we;
	assign rd_fire = sub_module_a_i_wb_cyc && sub_module_a_i_wb_stb && ~sub_module_a_i_wb_we;

	assign wr_sel_0 = wr_fire && hit && addr_hit_0;
	assign rd_sel_0 = rd_fire && hit && addr_hit_0;
	assign wr_sel_10 = wr_fire && hit && addr_hit_10;
	assign rd_sel_10 = rd_fire && hit && addr_hit_10;
	assign wr_sel_20 = wr_fire && hit && addr_hit_20;
	assign rd_sel_20 = rd_fire && hit && addr_hit_20;
	assign wr_sel_30 = wr_fire && hit && addr_hit_30;
	assign rd_sel_30 = rd_fire && hit && addr_hit_30;
	assign wr_sel_40 = wr_fire && hit && addr_hit_40;
	assign rd_sel_40 = rd_fire && hit && addr_hit_40;
	assign wr_sel_44 = wr_fire && hit && addr_hit_44;
	assign rd_sel_44 = rd_fire && hit && addr_hit_44;
	assign wr_sel_48 = wr_fire && hit && addr_hit_48;
	assign rd_sel_48 = rd_fire && hit && addr_hit_48;
	assign wr_sel_4c = wr_fire && hit && addr_hit_4c;
	assign rd_sel_4c = rd_fire && hit && addr_hit_4c;
	assign wr_sel_50 = wr_fire && hit && addr_hit_50;
	assign rd_sel_50 = rd_fire && hit && addr_hit_50;

	//------------------------------------------------------------------------------
	//  3. Shadow tag decode (TGA → one-hot mask / bin sel)
	//------------------------------------------------------------------------------

	assign raw_lane = sub_module_a_i_wb_tga[1:0];
	always_comb begin
		mask_lane = 4'h0;
		unique case (raw_lane)
			2'd3: mask_lane = 4'hf;
		default: mask_lane = 4'h0; // miss → nop
		endcase
	end
	// one-hot mask → bin index (first set bit); miss keeps 0
	always_comb begin
		o_lane_sel = 2'd0;
		for (int __i = 0; __i < 4; __i++) begin
			if (mask_lane[__i]) o_lane_sel = 2'(__i);
		end
	end


	//------------------------------------------------------------------------------
	//  4. Field storage / sideband glue
	//------------------------------------------------------------------------------

	// Addr: 0x00  RegCell: CFG0       — Main config
	//   shadow=lane
	//   [0]      RW   enable     — Soft enable
	//   [10:8]   RW   mode       — Operating mode
	//   [23:16]  RW   lane_cfg   — Per-lane config (shadowed)
	// RW  [0]     enable     — Soft enable
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) begin
			rg_enable_q[0] <= 1'h0;
			rg_enable_q[1] <= 1'h0;
			rg_enable_q[2] <= 1'h0;
			rg_enable_q[3] <= 1'h0;
		end else begin
			if (wr_sel_0) begin
				for (int __c = 0; __c < 4; __c++) begin
					if (mask_lane[__c]) rg_enable_q[__c] <= sub_module_a_i_wb_dat[0:0];
				end
			end
		end
	end
	assign rg_enable = rg_enable_q[o_lane_sel];
	// RW  [10:8]  mode       — Operating mode
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) begin
			rg_mode_q[0] <= 3'h0;
			rg_mode_q[1] <= 3'h0;
			rg_mode_q[2] <= 3'h0;
			rg_mode_q[3] <= 3'h0;
		end else begin
			if (wr_sel_0) begin
				for (int __c = 0; __c < 4; __c++) begin
					if (mask_lane[__c]) rg_mode_q[__c] <= sub_module_a_i_wb_dat[10:8];
				end
			end
		end
	end
	assign rg_mode = rg_mode_q[o_lane_sel];
	// RW  [23:16] lane_cfg   — Per-lane config (shadowed)
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) begin
			rg_lane_cfg_q[0] <= 8'h10;
			rg_lane_cfg_q[1] <= 8'h20;
			rg_lane_cfg_q[2] <= 8'h30;
			rg_lane_cfg_q[3] <= 8'h40;
		end else begin
			if (wr_sel_0) begin
				for (int __c = 0; __c < 4; __c++) begin
					if (mask_lane[__c]) rg_lane_cfg_q[__c] <= sub_module_a_i_wb_dat[23:16];
				end
			end
		end
	end
	assign rg_lane_cfg = rg_lane_cfg_q[o_lane_sel];

	// Addr: 0x10  RegCell: STATUS     — Status
	//   [0]      RO   busy       — Busy
	//   [8]      W1C  irq_sticky — Sticky IRQ; write 1 to clear
	//   [16]     W1P  pulse_cmd  — Write 1 → one-cycle pulse out
	// W1C [8]     irq_sticky — Sticky IRQ; write 1 to clear
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) c_rg_irq_sticky_q <= 1'h0;
		else if (wr_sel_10) c_rg_irq_sticky_q <= c_rg_irq_sticky_q & ~sub_module_a_i_wb_dat[8:8];
	end
	assign c_rg_irq_sticky = c_rg_irq_sticky_q;
	// W1P [16]    pulse_cmd  — Write 1 → one-cycle pulse out
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) p_rg_pulse_cmd <= 1'h0;
		else p_rg_pulse_cmd <= wr_sel_10 ? sub_module_a_i_wb_dat[16:16] : 1'h0;
	end

	// Addr: 0x20  RegCell: ctrl_key_0 — 96-bit key; auto-split + auto offset
	//   [31:0]   RW   key_0      — 96-bit key; auto-split + auto offset (slice0 of key)
	// RW  [31:0]  key_0      — 96-bit key; auto-split + auto offset
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) rg_key_0_q <= 32'h0;
		else if (wr_sel_20) rg_key_0_q <= sub_module_a_i_wb_dat[31:0];
	end
	assign rg_key_0 = rg_key_0_q;

	// Addr: 0x30  RegCell: ctrl_key_1 — 96-bit key; auto-split + auto offset
	//   [31:0]   RW   key_1      — 96-bit key; auto-split + auto offset (slice1 of key)
	// RW  [31:0]  key_1      — 96-bit key; auto-split + auto offset
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) rg_key_1_q <= 32'h0;
		else if (wr_sel_30) rg_key_1_q <= sub_module_a_i_wb_dat[31:0];
	end
	assign rg_key_1 = rg_key_1_q;

	// Addr: 0x40  RegCell: ctrl_key_2 — 96-bit key; auto-split + auto offset
	//   [31:0]   RW   key_2      — 96-bit key; auto-split + auto offset (slice2 of key)
	// RW  [31:0]  key_2      — 96-bit key; auto-split + auto offset
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) rg_key_2_q <= 32'h0;
		else if (wr_sel_40) rg_key_2_q <= sub_module_a_i_wb_dat[31:0];
	end
	assign rg_key_2 = rg_key_2_q;

	// Addr: 0x44  RegCell: SCRATCH    — Scratch pad
	//   [31:0]   RW   word       — Scratch word
	// RW  [31:0]  word       — Scratch word
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) rg_word_q <= 32'h0;
		else if (wr_sel_44) rg_word_q <= sub_module_a_i_wb_dat[31:0];
	end
	assign rg_word = rg_word_q;

	// Addr: 0x48  RegCell: HW_FEED    — Hardware feed
	//   [15:0]   RWW  capture    — HW may update via capture_strb/capture_hwdata
	// RWW [15:0]  capture    — HW may update via capture_strb/capture_hwdata
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) rg_capture_q <= 16'h0;
		else if (wr_sel_48) rg_capture_q <= sub_module_a_i_wb_dat[15:0];
		else if (rg_capture_strb) rg_capture_q <= rg_capture_hwdata;
	end
	assign rg_capture = rg_capture_q;

	// Addr: 0x4c  RegCell: EXT_FIFO   — External FIFO window
	//   [31:0]   RWE  ext_data   — External FIFO data
	// RWE [31:0]  ext_data   — External FIFO data
	assign ext_data_wdata = sub_module_a_i_wb_dat[31:0];
	assign ext_data_wren  = wr_sel_4c;
	assign ext_data_rden  = rd_sel_4c;
	assign ext_data_rst   = ~i_rst_n;
	// Stall ACK when this RWE window is selected and not ready
	assign rwe_stall_ext_data = (wr_sel_4c || rd_sel_4c) && !ext_data_ready;

	// Addr: 0x50  RegCell: SOLO       — Independent cell
	//   [0]      RW   flag       — Solo flag
	// RW  [0]     flag       — Solo flag
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) rg_flag_q <= 1'h0;
		else if (wr_sel_50) rg_flag_q <= sub_module_a_i_wb_dat[0:0];
	end
	assign rg_flag = rg_flag_q;


	//------------------------------------------------------------------------------
	//  5. Read mux → sub_module_a_o_wb_dat / ACK
	//------------------------------------------------------------------------------

	always_comb begin
		rd_data = 32'h0;
		unique case (1'b1)
			// CFG0 @ 0x00
			rd_sel_0: begin
				rd_data = 32'h0;
				// RW  [0]     enable     — Soft enable
				begin
					logic [0:0] __v;
					__v = 1'h0;
					for (int __c = 0; __c < 4; __c++) begin
						if (mask_lane[__c]) __v |= rg_enable_q[__c];
					end
					rd_data[0:0] = __v;
				end
				// RW  [10:8]  mode       — Operating mode
				begin
					logic [2:0] __v;
					__v = 3'h0;
					for (int __c = 0; __c < 4; __c++) begin
						if (mask_lane[__c]) __v |= rg_mode_q[__c];
					end
					rd_data[10:8] = __v;
				end
				// RW  [23:16] lane_cfg   — Per-lane config (shadowed)
				begin
					logic [7:0] __v;
					__v = 8'h0;
					for (int __c = 0; __c < 4; __c++) begin
						if (mask_lane[__c]) __v |= rg_lane_cfg_q[__c];
					end
					rd_data[23:16] = __v;
				end
			end
			// STATUS @ 0x10
			rd_sel_10: begin
				rd_data = 32'h0;
				// RO  [0]     busy       — Busy
				rd_data[0:0] = ro_busy;
				// W1C [8]     irq_sticky — Sticky IRQ; write 1 to clear
				rd_data[8:8] = c_rg_irq_sticky_q;
				// W1P [16]    pulse_cmd  — Write 1 → one-cycle pulse out
				rd_data[16:16] = 1'h0;
			end
			// ctrl_key_0 @ 0x20
			rd_sel_20: begin
				rd_data = 32'h0;
				// RW  [31:0]  key_0      — 96-bit key; auto-split + auto offset
				rd_data[31:0] = rg_key_0_q;
			end
			// ctrl_key_1 @ 0x30
			rd_sel_30: begin
				rd_data = 32'h0;
				// RW  [31:0]  key_1      — 96-bit key; auto-split + auto offset
				rd_data[31:0] = rg_key_1_q;
			end
			// ctrl_key_2 @ 0x40
			rd_sel_40: begin
				rd_data = 32'h0;
				// RW  [31:0]  key_2      — 96-bit key; auto-split + auto offset
				rd_data[31:0] = rg_key_2_q;
			end
			// SCRATCH @ 0x44
			rd_sel_44: begin
				rd_data = 32'h0;
				// RW  [31:0]  word       — Scratch word
				rd_data[31:0] = rg_word_q;
			end
			// HW_FEED @ 0x48
			rd_sel_48: begin
				rd_data = 32'h0;
				// RWW [15:0]  capture    — HW may update via capture_strb/capture_hwdata
				rd_data[15:0] = rg_capture_q;
			end
			// EXT_FIFO @ 0x4c
			rd_sel_4c: begin
				rd_data = 32'h0;
				// RWE [31:0]  ext_data   — External FIFO data
				rd_data[31:0] = ext_data;
			end
			// SOLO @ 0x50
			rd_sel_50: begin
				rd_data = 32'h0;
				// RW  [0]     flag       — Solo flag
				rd_data[0:0] = rg_flag_q;
			end
			default: rd_data = 32'h0;
		endcase
	end

	assign sub_module_a_o_wb_ack = sub_module_a_i_wb_cyc && sub_module_a_i_wb_stb && hit && !rwe_stall_ext_data;
	assign sub_module_a_o_wb_dat = rd_data;

endmodule
