// Generated by autowire plugin wishbone-regfile (table sub_module_b). Do not edit.
// Sub-module B (nested slot)
module sub_module_b_regfile (
	input  logic        i_clk,
	input  logic        i_rst_n,
	input  logic        i_wb_cyc,
	input  logic        i_wb_stb,
	input  logic        i_wb_we,
	input  logic [15:0] i_wb_adr,
	input  logic [31:0] i_wb_dat,
	input  logic [3:0]  i_wb_sel,
	output logic        o_wb_ack,
	output logic [31:0] o_wb_dat
);

	logic        hit;
	logic        wr_fire;
	logic        rd_fire;
	logic        addr_hit_0;
	logic        wr_sel_0;
	logic        rd_sel_0;
	logic [31:0] rd_data;

	// Addr: 0x0 RegCell: ID — Identification
	assign addr_hit_0 = (i_wb_adr[15:2] == 14'd0);

	assign hit = |{
		addr_hit_0
	};
	assign wr_fire = i_wb_cyc && i_wb_stb &&  i_wb_we;
	assign rd_fire = i_wb_cyc && i_wb_stb && ~i_wb_we;

	assign wr_sel_0 = wr_fire && hit && addr_hit_0;
	assign rd_sel_0 = rd_fire && hit && addr_hit_0;

	always_comb begin
		rd_data = 32'h0;
		unique case (1'b1)
			rd_sel_0: begin
				rd_data = 32'h0;
				rd_data[15:0] = 16'h1;
				rd_data[31:16] = 16'ha55a;
			end
			default: rd_data = 32'h0;
		endcase
	end

	assign o_wb_ack = i_wb_cyc && i_wb_stb && hit;
	assign o_wb_dat = rd_data;

endmodule
