// Generated by autowire plugin wishbone (table center). Do not edit.
// uvm_reg: field layout only. Address map and shadow tag are packed with the bus.

`ifndef RAL_CENTER_SV
`define RAL_CENTER_SV

import uvm_pkg::*;
`include "uvm_macros.svh"

// Cell ID — Fabric identity
class ral_reg_center_ID extends uvm_reg;
	     uvm_reg_field magic  ; // bit [15:0]
	     uvm_reg_field version; // bit [31:16]

	function new(string name = "ral_reg_center_ID");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.magic = uvm_reg_field::type_id::create("magic",, get_full_name());
		this.magic.configure(this, 16, 0, "RO", 0, 16'hc0de, 1, 0, 0);
		this.version = uvm_reg_field::type_id::create("version",, get_full_name());
		this.version.configure(this, 16, 16, "RO", 0, 16'h1, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_center_ID)
endclass : ral_reg_center_ID

// Cell CH_EN — Per-channel enable
class ral_reg_center_CH_EN extends uvm_reg;
	rand uvm_reg_field enable     ; // bit [15:0]
	     uvm_reg_field reserved_16; // bit [31:16]

	function new(string name = "ral_reg_center_CH_EN");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.enable = uvm_reg_field::type_id::create("enable",, get_full_name());
		this.enable.configure(this, 16, 0, "RW", 0, 16'hffff, 1, 1, 0);
		this.reserved_16 = uvm_reg_field::type_id::create("reserved_16",, get_full_name());
		this.reserved_16.configure(this, 16, 16, "RO", 0, 16'h0, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_center_CH_EN)
endclass : ral_reg_center_CH_EN

// Cell STATUS — Fabric status
class ral_reg_center_STATUS extends uvm_reg;
	     uvm_reg_field all_cal_done; // bit [0]
	     uvm_reg_field reserved_1  ; // bit [7:1]
	     uvm_reg_field err_ch      ; // bit [11:8]
	     uvm_reg_field reserved_12 ; // bit [31:12]

	function new(string name = "ral_reg_center_STATUS");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.all_cal_done = uvm_reg_field::type_id::create("all_cal_done",, get_full_name());
		this.all_cal_done.configure(this, 1, 0, "RO", 0, 1'h0, 1, 0, 0);
		this.reserved_1 = uvm_reg_field::type_id::create("reserved_1",, get_full_name());
		this.reserved_1.configure(this, 7, 1, "RO", 0, 7'h0, 1, 0, 0);
		this.err_ch = uvm_reg_field::type_id::create("err_ch",, get_full_name());
		this.err_ch.configure(this, 4, 8, "RO", 0, 4'h0, 1, 0, 0);
		this.reserved_12 = uvm_reg_field::type_id::create("reserved_12",, get_full_name());
		this.reserved_12.configure(this, 20, 12, "RO", 0, 20'h0, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_center_STATUS)
endclass : ral_reg_center_STATUS

// Leaf block — center: HBM center CSR (fabric-global control)
class ral_block_center extends uvm_reg_block;
	rand ral_reg_center_ID ID;
	rand ral_reg_center_CH_EN CH_EN;
	rand ral_reg_center_STATUS STATUS;

	function new(string name = "ral_block_center");
		super.new(name, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		default_map = create_map("default_map", 0, 4, UVM_LITTLE_ENDIAN);
		this.ID = ral_reg_center_ID::type_id::create("ID",, get_full_name());
		this.ID.configure(this);
		this.ID.build();
		default_map.add_reg(this.ID, 32'h00000000, "RO");
		this.CH_EN = ral_reg_center_CH_EN::type_id::create("CH_EN",, get_full_name());
		this.CH_EN.configure(this);
		this.CH_EN.build();
		default_map.add_reg(this.CH_EN, 32'h00000004, "RW");
		this.STATUS = ral_reg_center_STATUS::type_id::create("STATUS",, get_full_name());
		this.STATUS.configure(this);
		this.STATUS.build();
		default_map.add_reg(this.STATUS, 32'h00000008, "RO");
	endfunction: build

	`uvm_object_utils(ral_block_center)
endclass : ral_block_center

`endif // RAL_CENTER_SV
