// Generated by autowire plugin wishbone (table dword). Do not edit.
// uvm_reg: field layout only. Address map and shadow tag are packed with the bus.

`ifndef RAL_DWORD_SV
`define RAL_DWORD_SV

import uvm_pkg::*;
`include "uvm_macros.svh"

// Cell ID — Lane identity
class ral_reg_dword_ID extends uvm_reg;
	     uvm_reg_field magic  ; // bit [15:0]
	     uvm_reg_field version; // bit [31:16]

	function new(string name = "ral_reg_dword_ID");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.magic = uvm_reg_field::type_id::create("magic",, get_full_name());
		this.magic.configure(this, 16, 0, "RO", 0, 16'hd010, 1, 0, 0);
		this.version = uvm_reg_field::type_id::create("version",, get_full_name());
		this.version.configure(this, 16, 16, "RO", 0, 16'h1, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_dword_ID)
endclass : ral_reg_dword_ID

// Cell STATUS — Lane status
class ral_reg_dword_STATUS extends uvm_reg;
	     uvm_reg_field train_done ; // bit [0]
	     uvm_reg_field reserved_1 ; // bit [7:1]
	     uvm_reg_field eye_width  ; // bit [15:8]
	     uvm_reg_field reserved_16; // bit [31:16]

	function new(string name = "ral_reg_dword_STATUS");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.train_done = uvm_reg_field::type_id::create("train_done",, get_full_name());
		this.train_done.configure(this, 1, 0, "RO", 0, 1'h0, 1, 0, 0);
		this.reserved_1 = uvm_reg_field::type_id::create("reserved_1",, get_full_name());
		this.reserved_1.configure(this, 7, 1, "RO", 0, 7'h0, 1, 0, 0);
		this.eye_width = uvm_reg_field::type_id::create("eye_width",, get_full_name());
		this.eye_width.configure(this, 8, 8, "RO", 0, 8'h0, 1, 0, 0);
		this.reserved_16 = uvm_reg_field::type_id::create("reserved_16",, get_full_name());
		this.reserved_16.configure(this, 16, 16, "RO", 0, 16'h0, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_dword_STATUS)
endclass : ral_reg_dword_STATUS

// Cell TRAIN — Per-lane train pass (active low)
class ral_reg_dword_TRAIN extends uvm_reg;
	     uvm_reg_field train_pass_n; // bit [0]
	     uvm_reg_field reserved_1  ; // bit [31:1]

	function new(string name = "ral_reg_dword_TRAIN");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.train_pass_n = uvm_reg_field::type_id::create("train_pass_n",, get_full_name());
		this.train_pass_n.configure(this, 1, 0, "RO", 0, 1'h0, 1, 0, 0);
		this.reserved_1 = uvm_reg_field::type_id::create("reserved_1",, get_full_name());
		this.reserved_1.configure(this, 31, 1, "RO", 0, 31'h0, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_dword_TRAIN)
endclass : ral_reg_dword_TRAIN

// Cell VREF — Per-pstate receiver reference
// shadow: pstate, 4 copies (bank select is a bus TGA concern)
class ral_reg_dword_VREF extends uvm_reg;
	rand uvm_reg_field level     ; // bit [6:0]
	     uvm_reg_field reserved_7; // bit [31:7]

	function new(string name = "ral_reg_dword_VREF");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.level = uvm_reg_field::type_id::create("level",, get_full_name());
		this.level.configure(this, 7, 0, "RW", 0, 7'h30, 1, 1, 0);
		this.reserved_7 = uvm_reg_field::type_id::create("reserved_7",, get_full_name());
		this.reserved_7.configure(this, 25, 7, "RO", 0, 25'h0, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_dword_VREF)
endclass : ral_reg_dword_VREF

// Cell EQ — Per-pstate equalisation
// shadow: pstate, 4 copies (bank select is a bus TGA concern)
class ral_reg_dword_EQ extends uvm_reg;
	rand uvm_reg_field tap0       ; // bit [4:0]
	     uvm_reg_field reserved_5 ; // bit [7:5]
	rand uvm_reg_field tap1       ; // bit [12:8]
	     uvm_reg_field reserved_13; // bit [31:13]

	function new(string name = "ral_reg_dword_EQ");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.tap0 = uvm_reg_field::type_id::create("tap0",, get_full_name());
		this.tap0.configure(this, 5, 0, "RW", 0, 5'h2, 1, 1, 0);
		this.reserved_5 = uvm_reg_field::type_id::create("reserved_5",, get_full_name());
		this.reserved_5.configure(this, 3, 5, "RO", 0, 3'h0, 1, 0, 0);
		this.tap1 = uvm_reg_field::type_id::create("tap1",, get_full_name());
		this.tap1.configure(this, 5, 8, "RW", 0, 5'h1, 1, 1, 0);
		this.reserved_13 = uvm_reg_field::type_id::create("reserved_13",, get_full_name());
		this.reserved_13.configure(this, 19, 13, "RO", 0, 19'h0, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_dword_EQ)
endclass : ral_reg_dword_EQ

// Leaf block — dword: HBM dword CSR (data lane)
class ral_block_dword extends uvm_reg_block;
	rand ral_reg_dword_ID ID;
	rand ral_reg_dword_STATUS STATUS;
	rand ral_reg_dword_TRAIN TRAIN;
	rand ral_reg_dword_VREF VREF;
	rand ral_reg_dword_EQ EQ;

	function new(string name = "ral_block_dword");
		super.new(name, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		default_map = create_map("default_map", 0, 4, UVM_LITTLE_ENDIAN);
		this.ID = ral_reg_dword_ID::type_id::create("ID",, get_full_name());
		this.ID.configure(this);
		this.ID.build();
		default_map.add_reg(this.ID, 32'h00000000, "RO");
		this.STATUS = ral_reg_dword_STATUS::type_id::create("STATUS",, get_full_name());
		this.STATUS.configure(this);
		this.STATUS.build();
		default_map.add_reg(this.STATUS, 32'h00000004, "RO");
		this.TRAIN = ral_reg_dword_TRAIN::type_id::create("TRAIN",, get_full_name());
		this.TRAIN.configure(this);
		this.TRAIN.build();
		default_map.add_reg(this.TRAIN, 32'h00000010, "RO");
		// VREF: shadow: pstate, 4 copies (bank select is a bus TGA concern)
		this.VREF = ral_reg_dword_VREF::type_id::create("VREF",, get_full_name());
		this.VREF.configure(this);
		this.VREF.build();
		default_map.add_reg(this.VREF, 32'h00000008, "RW");
		// EQ: shadow: pstate, 4 copies (bank select is a bus TGA concern)
		this.EQ = ral_reg_dword_EQ::type_id::create("EQ",, get_full_name());
		this.EQ.configure(this);
		this.EQ.build();
		default_map.add_reg(this.EQ, 32'h0000000c, "RW");
	endfunction: build

	`uvm_object_utils(ral_block_dword)
endclass : ral_block_dword

`endif // RAL_DWORD_SV
