// Generated by autowire dump (unit "sd_sha_ch"). Do not edit: SoT is the connect HTML.
module sd_sha_ch (
	input  logic        rst_n,
	input  logic        rb_grant_en,
	input  logic        clk,
	input  logic [31:0] i_wb_adr,
	input  logic [31:0] i_wb_dat,
	input  logic [3:0]  i_wb_sel,
	input  logic        i_wb_cyc,
	input  logic        i_wb_stb,
	input  logic        i_wb_we,
	output logic [31:0] o_wb_dat,
	output logic        o_wb_ack,
	input  wire         rst,
	output wire         o_cs_n,
	output wire         o_sck,
	output wire         o_mosi,
	input  wire         i_miso,
	input  wire         i_cd,
	output wire         o_sd_irq,
	input  wire         rst_ni,
	output wire         o_dma_irq,
	output wire         o_sha_irq
);
	logic [31:0] eng_o_wb_adr;
	logic [31:0] eng_o_wb_dat;
	logic [3:0]  eng_o_wb_sel;
	logic        eng_o_wb_cyc;
	logic        eng_o_wb_stb;
	logic        eng_o_wb_we;
	logic [31:0] sd_o_wb_dat;
	logic        sd_o_wb_ack;
	logic [31:0] dma_o_wb_dat;
	logic        dma_o_wb_ack;
	logic        ro_busy;
	logic        ro_done;
	logic [31:0] ro_hash0;
	logic [31:0] ro_hash1;
	logic [31:0] ro_hash2;
	logic [31:0] ro_hash3;
	logic [31:0] ro_hash4;
	logic [31:0] ro_hash5;
	logic [31:0] ro_hash6;
	logic [31:0] ro_hash7;
	logic [31:0] eng_i_wb_dat;
	logic        eng_i_wb_ack;
	logic [31:0] sd_i_wb_adr;
	logic [31:0] sd_i_wb_dat;
	logic [3:0]  sd_i_wb_sel;
	logic        sd_i_wb_cyc;
	logic        sd_i_wb_stb;
	logic        sd_i_wb_we;
	logic [31:0] dma_i_wb_adr;
	logic [31:0] dma_i_wb_dat;
	logic [3:0]  dma_i_wb_sel;
	logic        dma_i_wb_cyc;
	logic        dma_i_wb_stb;
	logic        dma_i_wb_we;
	logic        rg_soft_reset;
	logic        p_rg_done_clear;
	wire  [31:0] axis_tdata;
	wire         axis_tvalid;
	wire         axis_tready;
	wire         axis_tlast;

	sd_sha_system u_ic (
		.clk            (clk             ),
		.rst_n          (rst_n           ),
		.rb_grant_en    (rb_grant_en     ),
		.eng_o_wb_adr   (eng_o_wb_adr    ),
		.eng_o_wb_dat   (eng_o_wb_dat    ),
		.eng_o_wb_sel   (eng_o_wb_sel    ),
		.eng_o_wb_cyc   (eng_o_wb_cyc    ),
		.eng_o_wb_stb   (eng_o_wb_stb    ),
		.eng_o_wb_we    (eng_o_wb_we     ),
		.sd_o_wb_dat    (sd_o_wb_dat     ),
		.sd_o_wb_ack    (sd_o_wb_ack     ),
		.dma_o_wb_dat   (dma_o_wb_dat    ),
		.dma_o_wb_ack   (dma_o_wb_ack    ),
		.i_wb_adr       (i_wb_adr        ),
		.i_wb_dat       (i_wb_dat        ),
		.i_wb_sel       (i_wb_sel        ),
		.i_wb_cyc       (i_wb_cyc        ),
		.i_wb_stb       (i_wb_stb        ),
		.i_wb_we        (i_wb_we         ),
		.ro_busy        (ro_busy         ),
		.ro_done        (ro_done         ),
		.ro_hash0       (ro_hash0        ),
		.ro_hash1       (ro_hash1        ),
		.ro_hash2       (ro_hash2        ),
		.ro_hash3       (ro_hash3        ),
		.ro_hash4       (ro_hash4        ),
		.ro_hash5       (ro_hash5        ),
		.ro_hash6       (ro_hash6        ),
		.ro_hash7       (ro_hash7        ),
		.eng_i_wb_dat   (eng_i_wb_dat    ),
		.eng_i_wb_ack   (eng_i_wb_ack    ),
		.sd_i_wb_adr    (sd_i_wb_adr     ),
		.sd_i_wb_dat    (sd_i_wb_dat     ),
		.sd_i_wb_sel    (sd_i_wb_sel     ),
		.sd_i_wb_cyc    (sd_i_wb_cyc     ),
		.sd_i_wb_stb    (sd_i_wb_stb     ),
		.sd_i_wb_we     (sd_i_wb_we      ),
		.dma_i_wb_adr   (dma_i_wb_adr    ),
		.dma_i_wb_dat   (dma_i_wb_dat    ),
		.dma_i_wb_sel   (dma_i_wb_sel    ),
		.dma_i_wb_cyc   (dma_i_wb_cyc    ),
		.dma_i_wb_stb   (dma_i_wb_stb    ),
		.dma_i_wb_we    (dma_i_wb_we     ),
		.o_wb_dat       (o_wb_dat        ),
		.o_wb_ack       (o_wb_ack        ),
		.rg_soft_reset  (rg_soft_reset   ),
		.p_rg_done_clear(p_rg_done_clear )
	);
	sdspi u_sd (
		.i_clk          (clk             ),
		.i_sd_reset     (rst             ),
		.i_wb_cyc       (sd_i_wb_cyc     ),
		.i_wb_stb       (sd_i_wb_stb     ),
		.i_wb_we        (sd_i_wb_we      ),
		.i_wb_addr      (sd_i_wb_adr[3:2]),
		.i_wb_data      (sd_i_wb_dat     ),
		.i_wb_sel       (sd_i_wb_sel     ),
		.i_miso         (i_miso          ),
		.i_card_detect  (i_cd            ),
		.i_bus_grant    (1'b1            ),
		.o_wb_stall     (                ),
		.o_wb_ack       (sd_o_wb_ack     ),
		.o_wb_data      (sd_o_wb_dat     ),
		.o_cs_n         (o_cs_n          ),
		.o_sck          (o_sck           ),
		.o_mosi         (o_mosi          ),
		.o_int          (o_sd_irq        ),
		.o_debug        (                )
	);
	sd_rd_dma u_eng (
		.clk            (clk             ),
		.rst_n          (rst_ni          ),
		.i_wb_cyc       (dma_i_wb_cyc    ),
		.i_wb_stb       (dma_i_wb_stb    ),
		.i_wb_we        (dma_i_wb_we     ),
		.i_wb_adr       (dma_i_wb_adr    ),
		.i_wb_dat       (dma_i_wb_dat    ),
		.i_wb_sel       (dma_i_wb_sel    ),
		.wbm_ack_i      (eng_i_wb_ack    ),
		.wbm_dat_i      (eng_i_wb_dat    ),
		.m_axis_tready  (axis_tready     ),
		.o_wb_ack       (dma_o_wb_ack    ),
		.o_wb_dat       (dma_o_wb_dat    ),
		.wbm_cyc_o      (eng_o_wb_cyc    ),
		.wbm_stb_o      (eng_o_wb_stb    ),
		.wbm_we_o       (eng_o_wb_we     ),
		.wbm_adr_o      (eng_o_wb_adr    ),
		.wbm_dat_o      (eng_o_wb_dat    ),
		.wbm_sel_o      (eng_o_wb_sel    ),
		.m_axis_tdata   (axis_tdata      ),
		.m_axis_tvalid  (axis_tvalid     ),
		.m_axis_tlast   (axis_tlast      ),
		.o_irq          (o_dma_irq       )
	);
	sha256wb u_sha (
		.irq_o          (o_sha_irq       ),
		.clk            (clk             ),
		.rst_ni         (rst_ni          ),
		.s_axis_tdata   (axis_tdata      ),
		.s_axis_tvalid  (axis_tvalid     ),
		.s_axis_tlast   (axis_tlast      ),
		.rg_soft_reset  (rg_soft_reset   ),
		.p_rg_done_clear(p_rg_done_clear ),
		.s_axis_tready  (axis_tready     ),
		.ro_busy        (ro_busy         ),
		.ro_done        (ro_done         ),
		.ro_hash0       (ro_hash0        ),
		.ro_hash1       (ro_hash1        ),
		.ro_hash2       (ro_hash2        ),
		.ro_hash3       (ro_hash3        ),
		.ro_hash4       (ro_hash4        ),
		.ro_hash5       (ro_hash5        ),
		.ro_hash6       (ro_hash6        ),
		.ro_hash7       (ro_hash7        )
	);

endmodule
