// Generated by autowire dump (unit "sha256wb"). Do not edit: SoT is the connect HTML.
module sha256wb (
	output wire         irq_o,
	input  wire         clk,
	input  wire         rst_ni,
	input  wire         i_wb_cyc,
	input  wire         i_wb_stb,
	input  wire         i_wb_we,
	input  wire  [31:0] i_wb_addr,
	input  wire  [31:0] i_wb_data,
	input  wire  [3:0]  i_wb_sel,
	input  wire  [31:0] s_axis_tdata,
	input  wire         s_axis_tvalid,
	input  wire         s_axis_tlast,
	output wire         o_wb_ack,
	output wire  [31:0] o_wb_data,
	output wire         s_axis_tready
);
	wire         dat_valid;
	wire  [31:0] dat_lsb;
	wire         core_rst_n;
	wire         hash_busy;
	wire         irq_finish;
	wire  [31:0] hash0;
	wire  [31:0] hash1;
	wire  [31:0] hash2;
	wire  [31:0] hash3;
	wire  [31:0] hash4;
	wire  [31:0] hash5;
	wire  [31:0] hash6;
	wire  [31:0] hash7;

	sha256_wb_regs u_regs (
		.clk          (clk),
		.rst_ni       (rst_ni),
		.i_wb_cyc     (i_wb_cyc),
		.i_wb_stb     (i_wb_stb),
		.i_wb_we      (i_wb_we),
		.i_wb_addr    (i_wb_addr),
		.i_wb_data    (i_wb_data),
		.i_wb_sel     (i_wb_sel),
		.s_axis_tdata (s_axis_tdata),
		.s_axis_tvalid(s_axis_tvalid),
		.s_axis_tlast (s_axis_tlast),
		.i_hash_busy  (hash_busy),
		.i_irq_finish (irq_finish),
		.i_hash0      (hash0),
		.i_hash1      (hash1),
		.i_hash2      (hash2),
		.i_hash3      (hash3),
		.i_hash4      (hash4),
		.i_hash5      (hash5),
		.i_hash6      (hash6),
		.i_hash7      (hash7),
		.o_wb_ack     (o_wb_ack),
		.o_wb_data    (o_wb_data),
		.s_axis_tready(s_axis_tready),
		.o_dat_valid  (dat_valid),
		.o_dat_lsb    (dat_lsb),
		.o_core_rst_n (core_rst_n),
		.o_irq        (irq_o)
	);
	sha256 u_core (
		.clk        (clk),
		.rst_n      (core_rst_n),
		.dat_vaild_i(dat_valid),
		.dat_lsb_i  (dat_lsb),
		.hash0      (hash0),
		.hash1      (hash1),
		.hash2      (hash2),
		.hash3      (hash3),
		.hash4      (hash4),
		.hash5      (hash5),
		.hash6      (hash6),
		.hash7      (hash7),
		.hash_busy_o(hash_busy),
		.irq_finish (irq_finish)
	);

endmodule
