// Generated by autowire dump (unit "soc_top"). Do not edit: SoT is the connect HTML.
module soc_top (
	input  wire         clk,
	input  wire         rst_ni,
	output wire         trap,
	output wire         ser_tx,
	input  wire         ser_rx,
	output wire         flash_csb,
	output wire         flash_clk,
	output wire         flash_io0_oe,
	output wire         flash_io1_oe,
	output wire         flash_io2_oe,
	output wire         flash_io3_oe,
	output wire         flash_io0_do,
	output wire         flash_io1_do,
	output wire         flash_io2_do,
	output wire         flash_io3_do,
	input  wire         flash_io0_di,
	input  wire         flash_io1_di,
	input  wire         flash_io2_di,
	input  wire         flash_io3_di,
	output wire         sd0_cs_n,
	output wire         sd0_sck,
	output wire         sd0_mosi,
	input  wire         sd0_miso,
	input  wire         sd0_cd,
	output wire         sd1_cs_n,
	output wire         sd1_sck,
	output wire         sd1_mosi,
	input  wire         sd1_miso,
	input  wire         sd1_cd,
	output wire         test_valid,
	output wire  [31:0] test_data
);
	localparam SOC_TOP__U_IC__SLAVE_BASE = {32'h03005000, 32'h03004000, 32'h03003000, 32'h03002000, 32'h03001000, 32'h03000000, 32'h02000010, 32'h02000004, 32'h02000000, 32'h01000000, 32'h00000000};
	localparam SOC_TOP__U_IC__SLAVE_MASK = {32'hffffffc0, 32'hffffffc0, 32'hfffffff0, 32'hfffffff0, 32'hfffffff0, 32'hfffffff0, 32'hfffffffc, 32'hfffffff8, 32'hfffffffc, 32'hff000000, 32'hffff0000};

	wire          rst;
	wire  [2:0]   ic_m_cyc;
	wire  [2:0]   ic_m_stb;
	wire  [2:0]   ic_m_we;
	wire  [2:0]   ic_m_ack;
	wire  [95:0]  ic_m_adr;
	wire  [95:0]  ic_m_wdata;
	wire  [95:0]  ic_m_rdata;
	wire  [11:0]  ic_m_sel;
	wire  [31:0]  irq_bus;
	wire  [351:0] ic_s_adr;
	wire  [351:0] ic_s_wdata;
	wire  [43:0]  ic_s_sel;
	wire  [10:0]  ic_s_cyc;
	wire  [10:0]  ic_s_stb;
	wire  [10:0]  ic_s_we;
	wire  [351:0] ic_s_rdata;
	wire  [10:0]  ic_s_ack;
	wire  [5:0]   irq_srcs;
	wire  [31:0]  axs0_tdata;
	wire          axs0_tvalid;
	wire          axs0_tready;
	wire          axs0_tlast;
	wire  [31:0]  axs1_tdata;
	wire          axs1_tvalid;
	wire          axs1_tready;
	wire          axs1_tlast;

	soc_reset u_rst (
		.clk    (clk),
		.i_rst_n(rst_ni),
		.o_rst  (rst)
	);
	picorv32_wb #(
		.BARREL_SHIFTER  (1),
		.COMPRESSED_ISA  (1),
		.ENABLE_MUL      (1),
		.ENABLE_DIV      (1),
		.ENABLE_IRQ      (1),
		.ENABLE_IRQ_QREGS(0),
		.LATCHED_IRQ     (32'h00000000),
		.PROGADDR_RESET  (32'h01000000),
		.PROGADDR_IRQ    (32'h00000000),
		.STACKADDR       (32'h00010000)
	) u_cpu_0 (
		.wb_rst_i   (rst),
		.wb_clk_i   (clk),
		.wbm_dat_i  (ic_m_rdata[31:0]),
		.wbm_ack_i  (ic_m_ack[0]),
		.pcpi_wr    (1'b0),
		.pcpi_rd    (32'h00000000),
		.pcpi_wait  (1'b0),
		.pcpi_ready (1'b0),
		.irq        (irq_bus),
		.trap       (trap),
		.wbm_adr_o  (ic_m_adr[31:0]),
		.wbm_dat_o  (ic_m_wdata[31:0]),
		.wbm_we_o   (ic_m_we[0]),
		.wbm_sel_o  (ic_m_sel[3:0]),
		.wbm_stb_o  (ic_m_stb[0]),
		.wbm_cyc_o  (ic_m_cyc[0]),
		.pcpi_valid (),
		.pcpi_insn  (),
		.pcpi_rs1   (),
		.pcpi_rs2   (),
		.eoi        (),
		.trace_valid(),
		.trace_data (),
		.mem_instr  ()
	);
	wb_interconnect #(
		.NM        (3),
		.NS        (11),
		.SLAVE_BASE(SOC_TOP__U_IC__SLAVE_BASE),
		.SLAVE_MASK(SOC_TOP__U_IC__SLAVE_MASK)
	) u_ic (
		.clk    (clk),
		.rst_n  (rst_ni),
		.m_adr_i(ic_m_adr),
		.m_dat_i(ic_m_wdata),
		.m_sel_i(ic_m_sel),
		.m_cyc_i(ic_m_cyc),
		.m_stb_i(ic_m_stb),
		.m_we_i (ic_m_we),
		.s_dat_i(ic_s_rdata),
		.s_ack_i(ic_s_ack),
		.m_dat_o(ic_m_rdata),
		.m_ack_o(ic_m_ack),
		.s_adr_o(ic_s_adr),
		.s_dat_o(ic_s_wdata),
		.s_sel_o(ic_s_sel),
		.s_cyc_o(ic_s_cyc),
		.s_stb_o(ic_s_stb),
		.s_we_o (ic_s_we)
	);
	wb_sram #(
		.WORDS(16384),
		.AW   (14)
	) u_ram_0 (
		.clk      (clk),
		.rst_n    (rst_ni),
		.i_wb_cyc (ic_s_cyc[0]),
		.i_wb_stb (ic_s_stb[0]),
		.i_wb_we  (ic_s_we[0]),
		.i_wb_addr(ic_s_adr[31:0]),
		.i_wb_data(ic_s_wdata[31:0]),
		.i_wb_sel (ic_s_sel[3:0]),
		.o_wb_ack (ic_s_ack[0]),
		.o_wb_data(ic_s_rdata[31:0])
	);
	wb_spiflash u_flash_1 (
		.clk         (clk),
		.rst_n       (rst_ni),
		.i_wb_cyc    (ic_s_cyc[1]),
		.i_wb_stb    (ic_s_stb[1]),
		.i_wb_we     (ic_s_we[1]),
		.i_wb_addr   (ic_s_adr[63:32]),
		.i_wb_data   (ic_s_wdata[63:32]),
		.i_wb_sel    (ic_s_sel[7:4]),
		.i_cfg_cyc   (ic_s_cyc[2]),
		.i_cfg_stb   (ic_s_stb[2]),
		.i_cfg_we    (ic_s_we[2]),
		.i_cfg_addr  (ic_s_adr[95:64]),
		.i_cfg_data  (ic_s_wdata[95:64]),
		.i_cfg_sel   (ic_s_sel[11:8]),
		.flash_io0_di(flash_io0_di),
		.flash_io1_di(flash_io1_di),
		.flash_io2_di(flash_io2_di),
		.flash_io3_di(flash_io3_di),
		.o_wb_ack    (ic_s_ack[1]),
		.o_wb_data   (ic_s_rdata[63:32]),
		.o_cfg_ack   (ic_s_ack[2]),
		.o_cfg_data  (ic_s_rdata[95:64]),
		.flash_csb   (flash_csb),
		.flash_clk   (flash_clk),
		.flash_io0_oe(flash_io0_oe),
		.flash_io1_oe(flash_io1_oe),
		.flash_io2_oe(flash_io2_oe),
		.flash_io3_oe(flash_io3_oe),
		.flash_io0_do(flash_io0_do),
		.flash_io1_do(flash_io1_do),
		.flash_io2_do(flash_io2_do),
		.flash_io3_do(flash_io3_do)
	);
	wb_uart u_uart_3 (
		.clk      (clk),
		.rst_n    (rst_ni),
		.i_wb_cyc (ic_s_cyc[3]),
		.i_wb_stb (ic_s_stb[3]),
		.i_wb_we  (ic_s_we[3]),
		.i_wb_addr(ic_s_adr[127:96]),
		.i_wb_data(ic_s_wdata[127:96]),
		.i_wb_sel (ic_s_sel[15:12]),
		.ser_rx   (ser_rx),
		.o_wb_ack (ic_s_ack[3]),
		.o_wb_data(ic_s_rdata[127:96]),
		.ser_tx   (ser_tx)
	);
	wb_testout u_testout_4 (
		.clk         (clk),
		.rst_n       (rst_ni),
		.i_wb_cyc    (ic_s_cyc[4]),
		.i_wb_stb    (ic_s_stb[4]),
		.i_wb_we     (ic_s_we[4]),
		.i_wb_addr   (ic_s_adr[159:128]),
		.i_wb_data   (ic_s_wdata[159:128]),
		.i_wb_sel    (ic_s_sel[19:16]),
		.o_wb_ack    (ic_s_ack[4]),
		.o_wb_data   (ic_s_rdata[159:128]),
		.o_test_valid(test_valid),
		.o_test_data (test_data)
	);
	sdspi u_sd_5 (
		.i_clk        (clk),
		.i_wb_cyc     (ic_s_cyc[5]),
		.i_wb_addr    (ic_s_adr[163:162]),
		.i_wb_data    (ic_s_wdata[191:160]),
		.i_wb_sel     (ic_s_sel[23:20]),
		.i_miso       (sd0_miso),
		.i_bus_grant  (1'b1),
		.o_wb_stall   (),
		.o_wb_ack     (ic_s_ack[5]),
		.o_wb_data    (ic_s_rdata[191:160]),
		.o_cs_n       (sd0_cs_n),
		.o_int        (irq_srcs[0]),
		.i_sd_reset   (rst),
		.i_wb_stb     (ic_s_stb[5]),
		.i_wb_we      (ic_s_we[5]),
		.o_sck        (sd0_sck),
		.o_mosi       (sd0_mosi),
		.i_card_detect(sd0_cd)
	);
	sdspi u_sd_6 (
		.i_clk        (clk),
		.i_wb_cyc     (ic_s_cyc[6]),
		.i_wb_addr    (ic_s_adr[195:194]),
		.i_wb_data    (ic_s_wdata[223:192]),
		.i_wb_sel     (ic_s_sel[27:24]),
		.i_miso       (sd1_miso),
		.i_bus_grant  (1'b1),
		.o_wb_stall   (),
		.o_wb_ack     (ic_s_ack[6]),
		.o_wb_data    (ic_s_rdata[223:192]),
		.o_cs_n       (sd1_cs_n),
		.o_int        (irq_srcs[1]),
		.i_sd_reset   (rst),
		.i_wb_stb     (ic_s_stb[6]),
		.i_wb_we      (ic_s_we[6]),
		.o_sck        (sd1_sck),
		.o_mosi       (sd1_mosi),
		.i_card_detect(sd1_cd)
	);
	sd_rd_dma u_dma_1 (
		.clk          (clk),
		.rst_n        (rst_ni),
		.i_wb_cyc     (ic_s_cyc[7]),
		.i_wb_stb     (ic_s_stb[7]),
		.i_wb_we      (ic_s_we[7]),
		.i_wb_addr    (ic_s_adr[255:224]),
		.i_wb_data    (ic_s_wdata[255:224]),
		.i_wb_sel     (ic_s_sel[31:28]),
		.wbm_ack_i    (ic_m_ack[1]),
		.wbm_dat_i    (ic_m_rdata[63:32]),
		.m_axis_tready(axs0_tready),
		.o_wb_ack     (ic_s_ack[7]),
		.o_wb_data    (ic_s_rdata[255:224]),
		.wbm_cyc_o    (ic_m_cyc[1]),
		.wbm_stb_o    (ic_m_stb[1]),
		.wbm_we_o     (ic_m_we[1]),
		.wbm_adr_o    (ic_m_adr[63:32]),
		.wbm_dat_o    (ic_m_wdata[63:32]),
		.wbm_sel_o    (ic_m_sel[7:4]),
		.m_axis_tdata (axs0_tdata),
		.m_axis_tvalid(axs0_tvalid),
		.m_axis_tlast (axs0_tlast),
		.o_irq        (irq_srcs[2])
	);
	sd_rd_dma u_dma_2 (
		.clk          (clk),
		.rst_n        (rst_ni),
		.i_wb_cyc     (ic_s_cyc[8]),
		.i_wb_stb     (ic_s_stb[8]),
		.i_wb_we      (ic_s_we[8]),
		.i_wb_addr    (ic_s_adr[287:256]),
		.i_wb_data    (ic_s_wdata[287:256]),
		.i_wb_sel     (ic_s_sel[35:32]),
		.wbm_ack_i    (ic_m_ack[2]),
		.wbm_dat_i    (ic_m_rdata[95:64]),
		.m_axis_tready(axs1_tready),
		.o_wb_ack     (ic_s_ack[8]),
		.o_wb_data    (ic_s_rdata[287:256]),
		.wbm_cyc_o    (ic_m_cyc[2]),
		.wbm_stb_o    (ic_m_stb[2]),
		.wbm_we_o     (ic_m_we[2]),
		.wbm_adr_o    (ic_m_adr[95:64]),
		.wbm_dat_o    (ic_m_wdata[95:64]),
		.wbm_sel_o    (ic_m_sel[11:8]),
		.m_axis_tdata (axs1_tdata),
		.m_axis_tvalid(axs1_tvalid),
		.m_axis_tlast (axs1_tlast),
		.o_irq        (irq_srcs[3])
	);
	sha256wb u_sha_9 (
		.clk          (clk),
		.rst_ni       (rst_ni),
		.i_wb_cyc     (ic_s_cyc[9]),
		.i_wb_stb     (ic_s_stb[9]),
		.i_wb_we      (ic_s_we[9]),
		.i_wb_addr    (ic_s_adr[319:288]),
		.i_wb_data    (ic_s_wdata[319:288]),
		.i_wb_sel     (ic_s_sel[39:36]),
		.o_wb_ack     (ic_s_ack[9]),
		.o_wb_data    (ic_s_rdata[319:288]),
		.s_axis_tdata (axs0_tdata),
		.s_axis_tvalid(axs0_tvalid),
		.s_axis_tready(axs0_tready),
		.s_axis_tlast (axs0_tlast),
		.irq_o        (irq_srcs[4])
	);
	sha256wb u_sha_10 (
		.clk          (clk),
		.rst_ni       (rst_ni),
		.i_wb_cyc     (ic_s_cyc[10]),
		.i_wb_stb     (ic_s_stb[10]),
		.i_wb_we      (ic_s_we[10]),
		.i_wb_addr    (ic_s_adr[351:320]),
		.i_wb_data    (ic_s_wdata[351:320]),
		.i_wb_sel     (ic_s_sel[43:40]),
		.o_wb_ack     (ic_s_ack[10]),
		.o_wb_data    (ic_s_rdata[351:320]),
		.s_axis_tdata (axs1_tdata),
		.s_axis_tvalid(axs1_tvalid),
		.s_axis_tready(axs1_tready),
		.s_axis_tlast (axs1_tlast),
		.irq_o        (irq_srcs[5])
	);
	soc_irqmerge u_irq (
		.i_ints(irq_srcs),
		.o_irq (irq_bus)
	);

endmodule
