// Generated by autowire plugin wishbone (hbm_ch). Do not edit.
// uvm_reg_block map: Slave.base + cell offset. Cell classes are packed beside this file.

`ifndef RAL_BLOCK_HBM_CH_SV
`define RAL_BLOCK_HBM_CH_SV

import uvm_pkg::*;
`include "uvm_macros.svh"

`include "ral_AWORD.sv"
`include "ral_DWORD.sv"

class ral_block_hbm_ch extends uvm_reg_block;
	rand ral_reg_aword_ID aword_ID;
	rand ral_reg_aword_STATUS aword_STATUS;
	rand ral_reg_aword_TIMING aword_TIMING;
	rand ral_reg_aword_DRIVE aword_DRIVE;
	rand ral_reg_dword_ID dword0_ID;
	rand ral_reg_dword_STATUS dword0_STATUS;
	rand ral_reg_dword_VREF dword0_VREF;
	rand ral_reg_dword_EQ dword0_EQ;
	rand ral_reg_dword_ID dword1_ID;
	rand ral_reg_dword_STATUS dword1_STATUS;
	rand ral_reg_dword_VREF dword1_VREF;
	rand ral_reg_dword_EQ dword1_EQ;

	function new(string name = "ral_block_hbm_ch");
		super.new(name, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		default_map = create_map("default_map", 0, 4, UVM_LITTLE_ENDIAN);
		this.aword_ID = ral_reg_aword_ID::type_id::create("aword_ID",, get_full_name());
		this.aword_ID.configure(this);
		this.aword_ID.build();
		default_map.add_reg(this.aword_ID, 32'h00000000, "RO");
		this.aword_STATUS = ral_reg_aword_STATUS::type_id::create("aword_STATUS",, get_full_name());
		this.aword_STATUS.configure(this);
		this.aword_STATUS.build();
		default_map.add_reg(this.aword_STATUS, 32'h00000004, "RO");
		// aword.TIMING: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.aword_TIMING = ral_reg_aword_TIMING::type_id::create("aword_TIMING",, get_full_name());
		this.aword_TIMING.configure(this);
		this.aword_TIMING.build();
		default_map.add_reg(this.aword_TIMING, 32'h00000008, "RW");
		// aword.DRIVE: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.aword_DRIVE = ral_reg_aword_DRIVE::type_id::create("aword_DRIVE",, get_full_name());
		this.aword_DRIVE.configure(this);
		this.aword_DRIVE.build();
		default_map.add_reg(this.aword_DRIVE, 32'h0000000c, "RW");
		this.dword0_ID = ral_reg_dword_ID::type_id::create("dword0_ID",, get_full_name());
		this.dword0_ID.configure(this);
		this.dword0_ID.build();
		default_map.add_reg(this.dword0_ID, 32'h00000100, "RO");
		this.dword0_STATUS = ral_reg_dword_STATUS::type_id::create("dword0_STATUS",, get_full_name());
		this.dword0_STATUS.configure(this);
		this.dword0_STATUS.build();
		default_map.add_reg(this.dword0_STATUS, 32'h00000104, "RO");
		// dword0.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.dword0_VREF = ral_reg_dword_VREF::type_id::create("dword0_VREF",, get_full_name());
		this.dword0_VREF.configure(this);
		this.dword0_VREF.build();
		default_map.add_reg(this.dword0_VREF, 32'h00000108, "RW");
		// dword0.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.dword0_EQ = ral_reg_dword_EQ::type_id::create("dword0_EQ",, get_full_name());
		this.dword0_EQ.configure(this);
		this.dword0_EQ.build();
		default_map.add_reg(this.dword0_EQ, 32'h0000010c, "RW");
		this.dword1_ID = ral_reg_dword_ID::type_id::create("dword1_ID",, get_full_name());
		this.dword1_ID.configure(this);
		this.dword1_ID.build();
		default_map.add_reg(this.dword1_ID, 32'h00000200, "RO");
		this.dword1_STATUS = ral_reg_dword_STATUS::type_id::create("dword1_STATUS",, get_full_name());
		this.dword1_STATUS.configure(this);
		this.dword1_STATUS.build();
		default_map.add_reg(this.dword1_STATUS, 32'h00000204, "RO");
		// dword1.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.dword1_VREF = ral_reg_dword_VREF::type_id::create("dword1_VREF",, get_full_name());
		this.dword1_VREF.configure(this);
		this.dword1_VREF.build();
		default_map.add_reg(this.dword1_VREF, 32'h00000208, "RW");
		// dword1.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.dword1_EQ = ral_reg_dword_EQ::type_id::create("dword1_EQ",, get_full_name());
		this.dword1_EQ.configure(this);
		this.dword1_EQ.build();
		default_map.add_reg(this.dword1_EQ, 32'h0000020c, "RW");
	endfunction: build

	`uvm_object_utils(ral_block_hbm_ch)
endclass : ral_block_hbm_ch

`endif // RAL_BLOCK_HBM_CH_SV
