// Generated by autowire plugin wishbone (hbm). Do not edit.
// uvm_reg_block: one sub-block per child bus, one register per TagFromAddr alias.
// Broadcast windows are comments: uvm_reg has no broadcast frontdoor.

`ifndef RAL_BLOCK_HBM_SV
`define RAL_BLOCK_HBM_SV

import uvm_pkg::*;
`include "uvm_macros.svh"

`include "ral_AWORD.sv"
`include "ral_DWORD.sv"

`include "ral_block_hbm_ch.sv"

class ral_block_hbm extends uvm_reg_block;
	rand ral_block_hbm_ch ch0_pstate0;
	rand ral_block_hbm_ch ch0_pstate1;
	rand ral_block_hbm_ch ch0_pstate2;
	rand ral_block_hbm_ch ch0_pstate3;
	rand ral_block_hbm_ch ch1_pstate0;
	rand ral_block_hbm_ch ch1_pstate1;
	rand ral_block_hbm_ch ch1_pstate2;
	rand ral_block_hbm_ch ch1_pstate3;
	rand ral_block_hbm_ch ch2_pstate0;
	rand ral_block_hbm_ch ch2_pstate1;
	rand ral_block_hbm_ch ch2_pstate2;
	rand ral_block_hbm_ch ch2_pstate3;
	rand ral_block_hbm_ch ch3_pstate0;
	rand ral_block_hbm_ch ch3_pstate1;
	rand ral_block_hbm_ch ch3_pstate2;
	rand ral_block_hbm_ch ch3_pstate3;
	rand ral_block_hbm_ch ch4_pstate0;
	rand ral_block_hbm_ch ch4_pstate1;
	rand ral_block_hbm_ch ch4_pstate2;
	rand ral_block_hbm_ch ch4_pstate3;
	rand ral_block_hbm_ch ch5_pstate0;
	rand ral_block_hbm_ch ch5_pstate1;
	rand ral_block_hbm_ch ch5_pstate2;
	rand ral_block_hbm_ch ch5_pstate3;
	rand ral_block_hbm_ch ch6_pstate0;
	rand ral_block_hbm_ch ch6_pstate1;
	rand ral_block_hbm_ch ch6_pstate2;
	rand ral_block_hbm_ch ch6_pstate3;
	rand ral_block_hbm_ch ch7_pstate0;
	rand ral_block_hbm_ch ch7_pstate1;
	rand ral_block_hbm_ch ch7_pstate2;
	rand ral_block_hbm_ch ch7_pstate3;
	rand ral_block_hbm_ch ch8_pstate0;
	rand ral_block_hbm_ch ch8_pstate1;
	rand ral_block_hbm_ch ch8_pstate2;
	rand ral_block_hbm_ch ch8_pstate3;
	rand ral_block_hbm_ch ch9_pstate0;
	rand ral_block_hbm_ch ch9_pstate1;
	rand ral_block_hbm_ch ch9_pstate2;
	rand ral_block_hbm_ch ch9_pstate3;
	rand ral_block_hbm_ch ch10_pstate0;
	rand ral_block_hbm_ch ch10_pstate1;
	rand ral_block_hbm_ch ch10_pstate2;
	rand ral_block_hbm_ch ch10_pstate3;
	rand ral_block_hbm_ch ch11_pstate0;
	rand ral_block_hbm_ch ch11_pstate1;
	rand ral_block_hbm_ch ch11_pstate2;
	rand ral_block_hbm_ch ch11_pstate3;
	rand ral_block_hbm_ch ch12_pstate0;
	rand ral_block_hbm_ch ch12_pstate1;
	rand ral_block_hbm_ch ch12_pstate2;
	rand ral_block_hbm_ch ch12_pstate3;
	rand ral_block_hbm_ch ch13_pstate0;
	rand ral_block_hbm_ch ch13_pstate1;
	rand ral_block_hbm_ch ch13_pstate2;
	rand ral_block_hbm_ch ch13_pstate3;
	rand ral_block_hbm_ch ch14_pstate0;
	rand ral_block_hbm_ch ch14_pstate1;
	rand ral_block_hbm_ch ch14_pstate2;
	rand ral_block_hbm_ch ch14_pstate3;
	rand ral_block_hbm_ch ch15_pstate0;
	rand ral_block_hbm_ch ch15_pstate1;
	rand ral_block_hbm_ch ch15_pstate2;
	rand ral_block_hbm_ch ch15_pstate3;

	function new(string name = "ral_block_hbm");
		super.new(name, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		default_map = create_map("default_map", 0, 4, UVM_LITTLE_ENDIAN);
		// ch_bcast @ 32'h00010000: broadcast ch_all: one write at this window hits every subscriber
		// ch0_pstate0: pstate=0
		this.ch0_pstate0 = ral_block_hbm_ch::type_id::create("ch0_pstate0",, get_full_name());
		this.ch0_pstate0.configure(this, "");
		this.ch0_pstate0.build();
		default_map.add_submap(this.ch0_pstate0.default_map, 32'h00000000);
		// ch0_pstate1: pstate=1
		this.ch0_pstate1 = ral_block_hbm_ch::type_id::create("ch0_pstate1",, get_full_name());
		this.ch0_pstate1.configure(this, "");
		this.ch0_pstate1.build();
		default_map.add_submap(this.ch0_pstate1.default_map, 32'h00020000);
		// ch0_pstate2: pstate=2
		this.ch0_pstate2 = ral_block_hbm_ch::type_id::create("ch0_pstate2",, get_full_name());
		this.ch0_pstate2.configure(this, "");
		this.ch0_pstate2.build();
		default_map.add_submap(this.ch0_pstate2.default_map, 32'h00040000);
		// ch0_pstate3: pstate=3
		this.ch0_pstate3 = ral_block_hbm_ch::type_id::create("ch0_pstate3",, get_full_name());
		this.ch0_pstate3.configure(this, "");
		this.ch0_pstate3.build();
		default_map.add_submap(this.ch0_pstate3.default_map, 32'h00060000);
		// ch1_pstate0: pstate=0
		this.ch1_pstate0 = ral_block_hbm_ch::type_id::create("ch1_pstate0",, get_full_name());
		this.ch1_pstate0.configure(this, "");
		this.ch1_pstate0.build();
		default_map.add_submap(this.ch1_pstate0.default_map, 32'h00001000);
		// ch1_pstate1: pstate=1
		this.ch1_pstate1 = ral_block_hbm_ch::type_id::create("ch1_pstate1",, get_full_name());
		this.ch1_pstate1.configure(this, "");
		this.ch1_pstate1.build();
		default_map.add_submap(this.ch1_pstate1.default_map, 32'h00021000);
		// ch1_pstate2: pstate=2
		this.ch1_pstate2 = ral_block_hbm_ch::type_id::create("ch1_pstate2",, get_full_name());
		this.ch1_pstate2.configure(this, "");
		this.ch1_pstate2.build();
		default_map.add_submap(this.ch1_pstate2.default_map, 32'h00041000);
		// ch1_pstate3: pstate=3
		this.ch1_pstate3 = ral_block_hbm_ch::type_id::create("ch1_pstate3",, get_full_name());
		this.ch1_pstate3.configure(this, "");
		this.ch1_pstate3.build();
		default_map.add_submap(this.ch1_pstate3.default_map, 32'h00061000);
		// ch2_pstate0: pstate=0
		this.ch2_pstate0 = ral_block_hbm_ch::type_id::create("ch2_pstate0",, get_full_name());
		this.ch2_pstate0.configure(this, "");
		this.ch2_pstate0.build();
		default_map.add_submap(this.ch2_pstate0.default_map, 32'h00002000);
		// ch2_pstate1: pstate=1
		this.ch2_pstate1 = ral_block_hbm_ch::type_id::create("ch2_pstate1",, get_full_name());
		this.ch2_pstate1.configure(this, "");
		this.ch2_pstate1.build();
		default_map.add_submap(this.ch2_pstate1.default_map, 32'h00022000);
		// ch2_pstate2: pstate=2
		this.ch2_pstate2 = ral_block_hbm_ch::type_id::create("ch2_pstate2",, get_full_name());
		this.ch2_pstate2.configure(this, "");
		this.ch2_pstate2.build();
		default_map.add_submap(this.ch2_pstate2.default_map, 32'h00042000);
		// ch2_pstate3: pstate=3
		this.ch2_pstate3 = ral_block_hbm_ch::type_id::create("ch2_pstate3",, get_full_name());
		this.ch2_pstate3.configure(this, "");
		this.ch2_pstate3.build();
		default_map.add_submap(this.ch2_pstate3.default_map, 32'h00062000);
		// ch3_pstate0: pstate=0
		this.ch3_pstate0 = ral_block_hbm_ch::type_id::create("ch3_pstate0",, get_full_name());
		this.ch3_pstate0.configure(this, "");
		this.ch3_pstate0.build();
		default_map.add_submap(this.ch3_pstate0.default_map, 32'h00003000);
		// ch3_pstate1: pstate=1
		this.ch3_pstate1 = ral_block_hbm_ch::type_id::create("ch3_pstate1",, get_full_name());
		this.ch3_pstate1.configure(this, "");
		this.ch3_pstate1.build();
		default_map.add_submap(this.ch3_pstate1.default_map, 32'h00023000);
		// ch3_pstate2: pstate=2
		this.ch3_pstate2 = ral_block_hbm_ch::type_id::create("ch3_pstate2",, get_full_name());
		this.ch3_pstate2.configure(this, "");
		this.ch3_pstate2.build();
		default_map.add_submap(this.ch3_pstate2.default_map, 32'h00043000);
		// ch3_pstate3: pstate=3
		this.ch3_pstate3 = ral_block_hbm_ch::type_id::create("ch3_pstate3",, get_full_name());
		this.ch3_pstate3.configure(this, "");
		this.ch3_pstate3.build();
		default_map.add_submap(this.ch3_pstate3.default_map, 32'h00063000);
		// ch4_pstate0: pstate=0
		this.ch4_pstate0 = ral_block_hbm_ch::type_id::create("ch4_pstate0",, get_full_name());
		this.ch4_pstate0.configure(this, "");
		this.ch4_pstate0.build();
		default_map.add_submap(this.ch4_pstate0.default_map, 32'h00004000);
		// ch4_pstate1: pstate=1
		this.ch4_pstate1 = ral_block_hbm_ch::type_id::create("ch4_pstate1",, get_full_name());
		this.ch4_pstate1.configure(this, "");
		this.ch4_pstate1.build();
		default_map.add_submap(this.ch4_pstate1.default_map, 32'h00024000);
		// ch4_pstate2: pstate=2
		this.ch4_pstate2 = ral_block_hbm_ch::type_id::create("ch4_pstate2",, get_full_name());
		this.ch4_pstate2.configure(this, "");
		this.ch4_pstate2.build();
		default_map.add_submap(this.ch4_pstate2.default_map, 32'h00044000);
		// ch4_pstate3: pstate=3
		this.ch4_pstate3 = ral_block_hbm_ch::type_id::create("ch4_pstate3",, get_full_name());
		this.ch4_pstate3.configure(this, "");
		this.ch4_pstate3.build();
		default_map.add_submap(this.ch4_pstate3.default_map, 32'h00064000);
		// ch5_pstate0: pstate=0
		this.ch5_pstate0 = ral_block_hbm_ch::type_id::create("ch5_pstate0",, get_full_name());
		this.ch5_pstate0.configure(this, "");
		this.ch5_pstate0.build();
		default_map.add_submap(this.ch5_pstate0.default_map, 32'h00005000);
		// ch5_pstate1: pstate=1
		this.ch5_pstate1 = ral_block_hbm_ch::type_id::create("ch5_pstate1",, get_full_name());
		this.ch5_pstate1.configure(this, "");
		this.ch5_pstate1.build();
		default_map.add_submap(this.ch5_pstate1.default_map, 32'h00025000);
		// ch5_pstate2: pstate=2
		this.ch5_pstate2 = ral_block_hbm_ch::type_id::create("ch5_pstate2",, get_full_name());
		this.ch5_pstate2.configure(this, "");
		this.ch5_pstate2.build();
		default_map.add_submap(this.ch5_pstate2.default_map, 32'h00045000);
		// ch5_pstate3: pstate=3
		this.ch5_pstate3 = ral_block_hbm_ch::type_id::create("ch5_pstate3",, get_full_name());
		this.ch5_pstate3.configure(this, "");
		this.ch5_pstate3.build();
		default_map.add_submap(this.ch5_pstate3.default_map, 32'h00065000);
		// ch6_pstate0: pstate=0
		this.ch6_pstate0 = ral_block_hbm_ch::type_id::create("ch6_pstate0",, get_full_name());
		this.ch6_pstate0.configure(this, "");
		this.ch6_pstate0.build();
		default_map.add_submap(this.ch6_pstate0.default_map, 32'h00006000);
		// ch6_pstate1: pstate=1
		this.ch6_pstate1 = ral_block_hbm_ch::type_id::create("ch6_pstate1",, get_full_name());
		this.ch6_pstate1.configure(this, "");
		this.ch6_pstate1.build();
		default_map.add_submap(this.ch6_pstate1.default_map, 32'h00026000);
		// ch6_pstate2: pstate=2
		this.ch6_pstate2 = ral_block_hbm_ch::type_id::create("ch6_pstate2",, get_full_name());
		this.ch6_pstate2.configure(this, "");
		this.ch6_pstate2.build();
		default_map.add_submap(this.ch6_pstate2.default_map, 32'h00046000);
		// ch6_pstate3: pstate=3
		this.ch6_pstate3 = ral_block_hbm_ch::type_id::create("ch6_pstate3",, get_full_name());
		this.ch6_pstate3.configure(this, "");
		this.ch6_pstate3.build();
		default_map.add_submap(this.ch6_pstate3.default_map, 32'h00066000);
		// ch7_pstate0: pstate=0
		this.ch7_pstate0 = ral_block_hbm_ch::type_id::create("ch7_pstate0",, get_full_name());
		this.ch7_pstate0.configure(this, "");
		this.ch7_pstate0.build();
		default_map.add_submap(this.ch7_pstate0.default_map, 32'h00007000);
		// ch7_pstate1: pstate=1
		this.ch7_pstate1 = ral_block_hbm_ch::type_id::create("ch7_pstate1",, get_full_name());
		this.ch7_pstate1.configure(this, "");
		this.ch7_pstate1.build();
		default_map.add_submap(this.ch7_pstate1.default_map, 32'h00027000);
		// ch7_pstate2: pstate=2
		this.ch7_pstate2 = ral_block_hbm_ch::type_id::create("ch7_pstate2",, get_full_name());
		this.ch7_pstate2.configure(this, "");
		this.ch7_pstate2.build();
		default_map.add_submap(this.ch7_pstate2.default_map, 32'h00047000);
		// ch7_pstate3: pstate=3
		this.ch7_pstate3 = ral_block_hbm_ch::type_id::create("ch7_pstate3",, get_full_name());
		this.ch7_pstate3.configure(this, "");
		this.ch7_pstate3.build();
		default_map.add_submap(this.ch7_pstate3.default_map, 32'h00067000);
		// ch8_pstate0: pstate=0
		this.ch8_pstate0 = ral_block_hbm_ch::type_id::create("ch8_pstate0",, get_full_name());
		this.ch8_pstate0.configure(this, "");
		this.ch8_pstate0.build();
		default_map.add_submap(this.ch8_pstate0.default_map, 32'h00008000);
		// ch8_pstate1: pstate=1
		this.ch8_pstate1 = ral_block_hbm_ch::type_id::create("ch8_pstate1",, get_full_name());
		this.ch8_pstate1.configure(this, "");
		this.ch8_pstate1.build();
		default_map.add_submap(this.ch8_pstate1.default_map, 32'h00028000);
		// ch8_pstate2: pstate=2
		this.ch8_pstate2 = ral_block_hbm_ch::type_id::create("ch8_pstate2",, get_full_name());
		this.ch8_pstate2.configure(this, "");
		this.ch8_pstate2.build();
		default_map.add_submap(this.ch8_pstate2.default_map, 32'h00048000);
		// ch8_pstate3: pstate=3
		this.ch8_pstate3 = ral_block_hbm_ch::type_id::create("ch8_pstate3",, get_full_name());
		this.ch8_pstate3.configure(this, "");
		this.ch8_pstate3.build();
		default_map.add_submap(this.ch8_pstate3.default_map, 32'h00068000);
		// ch9_pstate0: pstate=0
		this.ch9_pstate0 = ral_block_hbm_ch::type_id::create("ch9_pstate0",, get_full_name());
		this.ch9_pstate0.configure(this, "");
		this.ch9_pstate0.build();
		default_map.add_submap(this.ch9_pstate0.default_map, 32'h00009000);
		// ch9_pstate1: pstate=1
		this.ch9_pstate1 = ral_block_hbm_ch::type_id::create("ch9_pstate1",, get_full_name());
		this.ch9_pstate1.configure(this, "");
		this.ch9_pstate1.build();
		default_map.add_submap(this.ch9_pstate1.default_map, 32'h00029000);
		// ch9_pstate2: pstate=2
		this.ch9_pstate2 = ral_block_hbm_ch::type_id::create("ch9_pstate2",, get_full_name());
		this.ch9_pstate2.configure(this, "");
		this.ch9_pstate2.build();
		default_map.add_submap(this.ch9_pstate2.default_map, 32'h00049000);
		// ch9_pstate3: pstate=3
		this.ch9_pstate3 = ral_block_hbm_ch::type_id::create("ch9_pstate3",, get_full_name());
		this.ch9_pstate3.configure(this, "");
		this.ch9_pstate3.build();
		default_map.add_submap(this.ch9_pstate3.default_map, 32'h00069000);
		// ch10_pstate0: pstate=0
		this.ch10_pstate0 = ral_block_hbm_ch::type_id::create("ch10_pstate0",, get_full_name());
		this.ch10_pstate0.configure(this, "");
		this.ch10_pstate0.build();
		default_map.add_submap(this.ch10_pstate0.default_map, 32'h0000a000);
		// ch10_pstate1: pstate=1
		this.ch10_pstate1 = ral_block_hbm_ch::type_id::create("ch10_pstate1",, get_full_name());
		this.ch10_pstate1.configure(this, "");
		this.ch10_pstate1.build();
		default_map.add_submap(this.ch10_pstate1.default_map, 32'h0002a000);
		// ch10_pstate2: pstate=2
		this.ch10_pstate2 = ral_block_hbm_ch::type_id::create("ch10_pstate2",, get_full_name());
		this.ch10_pstate2.configure(this, "");
		this.ch10_pstate2.build();
		default_map.add_submap(this.ch10_pstate2.default_map, 32'h0004a000);
		// ch10_pstate3: pstate=3
		this.ch10_pstate3 = ral_block_hbm_ch::type_id::create("ch10_pstate3",, get_full_name());
		this.ch10_pstate3.configure(this, "");
		this.ch10_pstate3.build();
		default_map.add_submap(this.ch10_pstate3.default_map, 32'h0006a000);
		// ch11_pstate0: pstate=0
		this.ch11_pstate0 = ral_block_hbm_ch::type_id::create("ch11_pstate0",, get_full_name());
		this.ch11_pstate0.configure(this, "");
		this.ch11_pstate0.build();
		default_map.add_submap(this.ch11_pstate0.default_map, 32'h0000b000);
		// ch11_pstate1: pstate=1
		this.ch11_pstate1 = ral_block_hbm_ch::type_id::create("ch11_pstate1",, get_full_name());
		this.ch11_pstate1.configure(this, "");
		this.ch11_pstate1.build();
		default_map.add_submap(this.ch11_pstate1.default_map, 32'h0002b000);
		// ch11_pstate2: pstate=2
		this.ch11_pstate2 = ral_block_hbm_ch::type_id::create("ch11_pstate2",, get_full_name());
		this.ch11_pstate2.configure(this, "");
		this.ch11_pstate2.build();
		default_map.add_submap(this.ch11_pstate2.default_map, 32'h0004b000);
		// ch11_pstate3: pstate=3
		this.ch11_pstate3 = ral_block_hbm_ch::type_id::create("ch11_pstate3",, get_full_name());
		this.ch11_pstate3.configure(this, "");
		this.ch11_pstate3.build();
		default_map.add_submap(this.ch11_pstate3.default_map, 32'h0006b000);
		// ch12_pstate0: pstate=0
		this.ch12_pstate0 = ral_block_hbm_ch::type_id::create("ch12_pstate0",, get_full_name());
		this.ch12_pstate0.configure(this, "");
		this.ch12_pstate0.build();
		default_map.add_submap(this.ch12_pstate0.default_map, 32'h0000c000);
		// ch12_pstate1: pstate=1
		this.ch12_pstate1 = ral_block_hbm_ch::type_id::create("ch12_pstate1",, get_full_name());
		this.ch12_pstate1.configure(this, "");
		this.ch12_pstate1.build();
		default_map.add_submap(this.ch12_pstate1.default_map, 32'h0002c000);
		// ch12_pstate2: pstate=2
		this.ch12_pstate2 = ral_block_hbm_ch::type_id::create("ch12_pstate2",, get_full_name());
		this.ch12_pstate2.configure(this, "");
		this.ch12_pstate2.build();
		default_map.add_submap(this.ch12_pstate2.default_map, 32'h0004c000);
		// ch12_pstate3: pstate=3
		this.ch12_pstate3 = ral_block_hbm_ch::type_id::create("ch12_pstate3",, get_full_name());
		this.ch12_pstate3.configure(this, "");
		this.ch12_pstate3.build();
		default_map.add_submap(this.ch12_pstate3.default_map, 32'h0006c000);
		// ch13_pstate0: pstate=0
		this.ch13_pstate0 = ral_block_hbm_ch::type_id::create("ch13_pstate0",, get_full_name());
		this.ch13_pstate0.configure(this, "");
		this.ch13_pstate0.build();
		default_map.add_submap(this.ch13_pstate0.default_map, 32'h0000d000);
		// ch13_pstate1: pstate=1
		this.ch13_pstate1 = ral_block_hbm_ch::type_id::create("ch13_pstate1",, get_full_name());
		this.ch13_pstate1.configure(this, "");
		this.ch13_pstate1.build();
		default_map.add_submap(this.ch13_pstate1.default_map, 32'h0002d000);
		// ch13_pstate2: pstate=2
		this.ch13_pstate2 = ral_block_hbm_ch::type_id::create("ch13_pstate2",, get_full_name());
		this.ch13_pstate2.configure(this, "");
		this.ch13_pstate2.build();
		default_map.add_submap(this.ch13_pstate2.default_map, 32'h0004d000);
		// ch13_pstate3: pstate=3
		this.ch13_pstate3 = ral_block_hbm_ch::type_id::create("ch13_pstate3",, get_full_name());
		this.ch13_pstate3.configure(this, "");
		this.ch13_pstate3.build();
		default_map.add_submap(this.ch13_pstate3.default_map, 32'h0006d000);
		// ch14_pstate0: pstate=0
		this.ch14_pstate0 = ral_block_hbm_ch::type_id::create("ch14_pstate0",, get_full_name());
		this.ch14_pstate0.configure(this, "");
		this.ch14_pstate0.build();
		default_map.add_submap(this.ch14_pstate0.default_map, 32'h0000e000);
		// ch14_pstate1: pstate=1
		this.ch14_pstate1 = ral_block_hbm_ch::type_id::create("ch14_pstate1",, get_full_name());
		this.ch14_pstate1.configure(this, "");
		this.ch14_pstate1.build();
		default_map.add_submap(this.ch14_pstate1.default_map, 32'h0002e000);
		// ch14_pstate2: pstate=2
		this.ch14_pstate2 = ral_block_hbm_ch::type_id::create("ch14_pstate2",, get_full_name());
		this.ch14_pstate2.configure(this, "");
		this.ch14_pstate2.build();
		default_map.add_submap(this.ch14_pstate2.default_map, 32'h0004e000);
		// ch14_pstate3: pstate=3
		this.ch14_pstate3 = ral_block_hbm_ch::type_id::create("ch14_pstate3",, get_full_name());
		this.ch14_pstate3.configure(this, "");
		this.ch14_pstate3.build();
		default_map.add_submap(this.ch14_pstate3.default_map, 32'h0006e000);
		// ch15_pstate0: pstate=0
		this.ch15_pstate0 = ral_block_hbm_ch::type_id::create("ch15_pstate0",, get_full_name());
		this.ch15_pstate0.configure(this, "");
		this.ch15_pstate0.build();
		default_map.add_submap(this.ch15_pstate0.default_map, 32'h0000f000);
		// ch15_pstate1: pstate=1
		this.ch15_pstate1 = ral_block_hbm_ch::type_id::create("ch15_pstate1",, get_full_name());
		this.ch15_pstate1.configure(this, "");
		this.ch15_pstate1.build();
		default_map.add_submap(this.ch15_pstate1.default_map, 32'h0002f000);
		// ch15_pstate2: pstate=2
		this.ch15_pstate2 = ral_block_hbm_ch::type_id::create("ch15_pstate2",, get_full_name());
		this.ch15_pstate2.configure(this, "");
		this.ch15_pstate2.build();
		default_map.add_submap(this.ch15_pstate2.default_map, 32'h0004f000);
		// ch15_pstate3: pstate=3
		this.ch15_pstate3 = ral_block_hbm_ch::type_id::create("ch15_pstate3",, get_full_name());
		this.ch15_pstate3.configure(this, "");
		this.ch15_pstate3.build();
		default_map.add_submap(this.ch15_pstate3.default_map, 32'h0006f000);
	endfunction: build

	`uvm_object_utils(ral_block_hbm)
endclass : ral_block_hbm

`endif // RAL_BLOCK_HBM_SV
