// Generated by autowire plugin wishbone (hbm). Do not edit.
// uvm_reg_block map: Slave.base + cell offset. Cell classes are packed beside this file.

`ifndef RAL_BLOCK_HBM_SV
`define RAL_BLOCK_HBM_SV

import uvm_pkg::*;
`include "uvm_macros.svh"

`include "ral_AWORD.sv"
`include "ral_DWORD.sv"

class ral_block_hbm extends uvm_reg_block;
	rand ral_reg_aword_ID ch0_aword_ID;
	rand ral_reg_aword_STATUS ch0_aword_STATUS;
	rand ral_reg_aword_TIMING ch0_aword_TIMING;
	rand ral_reg_aword_DRIVE ch0_aword_DRIVE;
	rand ral_reg_dword_ID ch0_dword0_ID;
	rand ral_reg_dword_STATUS ch0_dword0_STATUS;
	rand ral_reg_dword_VREF ch0_dword0_VREF;
	rand ral_reg_dword_EQ ch0_dword0_EQ;
	rand ral_reg_dword_ID ch0_dword1_ID;
	rand ral_reg_dword_STATUS ch0_dword1_STATUS;
	rand ral_reg_dword_VREF ch0_dword1_VREF;
	rand ral_reg_dword_EQ ch0_dword1_EQ;
	rand ral_reg_aword_ID ch1_aword_ID;
	rand ral_reg_aword_STATUS ch1_aword_STATUS;
	rand ral_reg_aword_TIMING ch1_aword_TIMING;
	rand ral_reg_aword_DRIVE ch1_aword_DRIVE;
	rand ral_reg_dword_ID ch1_dword0_ID;
	rand ral_reg_dword_STATUS ch1_dword0_STATUS;
	rand ral_reg_dword_VREF ch1_dword0_VREF;
	rand ral_reg_dword_EQ ch1_dword0_EQ;
	rand ral_reg_dword_ID ch1_dword1_ID;
	rand ral_reg_dword_STATUS ch1_dword1_STATUS;
	rand ral_reg_dword_VREF ch1_dword1_VREF;
	rand ral_reg_dword_EQ ch1_dword1_EQ;
	rand ral_reg_aword_ID ch2_aword_ID;
	rand ral_reg_aword_STATUS ch2_aword_STATUS;
	rand ral_reg_aword_TIMING ch2_aword_TIMING;
	rand ral_reg_aword_DRIVE ch2_aword_DRIVE;
	rand ral_reg_dword_ID ch2_dword0_ID;
	rand ral_reg_dword_STATUS ch2_dword0_STATUS;
	rand ral_reg_dword_VREF ch2_dword0_VREF;
	rand ral_reg_dword_EQ ch2_dword0_EQ;
	rand ral_reg_dword_ID ch2_dword1_ID;
	rand ral_reg_dword_STATUS ch2_dword1_STATUS;
	rand ral_reg_dword_VREF ch2_dword1_VREF;
	rand ral_reg_dword_EQ ch2_dword1_EQ;
	rand ral_reg_aword_ID ch3_aword_ID;
	rand ral_reg_aword_STATUS ch3_aword_STATUS;
	rand ral_reg_aword_TIMING ch3_aword_TIMING;
	rand ral_reg_aword_DRIVE ch3_aword_DRIVE;
	rand ral_reg_dword_ID ch3_dword0_ID;
	rand ral_reg_dword_STATUS ch3_dword0_STATUS;
	rand ral_reg_dword_VREF ch3_dword0_VREF;
	rand ral_reg_dword_EQ ch3_dword0_EQ;
	rand ral_reg_dword_ID ch3_dword1_ID;
	rand ral_reg_dword_STATUS ch3_dword1_STATUS;
	rand ral_reg_dword_VREF ch3_dword1_VREF;
	rand ral_reg_dword_EQ ch3_dword1_EQ;
	rand ral_reg_aword_ID ch4_aword_ID;
	rand ral_reg_aword_STATUS ch4_aword_STATUS;
	rand ral_reg_aword_TIMING ch4_aword_TIMING;
	rand ral_reg_aword_DRIVE ch4_aword_DRIVE;
	rand ral_reg_dword_ID ch4_dword0_ID;
	rand ral_reg_dword_STATUS ch4_dword0_STATUS;
	rand ral_reg_dword_VREF ch4_dword0_VREF;
	rand ral_reg_dword_EQ ch4_dword0_EQ;
	rand ral_reg_dword_ID ch4_dword1_ID;
	rand ral_reg_dword_STATUS ch4_dword1_STATUS;
	rand ral_reg_dword_VREF ch4_dword1_VREF;
	rand ral_reg_dword_EQ ch4_dword1_EQ;
	rand ral_reg_aword_ID ch5_aword_ID;
	rand ral_reg_aword_STATUS ch5_aword_STATUS;
	rand ral_reg_aword_TIMING ch5_aword_TIMING;
	rand ral_reg_aword_DRIVE ch5_aword_DRIVE;
	rand ral_reg_dword_ID ch5_dword0_ID;
	rand ral_reg_dword_STATUS ch5_dword0_STATUS;
	rand ral_reg_dword_VREF ch5_dword0_VREF;
	rand ral_reg_dword_EQ ch5_dword0_EQ;
	rand ral_reg_dword_ID ch5_dword1_ID;
	rand ral_reg_dword_STATUS ch5_dword1_STATUS;
	rand ral_reg_dword_VREF ch5_dword1_VREF;
	rand ral_reg_dword_EQ ch5_dword1_EQ;
	rand ral_reg_aword_ID ch6_aword_ID;
	rand ral_reg_aword_STATUS ch6_aword_STATUS;
	rand ral_reg_aword_TIMING ch6_aword_TIMING;
	rand ral_reg_aword_DRIVE ch6_aword_DRIVE;
	rand ral_reg_dword_ID ch6_dword0_ID;
	rand ral_reg_dword_STATUS ch6_dword0_STATUS;
	rand ral_reg_dword_VREF ch6_dword0_VREF;
	rand ral_reg_dword_EQ ch6_dword0_EQ;
	rand ral_reg_dword_ID ch6_dword1_ID;
	rand ral_reg_dword_STATUS ch6_dword1_STATUS;
	rand ral_reg_dword_VREF ch6_dword1_VREF;
	rand ral_reg_dword_EQ ch6_dword1_EQ;
	rand ral_reg_aword_ID ch7_aword_ID;
	rand ral_reg_aword_STATUS ch7_aword_STATUS;
	rand ral_reg_aword_TIMING ch7_aword_TIMING;
	rand ral_reg_aword_DRIVE ch7_aword_DRIVE;
	rand ral_reg_dword_ID ch7_dword0_ID;
	rand ral_reg_dword_STATUS ch7_dword0_STATUS;
	rand ral_reg_dword_VREF ch7_dword0_VREF;
	rand ral_reg_dword_EQ ch7_dword0_EQ;
	rand ral_reg_dword_ID ch7_dword1_ID;
	rand ral_reg_dword_STATUS ch7_dword1_STATUS;
	rand ral_reg_dword_VREF ch7_dword1_VREF;
	rand ral_reg_dword_EQ ch7_dword1_EQ;
	rand ral_reg_aword_ID ch8_aword_ID;
	rand ral_reg_aword_STATUS ch8_aword_STATUS;
	rand ral_reg_aword_TIMING ch8_aword_TIMING;
	rand ral_reg_aword_DRIVE ch8_aword_DRIVE;
	rand ral_reg_dword_ID ch8_dword0_ID;
	rand ral_reg_dword_STATUS ch8_dword0_STATUS;
	rand ral_reg_dword_VREF ch8_dword0_VREF;
	rand ral_reg_dword_EQ ch8_dword0_EQ;
	rand ral_reg_dword_ID ch8_dword1_ID;
	rand ral_reg_dword_STATUS ch8_dword1_STATUS;
	rand ral_reg_dword_VREF ch8_dword1_VREF;
	rand ral_reg_dword_EQ ch8_dword1_EQ;
	rand ral_reg_aword_ID ch9_aword_ID;
	rand ral_reg_aword_STATUS ch9_aword_STATUS;
	rand ral_reg_aword_TIMING ch9_aword_TIMING;
	rand ral_reg_aword_DRIVE ch9_aword_DRIVE;
	rand ral_reg_dword_ID ch9_dword0_ID;
	rand ral_reg_dword_STATUS ch9_dword0_STATUS;
	rand ral_reg_dword_VREF ch9_dword0_VREF;
	rand ral_reg_dword_EQ ch9_dword0_EQ;
	rand ral_reg_dword_ID ch9_dword1_ID;
	rand ral_reg_dword_STATUS ch9_dword1_STATUS;
	rand ral_reg_dword_VREF ch9_dword1_VREF;
	rand ral_reg_dword_EQ ch9_dword1_EQ;
	rand ral_reg_aword_ID ch10_aword_ID;
	rand ral_reg_aword_STATUS ch10_aword_STATUS;
	rand ral_reg_aword_TIMING ch10_aword_TIMING;
	rand ral_reg_aword_DRIVE ch10_aword_DRIVE;
	rand ral_reg_dword_ID ch10_dword0_ID;
	rand ral_reg_dword_STATUS ch10_dword0_STATUS;
	rand ral_reg_dword_VREF ch10_dword0_VREF;
	rand ral_reg_dword_EQ ch10_dword0_EQ;
	rand ral_reg_dword_ID ch10_dword1_ID;
	rand ral_reg_dword_STATUS ch10_dword1_STATUS;
	rand ral_reg_dword_VREF ch10_dword1_VREF;
	rand ral_reg_dword_EQ ch10_dword1_EQ;
	rand ral_reg_aword_ID ch11_aword_ID;
	rand ral_reg_aword_STATUS ch11_aword_STATUS;
	rand ral_reg_aword_TIMING ch11_aword_TIMING;
	rand ral_reg_aword_DRIVE ch11_aword_DRIVE;
	rand ral_reg_dword_ID ch11_dword0_ID;
	rand ral_reg_dword_STATUS ch11_dword0_STATUS;
	rand ral_reg_dword_VREF ch11_dword0_VREF;
	rand ral_reg_dword_EQ ch11_dword0_EQ;
	rand ral_reg_dword_ID ch11_dword1_ID;
	rand ral_reg_dword_STATUS ch11_dword1_STATUS;
	rand ral_reg_dword_VREF ch11_dword1_VREF;
	rand ral_reg_dword_EQ ch11_dword1_EQ;
	rand ral_reg_aword_ID ch12_aword_ID;
	rand ral_reg_aword_STATUS ch12_aword_STATUS;
	rand ral_reg_aword_TIMING ch12_aword_TIMING;
	rand ral_reg_aword_DRIVE ch12_aword_DRIVE;
	rand ral_reg_dword_ID ch12_dword0_ID;
	rand ral_reg_dword_STATUS ch12_dword0_STATUS;
	rand ral_reg_dword_VREF ch12_dword0_VREF;
	rand ral_reg_dword_EQ ch12_dword0_EQ;
	rand ral_reg_dword_ID ch12_dword1_ID;
	rand ral_reg_dword_STATUS ch12_dword1_STATUS;
	rand ral_reg_dword_VREF ch12_dword1_VREF;
	rand ral_reg_dword_EQ ch12_dword1_EQ;
	rand ral_reg_aword_ID ch13_aword_ID;
	rand ral_reg_aword_STATUS ch13_aword_STATUS;
	rand ral_reg_aword_TIMING ch13_aword_TIMING;
	rand ral_reg_aword_DRIVE ch13_aword_DRIVE;
	rand ral_reg_dword_ID ch13_dword0_ID;
	rand ral_reg_dword_STATUS ch13_dword0_STATUS;
	rand ral_reg_dword_VREF ch13_dword0_VREF;
	rand ral_reg_dword_EQ ch13_dword0_EQ;
	rand ral_reg_dword_ID ch13_dword1_ID;
	rand ral_reg_dword_STATUS ch13_dword1_STATUS;
	rand ral_reg_dword_VREF ch13_dword1_VREF;
	rand ral_reg_dword_EQ ch13_dword1_EQ;
	rand ral_reg_aword_ID ch14_aword_ID;
	rand ral_reg_aword_STATUS ch14_aword_STATUS;
	rand ral_reg_aword_TIMING ch14_aword_TIMING;
	rand ral_reg_aword_DRIVE ch14_aword_DRIVE;
	rand ral_reg_dword_ID ch14_dword0_ID;
	rand ral_reg_dword_STATUS ch14_dword0_STATUS;
	rand ral_reg_dword_VREF ch14_dword0_VREF;
	rand ral_reg_dword_EQ ch14_dword0_EQ;
	rand ral_reg_dword_ID ch14_dword1_ID;
	rand ral_reg_dword_STATUS ch14_dword1_STATUS;
	rand ral_reg_dword_VREF ch14_dword1_VREF;
	rand ral_reg_dword_EQ ch14_dword1_EQ;
	rand ral_reg_aword_ID ch15_aword_ID;
	rand ral_reg_aword_STATUS ch15_aword_STATUS;
	rand ral_reg_aword_TIMING ch15_aword_TIMING;
	rand ral_reg_aword_DRIVE ch15_aword_DRIVE;
	rand ral_reg_dword_ID ch15_dword0_ID;
	rand ral_reg_dword_STATUS ch15_dword0_STATUS;
	rand ral_reg_dword_VREF ch15_dword0_VREF;
	rand ral_reg_dword_EQ ch15_dword0_EQ;
	rand ral_reg_dword_ID ch15_dword1_ID;
	rand ral_reg_dword_STATUS ch15_dword1_STATUS;
	rand ral_reg_dword_VREF ch15_dword1_VREF;
	rand ral_reg_dword_EQ ch15_dword1_EQ;

	function new(string name = "ral_block_hbm");
		super.new(name, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		default_map = create_map("default_map", 0, 4, UVM_LITTLE_ENDIAN);
		this.ch0_aword_ID = ral_reg_aword_ID::type_id::create("ch0_aword_ID",, get_full_name());
		this.ch0_aword_ID.configure(this);
		this.ch0_aword_ID.build();
		default_map.add_reg(this.ch0_aword_ID, 32'h00000000, "RO");
		this.ch0_aword_STATUS = ral_reg_aword_STATUS::type_id::create("ch0_aword_STATUS",, get_full_name());
		this.ch0_aword_STATUS.configure(this);
		this.ch0_aword_STATUS.build();
		default_map.add_reg(this.ch0_aword_STATUS, 32'h00000004, "RO");
		// ch0_aword.TIMING: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch0_aword_TIMING = ral_reg_aword_TIMING::type_id::create("ch0_aword_TIMING",, get_full_name());
		this.ch0_aword_TIMING.configure(this);
		this.ch0_aword_TIMING.build();
		default_map.add_reg(this.ch0_aword_TIMING, 32'h00000008, "RW");
		// ch0_aword.DRIVE: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch0_aword_DRIVE = ral_reg_aword_DRIVE::type_id::create("ch0_aword_DRIVE",, get_full_name());
		this.ch0_aword_DRIVE.configure(this);
		this.ch0_aword_DRIVE.build();
		default_map.add_reg(this.ch0_aword_DRIVE, 32'h0000000c, "RW");
		this.ch0_dword0_ID = ral_reg_dword_ID::type_id::create("ch0_dword0_ID",, get_full_name());
		this.ch0_dword0_ID.configure(this);
		this.ch0_dword0_ID.build();
		default_map.add_reg(this.ch0_dword0_ID, 32'h00000100, "RO");
		this.ch0_dword0_STATUS = ral_reg_dword_STATUS::type_id::create("ch0_dword0_STATUS",, get_full_name());
		this.ch0_dword0_STATUS.configure(this);
		this.ch0_dword0_STATUS.build();
		default_map.add_reg(this.ch0_dword0_STATUS, 32'h00000104, "RO");
		// ch0_dword0.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch0_dword0_VREF = ral_reg_dword_VREF::type_id::create("ch0_dword0_VREF",, get_full_name());
		this.ch0_dword0_VREF.configure(this);
		this.ch0_dword0_VREF.build();
		default_map.add_reg(this.ch0_dword0_VREF, 32'h00000108, "RW");
		// ch0_dword0.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch0_dword0_EQ = ral_reg_dword_EQ::type_id::create("ch0_dword0_EQ",, get_full_name());
		this.ch0_dword0_EQ.configure(this);
		this.ch0_dword0_EQ.build();
		default_map.add_reg(this.ch0_dword0_EQ, 32'h0000010c, "RW");
		this.ch0_dword1_ID = ral_reg_dword_ID::type_id::create("ch0_dword1_ID",, get_full_name());
		this.ch0_dword1_ID.configure(this);
		this.ch0_dword1_ID.build();
		default_map.add_reg(this.ch0_dword1_ID, 32'h00000200, "RO");
		this.ch0_dword1_STATUS = ral_reg_dword_STATUS::type_id::create("ch0_dword1_STATUS",, get_full_name());
		this.ch0_dword1_STATUS.configure(this);
		this.ch0_dword1_STATUS.build();
		default_map.add_reg(this.ch0_dword1_STATUS, 32'h00000204, "RO");
		// ch0_dword1.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch0_dword1_VREF = ral_reg_dword_VREF::type_id::create("ch0_dword1_VREF",, get_full_name());
		this.ch0_dword1_VREF.configure(this);
		this.ch0_dword1_VREF.build();
		default_map.add_reg(this.ch0_dword1_VREF, 32'h00000208, "RW");
		// ch0_dword1.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch0_dword1_EQ = ral_reg_dword_EQ::type_id::create("ch0_dword1_EQ",, get_full_name());
		this.ch0_dword1_EQ.configure(this);
		this.ch0_dword1_EQ.build();
		default_map.add_reg(this.ch0_dword1_EQ, 32'h0000020c, "RW");
		this.ch1_aword_ID = ral_reg_aword_ID::type_id::create("ch1_aword_ID",, get_full_name());
		this.ch1_aword_ID.configure(this);
		this.ch1_aword_ID.build();
		default_map.add_reg(this.ch1_aword_ID, 32'h00001000, "RO");
		this.ch1_aword_STATUS = ral_reg_aword_STATUS::type_id::create("ch1_aword_STATUS",, get_full_name());
		this.ch1_aword_STATUS.configure(this);
		this.ch1_aword_STATUS.build();
		default_map.add_reg(this.ch1_aword_STATUS, 32'h00001004, "RO");
		// ch1_aword.TIMING: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch1_aword_TIMING = ral_reg_aword_TIMING::type_id::create("ch1_aword_TIMING",, get_full_name());
		this.ch1_aword_TIMING.configure(this);
		this.ch1_aword_TIMING.build();
		default_map.add_reg(this.ch1_aword_TIMING, 32'h00001008, "RW");
		// ch1_aword.DRIVE: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch1_aword_DRIVE = ral_reg_aword_DRIVE::type_id::create("ch1_aword_DRIVE",, get_full_name());
		this.ch1_aword_DRIVE.configure(this);
		this.ch1_aword_DRIVE.build();
		default_map.add_reg(this.ch1_aword_DRIVE, 32'h0000100c, "RW");
		this.ch1_dword0_ID = ral_reg_dword_ID::type_id::create("ch1_dword0_ID",, get_full_name());
		this.ch1_dword0_ID.configure(this);
		this.ch1_dword0_ID.build();
		default_map.add_reg(this.ch1_dword0_ID, 32'h00001100, "RO");
		this.ch1_dword0_STATUS = ral_reg_dword_STATUS::type_id::create("ch1_dword0_STATUS",, get_full_name());
		this.ch1_dword0_STATUS.configure(this);
		this.ch1_dword0_STATUS.build();
		default_map.add_reg(this.ch1_dword0_STATUS, 32'h00001104, "RO");
		// ch1_dword0.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch1_dword0_VREF = ral_reg_dword_VREF::type_id::create("ch1_dword0_VREF",, get_full_name());
		this.ch1_dword0_VREF.configure(this);
		this.ch1_dword0_VREF.build();
		default_map.add_reg(this.ch1_dword0_VREF, 32'h00001108, "RW");
		// ch1_dword0.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch1_dword0_EQ = ral_reg_dword_EQ::type_id::create("ch1_dword0_EQ",, get_full_name());
		this.ch1_dword0_EQ.configure(this);
		this.ch1_dword0_EQ.build();
		default_map.add_reg(this.ch1_dword0_EQ, 32'h0000110c, "RW");
		this.ch1_dword1_ID = ral_reg_dword_ID::type_id::create("ch1_dword1_ID",, get_full_name());
		this.ch1_dword1_ID.configure(this);
		this.ch1_dword1_ID.build();
		default_map.add_reg(this.ch1_dword1_ID, 32'h00001200, "RO");
		this.ch1_dword1_STATUS = ral_reg_dword_STATUS::type_id::create("ch1_dword1_STATUS",, get_full_name());
		this.ch1_dword1_STATUS.configure(this);
		this.ch1_dword1_STATUS.build();
		default_map.add_reg(this.ch1_dword1_STATUS, 32'h00001204, "RO");
		// ch1_dword1.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch1_dword1_VREF = ral_reg_dword_VREF::type_id::create("ch1_dword1_VREF",, get_full_name());
		this.ch1_dword1_VREF.configure(this);
		this.ch1_dword1_VREF.build();
		default_map.add_reg(this.ch1_dword1_VREF, 32'h00001208, "RW");
		// ch1_dword1.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch1_dword1_EQ = ral_reg_dword_EQ::type_id::create("ch1_dword1_EQ",, get_full_name());
		this.ch1_dword1_EQ.configure(this);
		this.ch1_dword1_EQ.build();
		default_map.add_reg(this.ch1_dword1_EQ, 32'h0000120c, "RW");
		this.ch2_aword_ID = ral_reg_aword_ID::type_id::create("ch2_aword_ID",, get_full_name());
		this.ch2_aword_ID.configure(this);
		this.ch2_aword_ID.build();
		default_map.add_reg(this.ch2_aword_ID, 32'h00002000, "RO");
		this.ch2_aword_STATUS = ral_reg_aword_STATUS::type_id::create("ch2_aword_STATUS",, get_full_name());
		this.ch2_aword_STATUS.configure(this);
		this.ch2_aword_STATUS.build();
		default_map.add_reg(this.ch2_aword_STATUS, 32'h00002004, "RO");
		// ch2_aword.TIMING: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch2_aword_TIMING = ral_reg_aword_TIMING::type_id::create("ch2_aword_TIMING",, get_full_name());
		this.ch2_aword_TIMING.configure(this);
		this.ch2_aword_TIMING.build();
		default_map.add_reg(this.ch2_aword_TIMING, 32'h00002008, "RW");
		// ch2_aword.DRIVE: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch2_aword_DRIVE = ral_reg_aword_DRIVE::type_id::create("ch2_aword_DRIVE",, get_full_name());
		this.ch2_aword_DRIVE.configure(this);
		this.ch2_aword_DRIVE.build();
		default_map.add_reg(this.ch2_aword_DRIVE, 32'h0000200c, "RW");
		this.ch2_dword0_ID = ral_reg_dword_ID::type_id::create("ch2_dword0_ID",, get_full_name());
		this.ch2_dword0_ID.configure(this);
		this.ch2_dword0_ID.build();
		default_map.add_reg(this.ch2_dword0_ID, 32'h00002100, "RO");
		this.ch2_dword0_STATUS = ral_reg_dword_STATUS::type_id::create("ch2_dword0_STATUS",, get_full_name());
		this.ch2_dword0_STATUS.configure(this);
		this.ch2_dword0_STATUS.build();
		default_map.add_reg(this.ch2_dword0_STATUS, 32'h00002104, "RO");
		// ch2_dword0.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch2_dword0_VREF = ral_reg_dword_VREF::type_id::create("ch2_dword0_VREF",, get_full_name());
		this.ch2_dword0_VREF.configure(this);
		this.ch2_dword0_VREF.build();
		default_map.add_reg(this.ch2_dword0_VREF, 32'h00002108, "RW");
		// ch2_dword0.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch2_dword0_EQ = ral_reg_dword_EQ::type_id::create("ch2_dword0_EQ",, get_full_name());
		this.ch2_dword0_EQ.configure(this);
		this.ch2_dword0_EQ.build();
		default_map.add_reg(this.ch2_dword0_EQ, 32'h0000210c, "RW");
		this.ch2_dword1_ID = ral_reg_dword_ID::type_id::create("ch2_dword1_ID",, get_full_name());
		this.ch2_dword1_ID.configure(this);
		this.ch2_dword1_ID.build();
		default_map.add_reg(this.ch2_dword1_ID, 32'h00002200, "RO");
		this.ch2_dword1_STATUS = ral_reg_dword_STATUS::type_id::create("ch2_dword1_STATUS",, get_full_name());
		this.ch2_dword1_STATUS.configure(this);
		this.ch2_dword1_STATUS.build();
		default_map.add_reg(this.ch2_dword1_STATUS, 32'h00002204, "RO");
		// ch2_dword1.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch2_dword1_VREF = ral_reg_dword_VREF::type_id::create("ch2_dword1_VREF",, get_full_name());
		this.ch2_dword1_VREF.configure(this);
		this.ch2_dword1_VREF.build();
		default_map.add_reg(this.ch2_dword1_VREF, 32'h00002208, "RW");
		// ch2_dword1.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch2_dword1_EQ = ral_reg_dword_EQ::type_id::create("ch2_dword1_EQ",, get_full_name());
		this.ch2_dword1_EQ.configure(this);
		this.ch2_dword1_EQ.build();
		default_map.add_reg(this.ch2_dword1_EQ, 32'h0000220c, "RW");
		this.ch3_aword_ID = ral_reg_aword_ID::type_id::create("ch3_aword_ID",, get_full_name());
		this.ch3_aword_ID.configure(this);
		this.ch3_aword_ID.build();
		default_map.add_reg(this.ch3_aword_ID, 32'h00003000, "RO");
		this.ch3_aword_STATUS = ral_reg_aword_STATUS::type_id::create("ch3_aword_STATUS",, get_full_name());
		this.ch3_aword_STATUS.configure(this);
		this.ch3_aword_STATUS.build();
		default_map.add_reg(this.ch3_aword_STATUS, 32'h00003004, "RO");
		// ch3_aword.TIMING: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch3_aword_TIMING = ral_reg_aword_TIMING::type_id::create("ch3_aword_TIMING",, get_full_name());
		this.ch3_aword_TIMING.configure(this);
		this.ch3_aword_TIMING.build();
		default_map.add_reg(this.ch3_aword_TIMING, 32'h00003008, "RW");
		// ch3_aword.DRIVE: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch3_aword_DRIVE = ral_reg_aword_DRIVE::type_id::create("ch3_aword_DRIVE",, get_full_name());
		this.ch3_aword_DRIVE.configure(this);
		this.ch3_aword_DRIVE.build();
		default_map.add_reg(this.ch3_aword_DRIVE, 32'h0000300c, "RW");
		this.ch3_dword0_ID = ral_reg_dword_ID::type_id::create("ch3_dword0_ID",, get_full_name());
		this.ch3_dword0_ID.configure(this);
		this.ch3_dword0_ID.build();
		default_map.add_reg(this.ch3_dword0_ID, 32'h00003100, "RO");
		this.ch3_dword0_STATUS = ral_reg_dword_STATUS::type_id::create("ch3_dword0_STATUS",, get_full_name());
		this.ch3_dword0_STATUS.configure(this);
		this.ch3_dword0_STATUS.build();
		default_map.add_reg(this.ch3_dword0_STATUS, 32'h00003104, "RO");
		// ch3_dword0.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch3_dword0_VREF = ral_reg_dword_VREF::type_id::create("ch3_dword0_VREF",, get_full_name());
		this.ch3_dword0_VREF.configure(this);
		this.ch3_dword0_VREF.build();
		default_map.add_reg(this.ch3_dword0_VREF, 32'h00003108, "RW");
		// ch3_dword0.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch3_dword0_EQ = ral_reg_dword_EQ::type_id::create("ch3_dword0_EQ",, get_full_name());
		this.ch3_dword0_EQ.configure(this);
		this.ch3_dword0_EQ.build();
		default_map.add_reg(this.ch3_dword0_EQ, 32'h0000310c, "RW");
		this.ch3_dword1_ID = ral_reg_dword_ID::type_id::create("ch3_dword1_ID",, get_full_name());
		this.ch3_dword1_ID.configure(this);
		this.ch3_dword1_ID.build();
		default_map.add_reg(this.ch3_dword1_ID, 32'h00003200, "RO");
		this.ch3_dword1_STATUS = ral_reg_dword_STATUS::type_id::create("ch3_dword1_STATUS",, get_full_name());
		this.ch3_dword1_STATUS.configure(this);
		this.ch3_dword1_STATUS.build();
		default_map.add_reg(this.ch3_dword1_STATUS, 32'h00003204, "RO");
		// ch3_dword1.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch3_dword1_VREF = ral_reg_dword_VREF::type_id::create("ch3_dword1_VREF",, get_full_name());
		this.ch3_dword1_VREF.configure(this);
		this.ch3_dword1_VREF.build();
		default_map.add_reg(this.ch3_dword1_VREF, 32'h00003208, "RW");
		// ch3_dword1.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch3_dword1_EQ = ral_reg_dword_EQ::type_id::create("ch3_dword1_EQ",, get_full_name());
		this.ch3_dword1_EQ.configure(this);
		this.ch3_dword1_EQ.build();
		default_map.add_reg(this.ch3_dword1_EQ, 32'h0000320c, "RW");
		this.ch4_aword_ID = ral_reg_aword_ID::type_id::create("ch4_aword_ID",, get_full_name());
		this.ch4_aword_ID.configure(this);
		this.ch4_aword_ID.build();
		default_map.add_reg(this.ch4_aword_ID, 32'h00004000, "RO");
		this.ch4_aword_STATUS = ral_reg_aword_STATUS::type_id::create("ch4_aword_STATUS",, get_full_name());
		this.ch4_aword_STATUS.configure(this);
		this.ch4_aword_STATUS.build();
		default_map.add_reg(this.ch4_aword_STATUS, 32'h00004004, "RO");
		// ch4_aword.TIMING: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch4_aword_TIMING = ral_reg_aword_TIMING::type_id::create("ch4_aword_TIMING",, get_full_name());
		this.ch4_aword_TIMING.configure(this);
		this.ch4_aword_TIMING.build();
		default_map.add_reg(this.ch4_aword_TIMING, 32'h00004008, "RW");
		// ch4_aword.DRIVE: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch4_aword_DRIVE = ral_reg_aword_DRIVE::type_id::create("ch4_aword_DRIVE",, get_full_name());
		this.ch4_aword_DRIVE.configure(this);
		this.ch4_aword_DRIVE.build();
		default_map.add_reg(this.ch4_aword_DRIVE, 32'h0000400c, "RW");
		this.ch4_dword0_ID = ral_reg_dword_ID::type_id::create("ch4_dword0_ID",, get_full_name());
		this.ch4_dword0_ID.configure(this);
		this.ch4_dword0_ID.build();
		default_map.add_reg(this.ch4_dword0_ID, 32'h00004100, "RO");
		this.ch4_dword0_STATUS = ral_reg_dword_STATUS::type_id::create("ch4_dword0_STATUS",, get_full_name());
		this.ch4_dword0_STATUS.configure(this);
		this.ch4_dword0_STATUS.build();
		default_map.add_reg(this.ch4_dword0_STATUS, 32'h00004104, "RO");
		// ch4_dword0.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch4_dword0_VREF = ral_reg_dword_VREF::type_id::create("ch4_dword0_VREF",, get_full_name());
		this.ch4_dword0_VREF.configure(this);
		this.ch4_dword0_VREF.build();
		default_map.add_reg(this.ch4_dword0_VREF, 32'h00004108, "RW");
		// ch4_dword0.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch4_dword0_EQ = ral_reg_dword_EQ::type_id::create("ch4_dword0_EQ",, get_full_name());
		this.ch4_dword0_EQ.configure(this);
		this.ch4_dword0_EQ.build();
		default_map.add_reg(this.ch4_dword0_EQ, 32'h0000410c, "RW");
		this.ch4_dword1_ID = ral_reg_dword_ID::type_id::create("ch4_dword1_ID",, get_full_name());
		this.ch4_dword1_ID.configure(this);
		this.ch4_dword1_ID.build();
		default_map.add_reg(this.ch4_dword1_ID, 32'h00004200, "RO");
		this.ch4_dword1_STATUS = ral_reg_dword_STATUS::type_id::create("ch4_dword1_STATUS",, get_full_name());
		this.ch4_dword1_STATUS.configure(this);
		this.ch4_dword1_STATUS.build();
		default_map.add_reg(this.ch4_dword1_STATUS, 32'h00004204, "RO");
		// ch4_dword1.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch4_dword1_VREF = ral_reg_dword_VREF::type_id::create("ch4_dword1_VREF",, get_full_name());
		this.ch4_dword1_VREF.configure(this);
		this.ch4_dword1_VREF.build();
		default_map.add_reg(this.ch4_dword1_VREF, 32'h00004208, "RW");
		// ch4_dword1.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch4_dword1_EQ = ral_reg_dword_EQ::type_id::create("ch4_dword1_EQ",, get_full_name());
		this.ch4_dword1_EQ.configure(this);
		this.ch4_dword1_EQ.build();
		default_map.add_reg(this.ch4_dword1_EQ, 32'h0000420c, "RW");
		this.ch5_aword_ID = ral_reg_aword_ID::type_id::create("ch5_aword_ID",, get_full_name());
		this.ch5_aword_ID.configure(this);
		this.ch5_aword_ID.build();
		default_map.add_reg(this.ch5_aword_ID, 32'h00005000, "RO");
		this.ch5_aword_STATUS = ral_reg_aword_STATUS::type_id::create("ch5_aword_STATUS",, get_full_name());
		this.ch5_aword_STATUS.configure(this);
		this.ch5_aword_STATUS.build();
		default_map.add_reg(this.ch5_aword_STATUS, 32'h00005004, "RO");
		// ch5_aword.TIMING: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch5_aword_TIMING = ral_reg_aword_TIMING::type_id::create("ch5_aword_TIMING",, get_full_name());
		this.ch5_aword_TIMING.configure(this);
		this.ch5_aword_TIMING.build();
		default_map.add_reg(this.ch5_aword_TIMING, 32'h00005008, "RW");
		// ch5_aword.DRIVE: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch5_aword_DRIVE = ral_reg_aword_DRIVE::type_id::create("ch5_aword_DRIVE",, get_full_name());
		this.ch5_aword_DRIVE.configure(this);
		this.ch5_aword_DRIVE.build();
		default_map.add_reg(this.ch5_aword_DRIVE, 32'h0000500c, "RW");
		this.ch5_dword0_ID = ral_reg_dword_ID::type_id::create("ch5_dword0_ID",, get_full_name());
		this.ch5_dword0_ID.configure(this);
		this.ch5_dword0_ID.build();
		default_map.add_reg(this.ch5_dword0_ID, 32'h00005100, "RO");
		this.ch5_dword0_STATUS = ral_reg_dword_STATUS::type_id::create("ch5_dword0_STATUS",, get_full_name());
		this.ch5_dword0_STATUS.configure(this);
		this.ch5_dword0_STATUS.build();
		default_map.add_reg(this.ch5_dword0_STATUS, 32'h00005104, "RO");
		// ch5_dword0.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch5_dword0_VREF = ral_reg_dword_VREF::type_id::create("ch5_dword0_VREF",, get_full_name());
		this.ch5_dword0_VREF.configure(this);
		this.ch5_dword0_VREF.build();
		default_map.add_reg(this.ch5_dword0_VREF, 32'h00005108, "RW");
		// ch5_dword0.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch5_dword0_EQ = ral_reg_dword_EQ::type_id::create("ch5_dword0_EQ",, get_full_name());
		this.ch5_dword0_EQ.configure(this);
		this.ch5_dword0_EQ.build();
		default_map.add_reg(this.ch5_dword0_EQ, 32'h0000510c, "RW");
		this.ch5_dword1_ID = ral_reg_dword_ID::type_id::create("ch5_dword1_ID",, get_full_name());
		this.ch5_dword1_ID.configure(this);
		this.ch5_dword1_ID.build();
		default_map.add_reg(this.ch5_dword1_ID, 32'h00005200, "RO");
		this.ch5_dword1_STATUS = ral_reg_dword_STATUS::type_id::create("ch5_dword1_STATUS",, get_full_name());
		this.ch5_dword1_STATUS.configure(this);
		this.ch5_dword1_STATUS.build();
		default_map.add_reg(this.ch5_dword1_STATUS, 32'h00005204, "RO");
		// ch5_dword1.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch5_dword1_VREF = ral_reg_dword_VREF::type_id::create("ch5_dword1_VREF",, get_full_name());
		this.ch5_dword1_VREF.configure(this);
		this.ch5_dword1_VREF.build();
		default_map.add_reg(this.ch5_dword1_VREF, 32'h00005208, "RW");
		// ch5_dword1.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch5_dword1_EQ = ral_reg_dword_EQ::type_id::create("ch5_dword1_EQ",, get_full_name());
		this.ch5_dword1_EQ.configure(this);
		this.ch5_dword1_EQ.build();
		default_map.add_reg(this.ch5_dword1_EQ, 32'h0000520c, "RW");
		this.ch6_aword_ID = ral_reg_aword_ID::type_id::create("ch6_aword_ID",, get_full_name());
		this.ch6_aword_ID.configure(this);
		this.ch6_aword_ID.build();
		default_map.add_reg(this.ch6_aword_ID, 32'h00006000, "RO");
		this.ch6_aword_STATUS = ral_reg_aword_STATUS::type_id::create("ch6_aword_STATUS",, get_full_name());
		this.ch6_aword_STATUS.configure(this);
		this.ch6_aword_STATUS.build();
		default_map.add_reg(this.ch6_aword_STATUS, 32'h00006004, "RO");
		// ch6_aword.TIMING: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch6_aword_TIMING = ral_reg_aword_TIMING::type_id::create("ch6_aword_TIMING",, get_full_name());
		this.ch6_aword_TIMING.configure(this);
		this.ch6_aword_TIMING.build();
		default_map.add_reg(this.ch6_aword_TIMING, 32'h00006008, "RW");
		// ch6_aword.DRIVE: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch6_aword_DRIVE = ral_reg_aword_DRIVE::type_id::create("ch6_aword_DRIVE",, get_full_name());
		this.ch6_aword_DRIVE.configure(this);
		this.ch6_aword_DRIVE.build();
		default_map.add_reg(this.ch6_aword_DRIVE, 32'h0000600c, "RW");
		this.ch6_dword0_ID = ral_reg_dword_ID::type_id::create("ch6_dword0_ID",, get_full_name());
		this.ch6_dword0_ID.configure(this);
		this.ch6_dword0_ID.build();
		default_map.add_reg(this.ch6_dword0_ID, 32'h00006100, "RO");
		this.ch6_dword0_STATUS = ral_reg_dword_STATUS::type_id::create("ch6_dword0_STATUS",, get_full_name());
		this.ch6_dword0_STATUS.configure(this);
		this.ch6_dword0_STATUS.build();
		default_map.add_reg(this.ch6_dword0_STATUS, 32'h00006104, "RO");
		// ch6_dword0.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch6_dword0_VREF = ral_reg_dword_VREF::type_id::create("ch6_dword0_VREF",, get_full_name());
		this.ch6_dword0_VREF.configure(this);
		this.ch6_dword0_VREF.build();
		default_map.add_reg(this.ch6_dword0_VREF, 32'h00006108, "RW");
		// ch6_dword0.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch6_dword0_EQ = ral_reg_dword_EQ::type_id::create("ch6_dword0_EQ",, get_full_name());
		this.ch6_dword0_EQ.configure(this);
		this.ch6_dword0_EQ.build();
		default_map.add_reg(this.ch6_dword0_EQ, 32'h0000610c, "RW");
		this.ch6_dword1_ID = ral_reg_dword_ID::type_id::create("ch6_dword1_ID",, get_full_name());
		this.ch6_dword1_ID.configure(this);
		this.ch6_dword1_ID.build();
		default_map.add_reg(this.ch6_dword1_ID, 32'h00006200, "RO");
		this.ch6_dword1_STATUS = ral_reg_dword_STATUS::type_id::create("ch6_dword1_STATUS",, get_full_name());
		this.ch6_dword1_STATUS.configure(this);
		this.ch6_dword1_STATUS.build();
		default_map.add_reg(this.ch6_dword1_STATUS, 32'h00006204, "RO");
		// ch6_dword1.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch6_dword1_VREF = ral_reg_dword_VREF::type_id::create("ch6_dword1_VREF",, get_full_name());
		this.ch6_dword1_VREF.configure(this);
		this.ch6_dword1_VREF.build();
		default_map.add_reg(this.ch6_dword1_VREF, 32'h00006208, "RW");
		// ch6_dword1.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch6_dword1_EQ = ral_reg_dword_EQ::type_id::create("ch6_dword1_EQ",, get_full_name());
		this.ch6_dword1_EQ.configure(this);
		this.ch6_dword1_EQ.build();
		default_map.add_reg(this.ch6_dword1_EQ, 32'h0000620c, "RW");
		this.ch7_aword_ID = ral_reg_aword_ID::type_id::create("ch7_aword_ID",, get_full_name());
		this.ch7_aword_ID.configure(this);
		this.ch7_aword_ID.build();
		default_map.add_reg(this.ch7_aword_ID, 32'h00007000, "RO");
		this.ch7_aword_STATUS = ral_reg_aword_STATUS::type_id::create("ch7_aword_STATUS",, get_full_name());
		this.ch7_aword_STATUS.configure(this);
		this.ch7_aword_STATUS.build();
		default_map.add_reg(this.ch7_aword_STATUS, 32'h00007004, "RO");
		// ch7_aword.TIMING: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch7_aword_TIMING = ral_reg_aword_TIMING::type_id::create("ch7_aword_TIMING",, get_full_name());
		this.ch7_aword_TIMING.configure(this);
		this.ch7_aword_TIMING.build();
		default_map.add_reg(this.ch7_aword_TIMING, 32'h00007008, "RW");
		// ch7_aword.DRIVE: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch7_aword_DRIVE = ral_reg_aword_DRIVE::type_id::create("ch7_aword_DRIVE",, get_full_name());
		this.ch7_aword_DRIVE.configure(this);
		this.ch7_aword_DRIVE.build();
		default_map.add_reg(this.ch7_aword_DRIVE, 32'h0000700c, "RW");
		this.ch7_dword0_ID = ral_reg_dword_ID::type_id::create("ch7_dword0_ID",, get_full_name());
		this.ch7_dword0_ID.configure(this);
		this.ch7_dword0_ID.build();
		default_map.add_reg(this.ch7_dword0_ID, 32'h00007100, "RO");
		this.ch7_dword0_STATUS = ral_reg_dword_STATUS::type_id::create("ch7_dword0_STATUS",, get_full_name());
		this.ch7_dword0_STATUS.configure(this);
		this.ch7_dword0_STATUS.build();
		default_map.add_reg(this.ch7_dword0_STATUS, 32'h00007104, "RO");
		// ch7_dword0.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch7_dword0_VREF = ral_reg_dword_VREF::type_id::create("ch7_dword0_VREF",, get_full_name());
		this.ch7_dword0_VREF.configure(this);
		this.ch7_dword0_VREF.build();
		default_map.add_reg(this.ch7_dword0_VREF, 32'h00007108, "RW");
		// ch7_dword0.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch7_dword0_EQ = ral_reg_dword_EQ::type_id::create("ch7_dword0_EQ",, get_full_name());
		this.ch7_dword0_EQ.configure(this);
		this.ch7_dword0_EQ.build();
		default_map.add_reg(this.ch7_dword0_EQ, 32'h0000710c, "RW");
		this.ch7_dword1_ID = ral_reg_dword_ID::type_id::create("ch7_dword1_ID",, get_full_name());
		this.ch7_dword1_ID.configure(this);
		this.ch7_dword1_ID.build();
		default_map.add_reg(this.ch7_dword1_ID, 32'h00007200, "RO");
		this.ch7_dword1_STATUS = ral_reg_dword_STATUS::type_id::create("ch7_dword1_STATUS",, get_full_name());
		this.ch7_dword1_STATUS.configure(this);
		this.ch7_dword1_STATUS.build();
		default_map.add_reg(this.ch7_dword1_STATUS, 32'h00007204, "RO");
		// ch7_dword1.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch7_dword1_VREF = ral_reg_dword_VREF::type_id::create("ch7_dword1_VREF",, get_full_name());
		this.ch7_dword1_VREF.configure(this);
		this.ch7_dword1_VREF.build();
		default_map.add_reg(this.ch7_dword1_VREF, 32'h00007208, "RW");
		// ch7_dword1.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch7_dword1_EQ = ral_reg_dword_EQ::type_id::create("ch7_dword1_EQ",, get_full_name());
		this.ch7_dword1_EQ.configure(this);
		this.ch7_dword1_EQ.build();
		default_map.add_reg(this.ch7_dword1_EQ, 32'h0000720c, "RW");
		this.ch8_aword_ID = ral_reg_aword_ID::type_id::create("ch8_aword_ID",, get_full_name());
		this.ch8_aword_ID.configure(this);
		this.ch8_aword_ID.build();
		default_map.add_reg(this.ch8_aword_ID, 32'h00008000, "RO");
		this.ch8_aword_STATUS = ral_reg_aword_STATUS::type_id::create("ch8_aword_STATUS",, get_full_name());
		this.ch8_aword_STATUS.configure(this);
		this.ch8_aword_STATUS.build();
		default_map.add_reg(this.ch8_aword_STATUS, 32'h00008004, "RO");
		// ch8_aword.TIMING: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch8_aword_TIMING = ral_reg_aword_TIMING::type_id::create("ch8_aword_TIMING",, get_full_name());
		this.ch8_aword_TIMING.configure(this);
		this.ch8_aword_TIMING.build();
		default_map.add_reg(this.ch8_aword_TIMING, 32'h00008008, "RW");
		// ch8_aword.DRIVE: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch8_aword_DRIVE = ral_reg_aword_DRIVE::type_id::create("ch8_aword_DRIVE",, get_full_name());
		this.ch8_aword_DRIVE.configure(this);
		this.ch8_aword_DRIVE.build();
		default_map.add_reg(this.ch8_aword_DRIVE, 32'h0000800c, "RW");
		this.ch8_dword0_ID = ral_reg_dword_ID::type_id::create("ch8_dword0_ID",, get_full_name());
		this.ch8_dword0_ID.configure(this);
		this.ch8_dword0_ID.build();
		default_map.add_reg(this.ch8_dword0_ID, 32'h00008100, "RO");
		this.ch8_dword0_STATUS = ral_reg_dword_STATUS::type_id::create("ch8_dword0_STATUS",, get_full_name());
		this.ch8_dword0_STATUS.configure(this);
		this.ch8_dword0_STATUS.build();
		default_map.add_reg(this.ch8_dword0_STATUS, 32'h00008104, "RO");
		// ch8_dword0.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch8_dword0_VREF = ral_reg_dword_VREF::type_id::create("ch8_dword0_VREF",, get_full_name());
		this.ch8_dword0_VREF.configure(this);
		this.ch8_dword0_VREF.build();
		default_map.add_reg(this.ch8_dword0_VREF, 32'h00008108, "RW");
		// ch8_dword0.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch8_dword0_EQ = ral_reg_dword_EQ::type_id::create("ch8_dword0_EQ",, get_full_name());
		this.ch8_dword0_EQ.configure(this);
		this.ch8_dword0_EQ.build();
		default_map.add_reg(this.ch8_dword0_EQ, 32'h0000810c, "RW");
		this.ch8_dword1_ID = ral_reg_dword_ID::type_id::create("ch8_dword1_ID",, get_full_name());
		this.ch8_dword1_ID.configure(this);
		this.ch8_dword1_ID.build();
		default_map.add_reg(this.ch8_dword1_ID, 32'h00008200, "RO");
		this.ch8_dword1_STATUS = ral_reg_dword_STATUS::type_id::create("ch8_dword1_STATUS",, get_full_name());
		this.ch8_dword1_STATUS.configure(this);
		this.ch8_dword1_STATUS.build();
		default_map.add_reg(this.ch8_dword1_STATUS, 32'h00008204, "RO");
		// ch8_dword1.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch8_dword1_VREF = ral_reg_dword_VREF::type_id::create("ch8_dword1_VREF",, get_full_name());
		this.ch8_dword1_VREF.configure(this);
		this.ch8_dword1_VREF.build();
		default_map.add_reg(this.ch8_dword1_VREF, 32'h00008208, "RW");
		// ch8_dword1.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch8_dword1_EQ = ral_reg_dword_EQ::type_id::create("ch8_dword1_EQ",, get_full_name());
		this.ch8_dword1_EQ.configure(this);
		this.ch8_dword1_EQ.build();
		default_map.add_reg(this.ch8_dword1_EQ, 32'h0000820c, "RW");
		this.ch9_aword_ID = ral_reg_aword_ID::type_id::create("ch9_aword_ID",, get_full_name());
		this.ch9_aword_ID.configure(this);
		this.ch9_aword_ID.build();
		default_map.add_reg(this.ch9_aword_ID, 32'h00009000, "RO");
		this.ch9_aword_STATUS = ral_reg_aword_STATUS::type_id::create("ch9_aword_STATUS",, get_full_name());
		this.ch9_aword_STATUS.configure(this);
		this.ch9_aword_STATUS.build();
		default_map.add_reg(this.ch9_aword_STATUS, 32'h00009004, "RO");
		// ch9_aword.TIMING: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch9_aword_TIMING = ral_reg_aword_TIMING::type_id::create("ch9_aword_TIMING",, get_full_name());
		this.ch9_aword_TIMING.configure(this);
		this.ch9_aword_TIMING.build();
		default_map.add_reg(this.ch9_aword_TIMING, 32'h00009008, "RW");
		// ch9_aword.DRIVE: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch9_aword_DRIVE = ral_reg_aword_DRIVE::type_id::create("ch9_aword_DRIVE",, get_full_name());
		this.ch9_aword_DRIVE.configure(this);
		this.ch9_aword_DRIVE.build();
		default_map.add_reg(this.ch9_aword_DRIVE, 32'h0000900c, "RW");
		this.ch9_dword0_ID = ral_reg_dword_ID::type_id::create("ch9_dword0_ID",, get_full_name());
		this.ch9_dword0_ID.configure(this);
		this.ch9_dword0_ID.build();
		default_map.add_reg(this.ch9_dword0_ID, 32'h00009100, "RO");
		this.ch9_dword0_STATUS = ral_reg_dword_STATUS::type_id::create("ch9_dword0_STATUS",, get_full_name());
		this.ch9_dword0_STATUS.configure(this);
		this.ch9_dword0_STATUS.build();
		default_map.add_reg(this.ch9_dword0_STATUS, 32'h00009104, "RO");
		// ch9_dword0.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch9_dword0_VREF = ral_reg_dword_VREF::type_id::create("ch9_dword0_VREF",, get_full_name());
		this.ch9_dword0_VREF.configure(this);
		this.ch9_dword0_VREF.build();
		default_map.add_reg(this.ch9_dword0_VREF, 32'h00009108, "RW");
		// ch9_dword0.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch9_dword0_EQ = ral_reg_dword_EQ::type_id::create("ch9_dword0_EQ",, get_full_name());
		this.ch9_dword0_EQ.configure(this);
		this.ch9_dword0_EQ.build();
		default_map.add_reg(this.ch9_dword0_EQ, 32'h0000910c, "RW");
		this.ch9_dword1_ID = ral_reg_dword_ID::type_id::create("ch9_dword1_ID",, get_full_name());
		this.ch9_dword1_ID.configure(this);
		this.ch9_dword1_ID.build();
		default_map.add_reg(this.ch9_dword1_ID, 32'h00009200, "RO");
		this.ch9_dword1_STATUS = ral_reg_dword_STATUS::type_id::create("ch9_dword1_STATUS",, get_full_name());
		this.ch9_dword1_STATUS.configure(this);
		this.ch9_dword1_STATUS.build();
		default_map.add_reg(this.ch9_dword1_STATUS, 32'h00009204, "RO");
		// ch9_dword1.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch9_dword1_VREF = ral_reg_dword_VREF::type_id::create("ch9_dword1_VREF",, get_full_name());
		this.ch9_dword1_VREF.configure(this);
		this.ch9_dword1_VREF.build();
		default_map.add_reg(this.ch9_dword1_VREF, 32'h00009208, "RW");
		// ch9_dword1.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch9_dword1_EQ = ral_reg_dword_EQ::type_id::create("ch9_dword1_EQ",, get_full_name());
		this.ch9_dword1_EQ.configure(this);
		this.ch9_dword1_EQ.build();
		default_map.add_reg(this.ch9_dword1_EQ, 32'h0000920c, "RW");
		this.ch10_aword_ID = ral_reg_aword_ID::type_id::create("ch10_aword_ID",, get_full_name());
		this.ch10_aword_ID.configure(this);
		this.ch10_aword_ID.build();
		default_map.add_reg(this.ch10_aword_ID, 32'h0000a000, "RO");
		this.ch10_aword_STATUS = ral_reg_aword_STATUS::type_id::create("ch10_aword_STATUS",, get_full_name());
		this.ch10_aword_STATUS.configure(this);
		this.ch10_aword_STATUS.build();
		default_map.add_reg(this.ch10_aword_STATUS, 32'h0000a004, "RO");
		// ch10_aword.TIMING: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch10_aword_TIMING = ral_reg_aword_TIMING::type_id::create("ch10_aword_TIMING",, get_full_name());
		this.ch10_aword_TIMING.configure(this);
		this.ch10_aword_TIMING.build();
		default_map.add_reg(this.ch10_aword_TIMING, 32'h0000a008, "RW");
		// ch10_aword.DRIVE: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch10_aword_DRIVE = ral_reg_aword_DRIVE::type_id::create("ch10_aword_DRIVE",, get_full_name());
		this.ch10_aword_DRIVE.configure(this);
		this.ch10_aword_DRIVE.build();
		default_map.add_reg(this.ch10_aword_DRIVE, 32'h0000a00c, "RW");
		this.ch10_dword0_ID = ral_reg_dword_ID::type_id::create("ch10_dword0_ID",, get_full_name());
		this.ch10_dword0_ID.configure(this);
		this.ch10_dword0_ID.build();
		default_map.add_reg(this.ch10_dword0_ID, 32'h0000a100, "RO");
		this.ch10_dword0_STATUS = ral_reg_dword_STATUS::type_id::create("ch10_dword0_STATUS",, get_full_name());
		this.ch10_dword0_STATUS.configure(this);
		this.ch10_dword0_STATUS.build();
		default_map.add_reg(this.ch10_dword0_STATUS, 32'h0000a104, "RO");
		// ch10_dword0.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch10_dword0_VREF = ral_reg_dword_VREF::type_id::create("ch10_dword0_VREF",, get_full_name());
		this.ch10_dword0_VREF.configure(this);
		this.ch10_dword0_VREF.build();
		default_map.add_reg(this.ch10_dword0_VREF, 32'h0000a108, "RW");
		// ch10_dword0.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch10_dword0_EQ = ral_reg_dword_EQ::type_id::create("ch10_dword0_EQ",, get_full_name());
		this.ch10_dword0_EQ.configure(this);
		this.ch10_dword0_EQ.build();
		default_map.add_reg(this.ch10_dword0_EQ, 32'h0000a10c, "RW");
		this.ch10_dword1_ID = ral_reg_dword_ID::type_id::create("ch10_dword1_ID",, get_full_name());
		this.ch10_dword1_ID.configure(this);
		this.ch10_dword1_ID.build();
		default_map.add_reg(this.ch10_dword1_ID, 32'h0000a200, "RO");
		this.ch10_dword1_STATUS = ral_reg_dword_STATUS::type_id::create("ch10_dword1_STATUS",, get_full_name());
		this.ch10_dword1_STATUS.configure(this);
		this.ch10_dword1_STATUS.build();
		default_map.add_reg(this.ch10_dword1_STATUS, 32'h0000a204, "RO");
		// ch10_dword1.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch10_dword1_VREF = ral_reg_dword_VREF::type_id::create("ch10_dword1_VREF",, get_full_name());
		this.ch10_dword1_VREF.configure(this);
		this.ch10_dword1_VREF.build();
		default_map.add_reg(this.ch10_dword1_VREF, 32'h0000a208, "RW");
		// ch10_dword1.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch10_dword1_EQ = ral_reg_dword_EQ::type_id::create("ch10_dword1_EQ",, get_full_name());
		this.ch10_dword1_EQ.configure(this);
		this.ch10_dword1_EQ.build();
		default_map.add_reg(this.ch10_dword1_EQ, 32'h0000a20c, "RW");
		this.ch11_aword_ID = ral_reg_aword_ID::type_id::create("ch11_aword_ID",, get_full_name());
		this.ch11_aword_ID.configure(this);
		this.ch11_aword_ID.build();
		default_map.add_reg(this.ch11_aword_ID, 32'h0000b000, "RO");
		this.ch11_aword_STATUS = ral_reg_aword_STATUS::type_id::create("ch11_aword_STATUS",, get_full_name());
		this.ch11_aword_STATUS.configure(this);
		this.ch11_aword_STATUS.build();
		default_map.add_reg(this.ch11_aword_STATUS, 32'h0000b004, "RO");
		// ch11_aword.TIMING: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch11_aword_TIMING = ral_reg_aword_TIMING::type_id::create("ch11_aword_TIMING",, get_full_name());
		this.ch11_aword_TIMING.configure(this);
		this.ch11_aword_TIMING.build();
		default_map.add_reg(this.ch11_aword_TIMING, 32'h0000b008, "RW");
		// ch11_aword.DRIVE: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch11_aword_DRIVE = ral_reg_aword_DRIVE::type_id::create("ch11_aword_DRIVE",, get_full_name());
		this.ch11_aword_DRIVE.configure(this);
		this.ch11_aword_DRIVE.build();
		default_map.add_reg(this.ch11_aword_DRIVE, 32'h0000b00c, "RW");
		this.ch11_dword0_ID = ral_reg_dword_ID::type_id::create("ch11_dword0_ID",, get_full_name());
		this.ch11_dword0_ID.configure(this);
		this.ch11_dword0_ID.build();
		default_map.add_reg(this.ch11_dword0_ID, 32'h0000b100, "RO");
		this.ch11_dword0_STATUS = ral_reg_dword_STATUS::type_id::create("ch11_dword0_STATUS",, get_full_name());
		this.ch11_dword0_STATUS.configure(this);
		this.ch11_dword0_STATUS.build();
		default_map.add_reg(this.ch11_dword0_STATUS, 32'h0000b104, "RO");
		// ch11_dword0.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch11_dword0_VREF = ral_reg_dword_VREF::type_id::create("ch11_dword0_VREF",, get_full_name());
		this.ch11_dword0_VREF.configure(this);
		this.ch11_dword0_VREF.build();
		default_map.add_reg(this.ch11_dword0_VREF, 32'h0000b108, "RW");
		// ch11_dword0.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch11_dword0_EQ = ral_reg_dword_EQ::type_id::create("ch11_dword0_EQ",, get_full_name());
		this.ch11_dword0_EQ.configure(this);
		this.ch11_dword0_EQ.build();
		default_map.add_reg(this.ch11_dword0_EQ, 32'h0000b10c, "RW");
		this.ch11_dword1_ID = ral_reg_dword_ID::type_id::create("ch11_dword1_ID",, get_full_name());
		this.ch11_dword1_ID.configure(this);
		this.ch11_dword1_ID.build();
		default_map.add_reg(this.ch11_dword1_ID, 32'h0000b200, "RO");
		this.ch11_dword1_STATUS = ral_reg_dword_STATUS::type_id::create("ch11_dword1_STATUS",, get_full_name());
		this.ch11_dword1_STATUS.configure(this);
		this.ch11_dword1_STATUS.build();
		default_map.add_reg(this.ch11_dword1_STATUS, 32'h0000b204, "RO");
		// ch11_dword1.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch11_dword1_VREF = ral_reg_dword_VREF::type_id::create("ch11_dword1_VREF",, get_full_name());
		this.ch11_dword1_VREF.configure(this);
		this.ch11_dword1_VREF.build();
		default_map.add_reg(this.ch11_dword1_VREF, 32'h0000b208, "RW");
		// ch11_dword1.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch11_dword1_EQ = ral_reg_dword_EQ::type_id::create("ch11_dword1_EQ",, get_full_name());
		this.ch11_dword1_EQ.configure(this);
		this.ch11_dword1_EQ.build();
		default_map.add_reg(this.ch11_dword1_EQ, 32'h0000b20c, "RW");
		this.ch12_aword_ID = ral_reg_aword_ID::type_id::create("ch12_aword_ID",, get_full_name());
		this.ch12_aword_ID.configure(this);
		this.ch12_aword_ID.build();
		default_map.add_reg(this.ch12_aword_ID, 32'h0000c000, "RO");
		this.ch12_aword_STATUS = ral_reg_aword_STATUS::type_id::create("ch12_aword_STATUS",, get_full_name());
		this.ch12_aword_STATUS.configure(this);
		this.ch12_aword_STATUS.build();
		default_map.add_reg(this.ch12_aword_STATUS, 32'h0000c004, "RO");
		// ch12_aword.TIMING: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch12_aword_TIMING = ral_reg_aword_TIMING::type_id::create("ch12_aword_TIMING",, get_full_name());
		this.ch12_aword_TIMING.configure(this);
		this.ch12_aword_TIMING.build();
		default_map.add_reg(this.ch12_aword_TIMING, 32'h0000c008, "RW");
		// ch12_aword.DRIVE: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch12_aword_DRIVE = ral_reg_aword_DRIVE::type_id::create("ch12_aword_DRIVE",, get_full_name());
		this.ch12_aword_DRIVE.configure(this);
		this.ch12_aword_DRIVE.build();
		default_map.add_reg(this.ch12_aword_DRIVE, 32'h0000c00c, "RW");
		this.ch12_dword0_ID = ral_reg_dword_ID::type_id::create("ch12_dword0_ID",, get_full_name());
		this.ch12_dword0_ID.configure(this);
		this.ch12_dword0_ID.build();
		default_map.add_reg(this.ch12_dword0_ID, 32'h0000c100, "RO");
		this.ch12_dword0_STATUS = ral_reg_dword_STATUS::type_id::create("ch12_dword0_STATUS",, get_full_name());
		this.ch12_dword0_STATUS.configure(this);
		this.ch12_dword0_STATUS.build();
		default_map.add_reg(this.ch12_dword0_STATUS, 32'h0000c104, "RO");
		// ch12_dword0.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch12_dword0_VREF = ral_reg_dword_VREF::type_id::create("ch12_dword0_VREF",, get_full_name());
		this.ch12_dword0_VREF.configure(this);
		this.ch12_dword0_VREF.build();
		default_map.add_reg(this.ch12_dword0_VREF, 32'h0000c108, "RW");
		// ch12_dword0.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch12_dword0_EQ = ral_reg_dword_EQ::type_id::create("ch12_dword0_EQ",, get_full_name());
		this.ch12_dword0_EQ.configure(this);
		this.ch12_dword0_EQ.build();
		default_map.add_reg(this.ch12_dword0_EQ, 32'h0000c10c, "RW");
		this.ch12_dword1_ID = ral_reg_dword_ID::type_id::create("ch12_dword1_ID",, get_full_name());
		this.ch12_dword1_ID.configure(this);
		this.ch12_dword1_ID.build();
		default_map.add_reg(this.ch12_dword1_ID, 32'h0000c200, "RO");
		this.ch12_dword1_STATUS = ral_reg_dword_STATUS::type_id::create("ch12_dword1_STATUS",, get_full_name());
		this.ch12_dword1_STATUS.configure(this);
		this.ch12_dword1_STATUS.build();
		default_map.add_reg(this.ch12_dword1_STATUS, 32'h0000c204, "RO");
		// ch12_dword1.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch12_dword1_VREF = ral_reg_dword_VREF::type_id::create("ch12_dword1_VREF",, get_full_name());
		this.ch12_dword1_VREF.configure(this);
		this.ch12_dword1_VREF.build();
		default_map.add_reg(this.ch12_dword1_VREF, 32'h0000c208, "RW");
		// ch12_dword1.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch12_dword1_EQ = ral_reg_dword_EQ::type_id::create("ch12_dword1_EQ",, get_full_name());
		this.ch12_dword1_EQ.configure(this);
		this.ch12_dword1_EQ.build();
		default_map.add_reg(this.ch12_dword1_EQ, 32'h0000c20c, "RW");
		this.ch13_aword_ID = ral_reg_aword_ID::type_id::create("ch13_aword_ID",, get_full_name());
		this.ch13_aword_ID.configure(this);
		this.ch13_aword_ID.build();
		default_map.add_reg(this.ch13_aword_ID, 32'h0000d000, "RO");
		this.ch13_aword_STATUS = ral_reg_aword_STATUS::type_id::create("ch13_aword_STATUS",, get_full_name());
		this.ch13_aword_STATUS.configure(this);
		this.ch13_aword_STATUS.build();
		default_map.add_reg(this.ch13_aword_STATUS, 32'h0000d004, "RO");
		// ch13_aword.TIMING: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch13_aword_TIMING = ral_reg_aword_TIMING::type_id::create("ch13_aword_TIMING",, get_full_name());
		this.ch13_aword_TIMING.configure(this);
		this.ch13_aword_TIMING.build();
		default_map.add_reg(this.ch13_aword_TIMING, 32'h0000d008, "RW");
		// ch13_aword.DRIVE: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch13_aword_DRIVE = ral_reg_aword_DRIVE::type_id::create("ch13_aword_DRIVE",, get_full_name());
		this.ch13_aword_DRIVE.configure(this);
		this.ch13_aword_DRIVE.build();
		default_map.add_reg(this.ch13_aword_DRIVE, 32'h0000d00c, "RW");
		this.ch13_dword0_ID = ral_reg_dword_ID::type_id::create("ch13_dword0_ID",, get_full_name());
		this.ch13_dword0_ID.configure(this);
		this.ch13_dword0_ID.build();
		default_map.add_reg(this.ch13_dword0_ID, 32'h0000d100, "RO");
		this.ch13_dword0_STATUS = ral_reg_dword_STATUS::type_id::create("ch13_dword0_STATUS",, get_full_name());
		this.ch13_dword0_STATUS.configure(this);
		this.ch13_dword0_STATUS.build();
		default_map.add_reg(this.ch13_dword0_STATUS, 32'h0000d104, "RO");
		// ch13_dword0.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch13_dword0_VREF = ral_reg_dword_VREF::type_id::create("ch13_dword0_VREF",, get_full_name());
		this.ch13_dword0_VREF.configure(this);
		this.ch13_dword0_VREF.build();
		default_map.add_reg(this.ch13_dword0_VREF, 32'h0000d108, "RW");
		// ch13_dword0.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch13_dword0_EQ = ral_reg_dword_EQ::type_id::create("ch13_dword0_EQ",, get_full_name());
		this.ch13_dword0_EQ.configure(this);
		this.ch13_dword0_EQ.build();
		default_map.add_reg(this.ch13_dword0_EQ, 32'h0000d10c, "RW");
		this.ch13_dword1_ID = ral_reg_dword_ID::type_id::create("ch13_dword1_ID",, get_full_name());
		this.ch13_dword1_ID.configure(this);
		this.ch13_dword1_ID.build();
		default_map.add_reg(this.ch13_dword1_ID, 32'h0000d200, "RO");
		this.ch13_dword1_STATUS = ral_reg_dword_STATUS::type_id::create("ch13_dword1_STATUS",, get_full_name());
		this.ch13_dword1_STATUS.configure(this);
		this.ch13_dword1_STATUS.build();
		default_map.add_reg(this.ch13_dword1_STATUS, 32'h0000d204, "RO");
		// ch13_dword1.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch13_dword1_VREF = ral_reg_dword_VREF::type_id::create("ch13_dword1_VREF",, get_full_name());
		this.ch13_dword1_VREF.configure(this);
		this.ch13_dword1_VREF.build();
		default_map.add_reg(this.ch13_dword1_VREF, 32'h0000d208, "RW");
		// ch13_dword1.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch13_dword1_EQ = ral_reg_dword_EQ::type_id::create("ch13_dword1_EQ",, get_full_name());
		this.ch13_dword1_EQ.configure(this);
		this.ch13_dword1_EQ.build();
		default_map.add_reg(this.ch13_dword1_EQ, 32'h0000d20c, "RW");
		this.ch14_aword_ID = ral_reg_aword_ID::type_id::create("ch14_aword_ID",, get_full_name());
		this.ch14_aword_ID.configure(this);
		this.ch14_aword_ID.build();
		default_map.add_reg(this.ch14_aword_ID, 32'h0000e000, "RO");
		this.ch14_aword_STATUS = ral_reg_aword_STATUS::type_id::create("ch14_aword_STATUS",, get_full_name());
		this.ch14_aword_STATUS.configure(this);
		this.ch14_aword_STATUS.build();
		default_map.add_reg(this.ch14_aword_STATUS, 32'h0000e004, "RO");
		// ch14_aword.TIMING: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch14_aword_TIMING = ral_reg_aword_TIMING::type_id::create("ch14_aword_TIMING",, get_full_name());
		this.ch14_aword_TIMING.configure(this);
		this.ch14_aword_TIMING.build();
		default_map.add_reg(this.ch14_aword_TIMING, 32'h0000e008, "RW");
		// ch14_aword.DRIVE: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch14_aword_DRIVE = ral_reg_aword_DRIVE::type_id::create("ch14_aword_DRIVE",, get_full_name());
		this.ch14_aword_DRIVE.configure(this);
		this.ch14_aword_DRIVE.build();
		default_map.add_reg(this.ch14_aword_DRIVE, 32'h0000e00c, "RW");
		this.ch14_dword0_ID = ral_reg_dword_ID::type_id::create("ch14_dword0_ID",, get_full_name());
		this.ch14_dword0_ID.configure(this);
		this.ch14_dword0_ID.build();
		default_map.add_reg(this.ch14_dword0_ID, 32'h0000e100, "RO");
		this.ch14_dword0_STATUS = ral_reg_dword_STATUS::type_id::create("ch14_dword0_STATUS",, get_full_name());
		this.ch14_dword0_STATUS.configure(this);
		this.ch14_dword0_STATUS.build();
		default_map.add_reg(this.ch14_dword0_STATUS, 32'h0000e104, "RO");
		// ch14_dword0.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch14_dword0_VREF = ral_reg_dword_VREF::type_id::create("ch14_dword0_VREF",, get_full_name());
		this.ch14_dword0_VREF.configure(this);
		this.ch14_dword0_VREF.build();
		default_map.add_reg(this.ch14_dword0_VREF, 32'h0000e108, "RW");
		// ch14_dword0.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch14_dword0_EQ = ral_reg_dword_EQ::type_id::create("ch14_dword0_EQ",, get_full_name());
		this.ch14_dword0_EQ.configure(this);
		this.ch14_dword0_EQ.build();
		default_map.add_reg(this.ch14_dword0_EQ, 32'h0000e10c, "RW");
		this.ch14_dword1_ID = ral_reg_dword_ID::type_id::create("ch14_dword1_ID",, get_full_name());
		this.ch14_dword1_ID.configure(this);
		this.ch14_dword1_ID.build();
		default_map.add_reg(this.ch14_dword1_ID, 32'h0000e200, "RO");
		this.ch14_dword1_STATUS = ral_reg_dword_STATUS::type_id::create("ch14_dword1_STATUS",, get_full_name());
		this.ch14_dword1_STATUS.configure(this);
		this.ch14_dword1_STATUS.build();
		default_map.add_reg(this.ch14_dword1_STATUS, 32'h0000e204, "RO");
		// ch14_dword1.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch14_dword1_VREF = ral_reg_dword_VREF::type_id::create("ch14_dword1_VREF",, get_full_name());
		this.ch14_dword1_VREF.configure(this);
		this.ch14_dword1_VREF.build();
		default_map.add_reg(this.ch14_dword1_VREF, 32'h0000e208, "RW");
		// ch14_dword1.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch14_dword1_EQ = ral_reg_dword_EQ::type_id::create("ch14_dword1_EQ",, get_full_name());
		this.ch14_dword1_EQ.configure(this);
		this.ch14_dword1_EQ.build();
		default_map.add_reg(this.ch14_dword1_EQ, 32'h0000e20c, "RW");
		this.ch15_aword_ID = ral_reg_aword_ID::type_id::create("ch15_aword_ID",, get_full_name());
		this.ch15_aword_ID.configure(this);
		this.ch15_aword_ID.build();
		default_map.add_reg(this.ch15_aword_ID, 32'h0000f000, "RO");
		this.ch15_aword_STATUS = ral_reg_aword_STATUS::type_id::create("ch15_aword_STATUS",, get_full_name());
		this.ch15_aword_STATUS.configure(this);
		this.ch15_aword_STATUS.build();
		default_map.add_reg(this.ch15_aword_STATUS, 32'h0000f004, "RO");
		// ch15_aword.TIMING: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch15_aword_TIMING = ral_reg_aword_TIMING::type_id::create("ch15_aword_TIMING",, get_full_name());
		this.ch15_aword_TIMING.configure(this);
		this.ch15_aword_TIMING.build();
		default_map.add_reg(this.ch15_aword_TIMING, 32'h0000f008, "RW");
		// ch15_aword.DRIVE: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch15_aword_DRIVE = ral_reg_aword_DRIVE::type_id::create("ch15_aword_DRIVE",, get_full_name());
		this.ch15_aword_DRIVE.configure(this);
		this.ch15_aword_DRIVE.build();
		default_map.add_reg(this.ch15_aword_DRIVE, 32'h0000f00c, "RW");
		this.ch15_dword0_ID = ral_reg_dword_ID::type_id::create("ch15_dword0_ID",, get_full_name());
		this.ch15_dword0_ID.configure(this);
		this.ch15_dword0_ID.build();
		default_map.add_reg(this.ch15_dword0_ID, 32'h0000f100, "RO");
		this.ch15_dword0_STATUS = ral_reg_dword_STATUS::type_id::create("ch15_dword0_STATUS",, get_full_name());
		this.ch15_dword0_STATUS.configure(this);
		this.ch15_dword0_STATUS.build();
		default_map.add_reg(this.ch15_dword0_STATUS, 32'h0000f104, "RO");
		// ch15_dword0.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch15_dword0_VREF = ral_reg_dword_VREF::type_id::create("ch15_dword0_VREF",, get_full_name());
		this.ch15_dword0_VREF.configure(this);
		this.ch15_dword0_VREF.build();
		default_map.add_reg(this.ch15_dword0_VREF, 32'h0000f108, "RW");
		// ch15_dword0.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch15_dword0_EQ = ral_reg_dword_EQ::type_id::create("ch15_dword0_EQ",, get_full_name());
		this.ch15_dword0_EQ.configure(this);
		this.ch15_dword0_EQ.build();
		default_map.add_reg(this.ch15_dword0_EQ, 32'h0000f10c, "RW");
		this.ch15_dword1_ID = ral_reg_dword_ID::type_id::create("ch15_dword1_ID",, get_full_name());
		this.ch15_dword1_ID.configure(this);
		this.ch15_dword1_ID.build();
		default_map.add_reg(this.ch15_dword1_ID, 32'h0000f200, "RO");
		this.ch15_dword1_STATUS = ral_reg_dword_STATUS::type_id::create("ch15_dword1_STATUS",, get_full_name());
		this.ch15_dword1_STATUS.configure(this);
		this.ch15_dword1_STATUS.build();
		default_map.add_reg(this.ch15_dword1_STATUS, 32'h0000f204, "RO");
		// ch15_dword1.VREF: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch15_dword1_VREF = ral_reg_dword_VREF::type_id::create("ch15_dword1_VREF",, get_full_name());
		this.ch15_dword1_VREF.configure(this);
		this.ch15_dword1_VREF.build();
		default_map.add_reg(this.ch15_dword1_VREF, 32'h0000f208, "RW");
		// ch15_dword1.EQ: shadow pstate, 4 copies; bank select is fabric TGA (2 bit)
		this.ch15_dword1_EQ = ral_reg_dword_EQ::type_id::create("ch15_dword1_EQ",, get_full_name());
		this.ch15_dword1_EQ.configure(this);
		this.ch15_dword1_EQ.build();
		default_map.add_reg(this.ch15_dword1_EQ, 32'h0000f20c, "RW");
	endfunction: build

	`uvm_object_utils(ral_block_hbm)
endclass : ral_block_hbm

`endif // RAL_BLOCK_HBM_SV
