// Generated by autowire plugin wishbone. Do not edit.
// Packed uvm_reg: cell classes + ral_block maps.

`ifndef RAL_WISHBONE_SV
`define RAL_WISHBONE_SV

`include "regfile/ral_AWORD.sv"
`include "regfile/ral_CENTER.sv"
`include "regfile/ral_DWORD.sv"
`include "bus/ral_block_hbm_ch.sv"
`include "bus/ral_block_hbm.sv"

`endif
