// Generated by autowire plugin wishbone. Do not edit.
// Packed uvm_reg: cell classes + ral_block maps (not .ralf).

`ifndef RAL_WISHBONE_SV
`define RAL_WISHBONE_SV

`include "ral_AWORD.sv"
`include "ral_DWORD.sv"
`include "ral_block_hbm_ch.sv"
`include "ral_block_hbm.sv"

`endif
