// Generated by autowire plugin wishbone (table aword). Do not edit.
// uvm_reg: field layout only. Address map and shadow tag are packed with the bus.

`ifndef RAL_AWORD_SV
`define RAL_AWORD_SV

import uvm_pkg::*;
`include "uvm_macros.svh"

// Cell ID — Lane identity
class ral_reg_aword_ID extends uvm_reg;
	     uvm_reg_field magic  ; // bit [15:0]
	     uvm_reg_field version; // bit [31:16]

	function new(string name = "ral_reg_aword_ID");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.magic = uvm_reg_field::type_id::create("magic",, get_full_name());
		this.magic.configure(this, 16, 0, "RO", 0, 16'ha570, 1, 0, 0);
		this.version = uvm_reg_field::type_id::create("version",, get_full_name());
		this.version.configure(this, 16, 16, "RO", 0, 16'h1, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_aword_ID)
endclass : ral_reg_aword_ID

// Cell STATUS — Lane status
class ral_reg_aword_STATUS extends uvm_reg;
	     uvm_reg_field cal_done   ; // bit [0]
	     uvm_reg_field reserved_1 ; // bit [7:1]
	     uvm_reg_field err_code   ; // bit [15:8]
	     uvm_reg_field reserved_16; // bit [31:16]

	function new(string name = "ral_reg_aword_STATUS");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.cal_done = uvm_reg_field::type_id::create("cal_done",, get_full_name());
		this.cal_done.configure(this, 1, 0, "RO", 0, 1'h0, 1, 0, 0);
		this.reserved_1 = uvm_reg_field::type_id::create("reserved_1",, get_full_name());
		this.reserved_1.configure(this, 7, 1, "RO", 0, 7'h0, 1, 0, 0);
		this.err_code = uvm_reg_field::type_id::create("err_code",, get_full_name());
		this.err_code.configure(this, 8, 8, "RO", 0, 8'h0, 1, 0, 0);
		this.reserved_16 = uvm_reg_field::type_id::create("reserved_16",, get_full_name());
		this.reserved_16.configure(this, 16, 16, "RO", 0, 16'h0, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_aword_STATUS)
endclass : ral_reg_aword_STATUS

// Cell TIMING — Per-pstate command timing
// shadow: pstate, 4 copies (bank select is a bus TGA concern)
class ral_reg_aword_TIMING extends uvm_reg;
	rand uvm_reg_field trcd       ; // bit [7:0]
	rand uvm_reg_field trp        ; // bit [15:8]
	     uvm_reg_field reserved_16; // bit [31:16]

	function new(string name = "ral_reg_aword_TIMING");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.trcd = uvm_reg_field::type_id::create("trcd",, get_full_name());
		this.trcd.configure(this, 8, 0, "RW", 0, 8'hc, 1, 1, 0);
		this.trp = uvm_reg_field::type_id::create("trp",, get_full_name());
		this.trp.configure(this, 8, 8, "RW", 0, 8'hc, 1, 1, 0);
		this.reserved_16 = uvm_reg_field::type_id::create("reserved_16",, get_full_name());
		this.reserved_16.configure(this, 16, 16, "RO", 0, 16'h0, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_aword_TIMING)
endclass : ral_reg_aword_TIMING

// Cell DRIVE — Per-pstate output drive
// shadow: pstate, 4 copies (bank select is a bus TGA concern)
class ral_reg_aword_DRIVE extends uvm_reg;
	rand uvm_reg_field ca_drive  ; // bit [3:0]
	     uvm_reg_field reserved_4; // bit [31:4]

	function new(string name = "ral_reg_aword_DRIVE");
		super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		this.ca_drive = uvm_reg_field::type_id::create("ca_drive",, get_full_name());
		this.ca_drive.configure(this, 4, 0, "RW", 0, 4'h4, 1, 1, 0);
		this.reserved_4 = uvm_reg_field::type_id::create("reserved_4",, get_full_name());
		this.reserved_4.configure(this, 28, 4, "RO", 0, 28'h0, 1, 0, 0);
	endfunction: build

	`uvm_object_utils(ral_reg_aword_DRIVE)
endclass : ral_reg_aword_DRIVE

// Leaf block — aword: HBM aword CSR (command/address lane)
class ral_block_aword extends uvm_reg_block;
	rand ral_reg_aword_ID ID;
	rand ral_reg_aword_STATUS STATUS;
	rand ral_reg_aword_TIMING TIMING;
	rand ral_reg_aword_DRIVE DRIVE;

	function new(string name = "ral_block_aword");
		super.new(name, build_coverage(UVM_NO_COVERAGE));
	endfunction: new

	virtual function void build();
		default_map = create_map("default_map", 0, 4, UVM_LITTLE_ENDIAN);
		this.ID = ral_reg_aword_ID::type_id::create("ID",, get_full_name());
		this.ID.configure(this);
		this.ID.build();
		default_map.add_reg(this.ID, 32'h00000000, "RO");
		this.STATUS = ral_reg_aword_STATUS::type_id::create("STATUS",, get_full_name());
		this.STATUS.configure(this);
		this.STATUS.build();
		default_map.add_reg(this.STATUS, 32'h00000004, "RO");
		// TIMING: shadow: pstate, 4 copies (bank select is a bus TGA concern)
		this.TIMING = ral_reg_aword_TIMING::type_id::create("TIMING",, get_full_name());
		this.TIMING.configure(this);
		this.TIMING.build();
		default_map.add_reg(this.TIMING, 32'h00000008, "RW");
		// DRIVE: shadow: pstate, 4 copies (bank select is a bus TGA concern)
		this.DRIVE = ral_reg_aword_DRIVE::type_id::create("DRIVE",, get_full_name());
		this.DRIVE.configure(this);
		this.DRIVE.build();
		default_map.add_reg(this.DRIVE, 32'h0000000c, "RW");
	endfunction: build

	`uvm_object_utils(ral_block_aword)
endclass : ral_block_aword

`endif // RAL_AWORD_SV
