// Software exports from a laid-out wishbone-regfile: C bitfield layout and
// per-cell uvm_reg. Address map / TGA / shadow tag belong to wishbone-bus.

import {
	Access,
	accessRalName,
	accessRalRand,
	effectiveSheet,
	type FieldReset,
	type RegShadow,
} from "./dsl.ts";
import type { LaidCell, LaidRegfile } from "./layout.ts";

const CELL_BITS = 32;

export type PackedBit = {
	name: string;
	width: number;
	bit_offset: number;
	access: Access;
	desc: string;
	reset: number;
	reserved: boolean;
};

export function resetCopy0(r: FieldReset | undefined): number {
	if (r === undefined) return 0;
	if (typeof r === "number") return r;
	return r[0] ?? 0;
}

function ident(raw: string): string {
	let s = raw.replace(/[^A-Za-z0-9_]/g, "_");
	if (s.length === 0 || /^[0-9]/.test(s)) s = `_${s}`;
	return s;
}

function cFieldName(name: string, bitOffset: number): string {
	const base =
		name.toLowerCase() === "reserved" ? `reserved_${bitOffset}` : name;
	return ident(base).toUpperCase();
}

function svFieldName(name: string, bitOffset: number): string {
	const base =
		name.toLowerCase() === "reserved" ? `reserved_${bitOffset}` : name;
	return ident(base);
}

function bitRange(lo: number, width: number): string {
	const hi = lo + width - 1;
	return width === 1 ? `bit [${lo}]` : `bit [${hi}:${lo}]`;
}

export function fieldsWithReserved(cell: LaidCell): PackedBit[] {
	const sorted = [...cell.fields].sort((a, b) => a.bit_offset - b.bit_offset);
	const out: PackedBit[] = [];
	let cursor = 0;
	const pushReserved = (lo: number, width: number) => {
		out.push({
			name: "reserved",
			width,
			bit_offset: lo,
			access: Access.RO,
			desc: "reserved",
			reset: 0,
			reserved: true,
		});
	};
	for (const f of sorted) {
		if (cursor < f.bit_offset) pushReserved(cursor, f.bit_offset - cursor);
		out.push({
			name: f.field.name,
			width: f.field.width,
			bit_offset: f.bit_offset,
			access: f.field.access,
			desc: f.field.desc,
			reset: resetCopy0(f.field.reset),
			reserved: false,
		});
		cursor = f.bit_offset + f.field.width;
	}
	if (cursor < CELL_BITS) pushReserved(cursor, CELL_BITS - cursor);
	return out;
}

function shadowComment(
	cell: LaidCell,
	shadows: readonly RegShadow[],
): string | null {
	if (!cell.shadow) return null;
	const sh = shadows.find((s) => s.name === cell.shadow);
	const copies = sh?.copies;
	const n = copies !== undefined ? `, ${copies} copies` : "";
	return `shadow: ${cell.shadow}${n} (bank select is a bus TGA concern)`;
}

/** Field-layout identity for shared C/UVM (no instance name, no byte offset). */
export function swLayoutFingerprint(laid: LaidRegfile): string {
	return JSON.stringify(
		laid.cells.map((c) => ({
			name: c.name,
			shadow: c.shadow ?? null,
			fields: [...c.fields]
				.sort((a, b) => a.bit_offset - b.bit_offset)
				.map((f) => ({
					n: f.field.name,
					w: f.field.width,
					o: f.bit_offset,
					a: f.field.access,
					r: resetCopy0(f.field.reset),
				})),
		})),
	);
}

function stableHead(table: string, kind: "C header" | "uvm_reg"): string[] {
	return [
		`// Generated by autowire plugin wishbone (table ${table}). Do not edit.`,
		`// ${kind}: field layout only. Address map and shadow tag are packed with the bus.`,
	];
}

/** C: per-cell struct bitfields + union { all; bit }. No OFFSET_* / overlay. */
export function emitRegfileC(laid: LaidRegfile): string {
	const table = effectiveSheet(laid.def);
	const up = ident(table).toUpperCase();
	const guard = `${up}_REGFILE_H`;
	const lines: string[] = [
		...stableHead(table, "C header"),
		"",
		`#ifndef ${guard}`,
		`#define ${guard}`,
		"",
		"#include <stdint.h>",
		"",
	];
	for (const cell of laid.cells) {
		const bits = fieldsWithReserved(cell);
		const st = `${up}_${ident(cell.name).toUpperCase()}`;
		const namePad = Math.max(
			...bits.map((b) => cFieldName(b.name, b.bit_offset).length),
		);
		const sh = shadowComment(cell, laid.shadows);
		lines.push(`/* Cell ${cell.name} — ${cell.desc}`);
		if (sh) lines.push(`   ${sh}`);
		lines.push("*/");
		lines.push(`struct ${st}_BITS {`);
		for (const b of bits) {
			const fn = cFieldName(b.name, b.bit_offset).padEnd(namePad);
			const w = String(b.width).padStart(2);
			lines.push(
				`\tvolatile uint32_t ${fn} : ${w}; /* ${bitRange(b.bit_offset, b.width)} ${b.desc} */`,
			);
		}
		lines.push("};", "");
		lines.push(`union ${st} {`);
		lines.push("\tvolatile uint32_t all;");
		lines.push(`\tstruct ${st}_BITS bit;`);
		lines.push("};", "");
	}
	lines.push(`#endif /* ${guard} */`, "");
	return lines.join("\n");
}

/** uvm_reg: one class per cell. No ral_block / add_reg(offset). */
export function emitRegfileUvm(laid: LaidRegfile): string {
	const table = effectiveSheet(laid.def);
	const macro = `RAL_${ident(table).toUpperCase()}_SV`;
	const lines: string[] = [
		...stableHead(table, "uvm_reg"),
		"",
		`\`ifndef ${macro}`,
		`\`define ${macro}`,
		"",
		"import uvm_pkg::*;",
		'`include "uvm_macros.svh"',
		"",
	];
	for (const cell of laid.cells) {
		const bits = fieldsWithReserved(cell);
		const cls = `ral_reg_${ident(table)}_${ident(cell.name)}`;
		const namePad = Math.max(
			...bits.map((b) => svFieldName(b.name, b.bit_offset).length),
		);
		const sh = shadowComment(cell, laid.shadows);
		lines.push(`// Cell ${cell.name} — ${cell.desc}`);
		if (sh) lines.push(`// ${sh}`);
		lines.push(`class ${cls} extends uvm_reg;`);
		for (const b of bits) {
			const fn = svFieldName(b.name, b.bit_offset);
			const rand = accessRalRand(b.access) ? "rand " : "     ";
			lines.push(
				`\t${rand}uvm_reg_field ${fn.padEnd(namePad)}; // ${bitRange(b.bit_offset, b.width)}`,
			);
		}
		lines.push("");
		lines.push(`\tfunction new(string name = "${cls}");`);
		lines.push("\t\tsuper.new(name, 32, build_coverage(UVM_NO_COVERAGE));");
		lines.push("\tendfunction: new");
		lines.push("");
		lines.push("\tvirtual function void build();");
		for (const b of bits) {
			const fn = svFieldName(b.name, b.bit_offset);
			const acc = accessRalName(b.access);
			const rst = `${b.width}'h${b.reset.toString(16)}`;
			const isRand = accessRalRand(b.access) ? "1" : "0";
			lines.push(
				`\t\tthis.${fn} = uvm_reg_field::type_id::create("${fn}",, get_full_name());`,
			);
			lines.push(
				`\t\tthis.${fn}.configure(this, ${b.width}, ${b.bit_offset}, "${acc}", 0, ${rst}, 1, ${isRand}, 0);`,
			);
		}
		lines.push("\tendfunction: build");
		lines.push("");
		lines.push(`\t\`uvm_object_utils(${cls})`);
		lines.push(`endclass : ${cls}`);
		lines.push("");
	}
	lines.push(`\`endif // ${macro}`, "");
	return lines.join("\n");
}
