// Empty stand-in so typecheck can resolve the bundle module.
// scripts/pack-docs.ts overwrites it for a real build. The file stays untracked.

import { existsSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { join } from "node:path";

const path = join(import.meta.dir, "..", "src", "cli", "doc-pack.generated.ts");
if (!existsSync(path)) {
	await writeFile(
		path,
		'// Generated by scripts/pack-docs.ts. Do not edit.\nexport function docPackB64(): string {\n\treturn "";\n}\n',
	);
}
