// Build the zstd blob that ships inside autowire.js. Run before bun build.

import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { collectPackFiles, encodePack } from "../src/cli/pack.ts";

const root = join(import.meta.dir, "..");
const files = await collectPackFiles(root);
const packed = encodePack(files);
// Base64 inside a function body: the bundler hoists top-level consts into the
// entry scope (eager multi-MB string alloc + parse on every cold start). A
// function body stays lazily parsed until loadPack calls it. Byte-array
// literals are worse still (~1s of token parsing), so never emit
// Uint8Array.from([...]).
const body = `// Generated by scripts/pack-docs.ts. Do not edit.
export function docPackB64(): string {
	return ${JSON.stringify(Buffer.from(packed).toString("base64"))};
}
`;
await writeFile(join(root, "src", "cli", "doc-pack.generated.ts"), body);
console.log(`docs pack: ${files.length} files, ${packed.byteLength} bytes`);
