// Build the gzip blob that ships inside autowire.js. Run before bun build.

import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { collectPackFiles, encodePack } from "../src/cli/pack.ts";

const root = join(import.meta.dir, "..");
const files = await collectPackFiles(root);
const packed = encodePack(files);
const body = `// Generated by scripts/pack-docs.ts. Do not edit.
export const DOC_PACK = Uint8Array.from(${JSON.stringify([...packed])});
`;
await writeFile(join(root, "src", "cli", "doc-pack.generated.ts"), body);
console.log(`docs pack: ${files.length} files, ${packed.byteLength} bytes`);
