// Generated by autowire plugin wishbone-regfile (table sha256_wb). Do not edit.
// SHA256 Wishbone CSR leaf (hash RO + soft reset)
module sha256_wb_regfile (
	input  logic        i_clk,
	input  logic        i_rst_n,
	input  logic        i_wb_cyc,
	input  logic        i_wb_stb,
	input  logic        i_wb_we,
	input  logic [5:0]  i_wb_adr,
	input  logic [31:0] i_wb_dat,
	input  logic [3:0]  i_wb_sel,
	output logic        o_wb_ack,
	output logic [31:0] o_wb_dat,
	output logic        rg_soft_reset,
	output logic        p_rg_done_clear,
	input  logic        ro_busy,
	input  logic        ro_done,
	input  logic [31:0] ro_hash0,
	input  logic [31:0] ro_hash1,
	input  logic [31:0] ro_hash2,
	input  logic [31:0] ro_hash3,
	input  logic [31:0] ro_hash4,
	input  logic [31:0] ro_hash5,
	input  logic [31:0] ro_hash6,
	input  logic [31:0] ro_hash7
);

	logic        hit;
	logic        wr_fire;
	logic        rd_fire;
	logic        addr_hit_0;
	logic        wr_sel_0;
	logic        rd_sel_0;
	logic        addr_hit_4;
	logic        wr_sel_4;
	logic        rd_sel_4;
	logic        addr_hit_8;
	logic        wr_sel_8;
	logic        rd_sel_8;
	logic        addr_hit_c;
	logic        wr_sel_c;
	logic        rd_sel_c;
	logic        addr_hit_10;
	logic        wr_sel_10;
	logic        rd_sel_10;
	logic        addr_hit_14;
	logic        wr_sel_14;
	logic        rd_sel_14;
	logic        addr_hit_18;
	logic        wr_sel_18;
	logic        rd_sel_18;
	logic        addr_hit_1c;
	logic        wr_sel_1c;
	logic        rd_sel_1c;
	logic        addr_hit_20;
	logic        wr_sel_20;
	logic        rd_sel_20;
	logic        rg_soft_reset_q;
	logic [31:0] rd_data;

	// Addr: 0x0 RegCell: CTRL — Control / status
	assign addr_hit_0 = (i_wb_adr[5:2] == 4'd0);
	// Addr: 0x4 RegCell: HASH0 — Digest word 0
	assign addr_hit_4 = (i_wb_adr[5:2] == 4'd1);
	// Addr: 0x8 RegCell: HASH1 — Digest word 1
	assign addr_hit_8 = (i_wb_adr[5:2] == 4'd2);
	// Addr: 0xc RegCell: HASH2 — Digest word 2
	assign addr_hit_c = (i_wb_adr[5:2] == 4'd3);
	// Addr: 0x10 RegCell: HASH3 — Digest word 3
	assign addr_hit_10 = (i_wb_adr[5:2] == 4'd4);
	// Addr: 0x14 RegCell: HASH4 — Digest word 4
	assign addr_hit_14 = (i_wb_adr[5:2] == 4'd5);
	// Addr: 0x18 RegCell: HASH5 — Digest word 5
	assign addr_hit_18 = (i_wb_adr[5:2] == 4'd6);
	// Addr: 0x1c RegCell: HASH6 — Digest word 6
	assign addr_hit_1c = (i_wb_adr[5:2] == 4'd7);
	// Addr: 0x20 RegCell: HASH7 — Digest word 7
	assign addr_hit_20 = (i_wb_adr[5:2] == 4'd8);

	assign hit = |{
		addr_hit_0,
		addr_hit_4,
		addr_hit_8,
		addr_hit_c,
		addr_hit_10,
		addr_hit_14,
		addr_hit_18,
		addr_hit_1c,
		addr_hit_20
	};
	assign wr_fire = i_wb_cyc && i_wb_stb &&  i_wb_we;
	assign rd_fire = i_wb_cyc && i_wb_stb && ~i_wb_we;

	assign wr_sel_0 = wr_fire && hit && addr_hit_0;
	assign rd_sel_0 = rd_fire && hit && addr_hit_0;
	assign wr_sel_4 = wr_fire && hit && addr_hit_4;
	assign rd_sel_4 = rd_fire && hit && addr_hit_4;
	assign wr_sel_8 = wr_fire && hit && addr_hit_8;
	assign rd_sel_8 = rd_fire && hit && addr_hit_8;
	assign wr_sel_c = wr_fire && hit && addr_hit_c;
	assign rd_sel_c = rd_fire && hit && addr_hit_c;
	assign wr_sel_10 = wr_fire && hit && addr_hit_10;
	assign rd_sel_10 = rd_fire && hit && addr_hit_10;
	assign wr_sel_14 = wr_fire && hit && addr_hit_14;
	assign rd_sel_14 = rd_fire && hit && addr_hit_14;
	assign wr_sel_18 = wr_fire && hit && addr_hit_18;
	assign rd_sel_18 = rd_fire && hit && addr_hit_18;
	assign wr_sel_1c = wr_fire && hit && addr_hit_1c;
	assign rd_sel_1c = rd_fire && hit && addr_hit_1c;
	assign wr_sel_20 = wr_fire && hit && addr_hit_20;
	assign rd_sel_20 = rd_fire && hit && addr_hit_20;

	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) rg_soft_reset_q <= 1'h0;
		else if (wr_sel_0) rg_soft_reset_q <= i_wb_dat[0:0];
	end
	assign rg_soft_reset = rg_soft_reset_q;
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) p_rg_done_clear <= 1'h0;
		else p_rg_done_clear <= wr_sel_0 ? i_wb_dat[1:1] : 1'h0;
	end
	always_comb begin
		rd_data = 32'h0;
		unique case (1'b1)
			rd_sel_0: begin
				rd_data = 32'h0;
				rd_data[0:0] = rg_soft_reset_q;
				rd_data[1:1] = 1'h0;
				rd_data[8:8] = ro_busy;
				rd_data[9:9] = ro_done;
			end
			rd_sel_4: begin
				rd_data = 32'h0;
				rd_data[31:0] = ro_hash0;
			end
			rd_sel_8: begin
				rd_data = 32'h0;
				rd_data[31:0] = ro_hash1;
			end
			rd_sel_c: begin
				rd_data = 32'h0;
				rd_data[31:0] = ro_hash2;
			end
			rd_sel_10: begin
				rd_data = 32'h0;
				rd_data[31:0] = ro_hash3;
			end
			rd_sel_14: begin
				rd_data = 32'h0;
				rd_data[31:0] = ro_hash4;
			end
			rd_sel_18: begin
				rd_data = 32'h0;
				rd_data[31:0] = ro_hash5;
			end
			rd_sel_1c: begin
				rd_data = 32'h0;
				rd_data[31:0] = ro_hash6;
			end
			rd_sel_20: begin
				rd_data = 32'h0;
				rd_data[31:0] = ro_hash7;
			end
			default: rd_data = 32'h0;
		endcase
	end

	assign o_wb_ack = i_wb_cyc && i_wb_stb && hit;
	assign o_wb_dat = rd_data;

endmodule
