// SPDX-License-Identifier: MIT
//
// sha256_wb_regs.v
//
// Wishbone + AXI4-Stream front-end for zynq_sha256. CSR map is generated by
// wishbone-regfile from regs/sha256_wb.ts → sha256_wb_regfile.sv; this wrapper
// keeps stream glue, sticky done (HW set / SW clear via p_rg_done_clear), and
// legacy port names expected by connect/sha256wb.html.
//
// Register map (byte ADR, 0x00..0x20):
//   0x00 CTRL  bit0 soft_reset(RW) bit1 done_clear(W1P)
//              bit8 busy(RO) bit9 done(RO sticky)
//   0x04..0x20 hash0..hash7 (RO)

`timescale 1ns / 1ps
`default_nettype none

module sha256_wb_regs (
	input wire clk,
	input wire rst_ni,

	// Wishbone slave (legacy names; mapped onto generated i_wb_*)
	input  wire        i_wb_cyc,
	input  wire        i_wb_stb,
	input  wire        i_wb_we,
	input  wire [31:0] i_wb_addr,
	input  wire [31:0] i_wb_data,
	input  wire [3:0]  i_wb_sel,
	output wire        o_wb_ack,
	output wire [31:0] o_wb_data,

	// AXI4-Stream slave (payload from the SD read DMA)
	input  wire [31:0] s_axis_tdata,
	input  wire        s_axis_tvalid,
	output wire        s_axis_tready,
	input  wire        s_axis_tlast,

	// sha256 core handshake
	output wire        o_dat_valid,
	output wire [31:0] o_dat_lsb,
	output wire        o_core_rst_n,
	input  wire        i_hash_busy,
	input  wire        i_irq_finish,
	input  wire [31:0] i_hash0,
	input  wire [31:0] i_hash1,
	input  wire [31:0] i_hash2,
	input  wire [31:0] i_hash3,
	input  wire [31:0] i_hash4,
	input  wire [31:0] i_hash5,
	input  wire [31:0] i_hash6,
	input  wire [31:0] i_hash7,

	output wire o_irq
);

	wire        rg_soft_reset;
	wire        p_rg_done_clear;
	reg         done_sticky;

	assign o_irq        = done_sticky;
	assign o_core_rst_n = rst_ni & ~rg_soft_reset;

	// Stream front-end (was sha256_stream_v1_0_S00_AXIS)
	assign s_axis_tready = ~i_hash_busy & ~rg_soft_reset & rst_ni;
	assign o_dat_valid   = s_axis_tvalid & s_axis_tready;
	assign o_dat_lsb     = s_axis_tdata;

	// Sticky done: HW sets on finish; SW clears via CTRL.done_clear (W1P)
	always @(posedge clk or negedge rst_ni) begin
		if (!rst_ni)
			done_sticky <= 1'b0;
		else begin
			if (i_irq_finish)
				done_sticky <= 1'b1;
			if (p_rg_done_clear)
				done_sticky <= 1'b0;
		end
	end

	sha256_wb_regfile u_csr (
		.i_clk           (clk),
		.i_rst_n         (rst_ni),
		.i_wb_cyc        (i_wb_cyc),
		.i_wb_stb        (i_wb_stb),
		.i_wb_we         (i_wb_we),
		.i_wb_adr        (i_wb_addr[5:0]),
		.i_wb_dat        (i_wb_data),
		.i_wb_sel        (i_wb_sel),
		.o_wb_ack        (o_wb_ack),
		.o_wb_dat        (o_wb_data),
		.rg_soft_reset   (rg_soft_reset),
		.p_rg_done_clear (p_rg_done_clear),
		.ro_busy         (i_hash_busy),
		.ro_done         (done_sticky),
		.ro_hash0        (i_hash0),
		.ro_hash1        (i_hash1),
		.ro_hash2        (i_hash2),
		.ro_hash3        (i_hash3),
		.ro_hash4        (i_hash4),
		.ro_hash5        (i_hash5),
		.ro_hash6        (i_hash6),
		.ro_hash7        (i_hash7)
	);

	// s_axis_tlast is intentionally unused: the sha256 core frames by count
	wire unused = s_axis_tlast;

endmodule

`default_nettype wire
