// Generated by autowire plugin wishbone-regfile (table smoke). Do not edit.
// SoC regfile smoke bank (RC/RO/RW/RWW/RWE/W1P/W1C/shadow/wide)
module smoke_regfile (
	input  logic        i_clk,
	input  logic        i_rst_n,
	input  logic        i_wb_cyc,
	input  logic        i_wb_stb,
	input  logic        i_wb_we,
	input  logic [11:0] i_wb_adr,
	input  logic [31:0] i_wb_dat,
	input  logic [3:0]  i_wb_sel,
	input  logic [1:0]  i_wb_tga,
	output logic        o_wb_ack,
	output logic [31:0] o_wb_dat,
	input  logic        ro_busy,
	input  logic [7:0]  ro_code,
	output logic        rg_enable,
	output logic [2:0]  rg_mode,
	output logic [15:0] rg_capture,
	input  logic        rg_capture_strb,
	input  logic [15:0] rg_capture_hwdata,
	input  logic [31:0] ext_data,
	output logic [31:0] ext_data_wdata,
	output logic        ext_data_wren,
	output logic        ext_data_rden,
	output logic        ext_data_rst,
	input  logic        ext_data_ready,
	output logic        p_rg_go,
	output logic        c_rg_sticky,
	output logic [7:0]  rg_cfg,
	output logic [1:0]  o_bank_sel,
	output logic [31:0] rg_key_0,
	output logic [31:0] rg_key_1,
	output logic [31:0] rg_key_2
);

	logic        hit;
	logic        wr_fire;
	logic        rd_fire;
	logic        addr_hit_0;
	logic        wr_sel_0;
	logic        rd_sel_0;
	logic        addr_hit_4;
	logic        wr_sel_4;
	logic        rd_sel_4;
	logic        addr_hit_8;
	logic        wr_sel_8;
	logic        rd_sel_8;
	logic        addr_hit_c;
	logic        wr_sel_c;
	logic        rd_sel_c;
	logic        addr_hit_10;
	logic        wr_sel_10;
	logic        rd_sel_10;
	logic        addr_hit_14;
	logic        wr_sel_14;
	logic        rd_sel_14;
	logic        addr_hit_18;
	logic        wr_sel_18;
	logic        rd_sel_18;
	logic        addr_hit_1c;
	logic        wr_sel_1c;
	logic        rd_sel_1c;
	logic        addr_hit_20;
	logic        wr_sel_20;
	logic        rd_sel_20;
	logic        addr_hit_24;
	logic        wr_sel_24;
	logic        rd_sel_24;
	logic        addr_hit_28;
	logic        wr_sel_28;
	logic        rd_sel_28;
	logic [1:0]  raw_bank;
	logic [3:0]  mask_bank;
	logic        rg_enable_q;
	logic [2:0]  rg_mode_q;
	logic [15:0] rg_capture_q;
	logic        c_rg_sticky_q;
	logic [7:0]  rg_cfg_q [4];
	logic [31:0] rg_key_0_q;
	logic [31:0] rg_key_1_q;
	logic [31:0] rg_key_2_q;
	logic [31:0] rd_data;

	// Addr: 0x0 RegCell: ID — RC identity
	assign addr_hit_0 = (i_wb_adr[11:2] == 10'd0);
	// Addr: 0x4 RegCell: STATUS — RO status
	assign addr_hit_4 = (i_wb_adr[11:2] == 10'd1);
	// Addr: 0x8 RegCell: CFG — RW config
	assign addr_hit_8 = (i_wb_adr[11:2] == 10'd2);
	// Addr: 0xc RegCell: FEED — RWW capture
	assign addr_hit_c = (i_wb_adr[11:2] == 10'd3);
	// Addr: 0x10 RegCell: FIFO — RWE window
	assign addr_hit_10 = (i_wb_adr[11:2] == 10'd4);
	// Addr: 0x14 RegCell: CMD — W1P pulse
	assign addr_hit_14 = (i_wb_adr[11:2] == 10'd5);
	// Addr: 0x18 RegCell: IRQ — W1C sticky
	assign addr_hit_18 = (i_wb_adr[11:2] == 10'd6);
	// Addr: 0x1c RegCell: BANK — Shadowed RW
	assign addr_hit_1c = (i_wb_adr[11:2] == 10'd7);
	// Addr: 0x20 RegCell: key_key_0 — 96-bit key
	assign addr_hit_20 = (i_wb_adr[11:2] == 10'd8);
	// Addr: 0x24 RegCell: key_key_1 — 96-bit key
	assign addr_hit_24 = (i_wb_adr[11:2] == 10'd9);
	// Addr: 0x28 RegCell: key_key_2 — 96-bit key
	assign addr_hit_28 = (i_wb_adr[11:2] == 10'd10);

	assign hit = |{
		addr_hit_0,
		addr_hit_4,
		addr_hit_8,
		addr_hit_c,
		addr_hit_10,
		addr_hit_14,
		addr_hit_18,
		addr_hit_1c,
		addr_hit_20,
		addr_hit_24,
		addr_hit_28
	};
	assign wr_fire = i_wb_cyc && i_wb_stb &&  i_wb_we;
	assign rd_fire = i_wb_cyc && i_wb_stb && ~i_wb_we;

	assign wr_sel_0 = wr_fire && hit && addr_hit_0;
	assign rd_sel_0 = rd_fire && hit && addr_hit_0;
	assign wr_sel_4 = wr_fire && hit && addr_hit_4;
	assign rd_sel_4 = rd_fire && hit && addr_hit_4;
	assign wr_sel_8 = wr_fire && hit && addr_hit_8;
	assign rd_sel_8 = rd_fire && hit && addr_hit_8;
	assign wr_sel_c = wr_fire && hit && addr_hit_c;
	assign rd_sel_c = rd_fire && hit && addr_hit_c;
	assign wr_sel_10 = wr_fire && hit && addr_hit_10;
	assign rd_sel_10 = rd_fire && hit && addr_hit_10;
	assign wr_sel_14 = wr_fire && hit && addr_hit_14;
	assign rd_sel_14 = rd_fire && hit && addr_hit_14;
	assign wr_sel_18 = wr_fire && hit && addr_hit_18;
	assign rd_sel_18 = rd_fire && hit && addr_hit_18;
	assign wr_sel_1c = wr_fire && hit && addr_hit_1c;
	assign rd_sel_1c = rd_fire && hit && addr_hit_1c;
	assign wr_sel_20 = wr_fire && hit && addr_hit_20;
	assign rd_sel_20 = rd_fire && hit && addr_hit_20;
	assign wr_sel_24 = wr_fire && hit && addr_hit_24;
	assign rd_sel_24 = rd_fire && hit && addr_hit_24;
	assign wr_sel_28 = wr_fire && hit && addr_hit_28;
	assign rd_sel_28 = rd_fire && hit && addr_hit_28;

	assign raw_bank = i_wb_tga[1:0];
	always_comb begin
		mask_bank = 4'h0;
		if (raw_bank < 4) mask_bank = 4'd1 << raw_bank;
	end
	// one-hot mask → bin index (first set bit); miss keeps 0
	always_comb begin
		o_bank_sel = 2'd0;
		for (int __i = 0; __i < 4; __i++) begin
			if (mask_bank[__i]) o_bank_sel = 2'(__i);
		end
	end

	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) rg_enable_q <= 1'h0;
		else if (wr_sel_8) rg_enable_q <= i_wb_dat[0:0];
	end
	assign rg_enable = rg_enable_q;
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) rg_mode_q <= 3'h1;
		else if (wr_sel_8) rg_mode_q <= i_wb_dat[10:8];
	end
	assign rg_mode = rg_mode_q;
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) rg_capture_q <= 16'h0;
		else if (wr_sel_c) rg_capture_q <= i_wb_dat[15:0];
		else if (rg_capture_strb) rg_capture_q <= rg_capture_hwdata;
	end
	assign rg_capture = rg_capture_q;
	assign ext_data_wdata = i_wb_dat[31:0];
	assign ext_data_wren  = wr_sel_10;
	assign ext_data_rden  = rd_sel_10;
	assign ext_data_rst   = ~i_rst_n;
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) p_rg_go <= 1'h0;
		else p_rg_go <= wr_sel_14 ? i_wb_dat[0:0] : 1'h0;
	end
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) c_rg_sticky_q <= 1'h0;
		else if (wr_sel_18) c_rg_sticky_q <= c_rg_sticky_q & ~i_wb_dat[0:0];
	end
	assign c_rg_sticky = c_rg_sticky_q;
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) begin
			rg_cfg_q[0] <= 8'h10;
			rg_cfg_q[1] <= 8'h20;
			rg_cfg_q[2] <= 8'h30;
			rg_cfg_q[3] <= 8'h40;
		end else begin
			if (wr_sel_1c) begin
				for (int __c = 0; __c < 4; __c++) begin
					if (mask_bank[__c]) rg_cfg_q[__c] <= i_wb_dat[7:0];
				end
			end
		end
	end
	assign rg_cfg = rg_cfg_q[o_bank_sel];
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) rg_key_0_q <= 32'h0;
		else if (wr_sel_20) rg_key_0_q <= i_wb_dat[31:0];
	end
	assign rg_key_0 = rg_key_0_q;
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) rg_key_1_q <= 32'h0;
		else if (wr_sel_24) rg_key_1_q <= i_wb_dat[31:0];
	end
	assign rg_key_1 = rg_key_1_q;
	always_ff @(posedge i_clk or negedge i_rst_n) begin
		if (!i_rst_n) rg_key_2_q <= 32'h0;
		else if (wr_sel_28) rg_key_2_q <= i_wb_dat[31:0];
	end
	assign rg_key_2 = rg_key_2_q;
	always_comb begin
		rd_data = 32'h0;
		unique case (1'b1)
			rd_sel_0: begin
				rd_data = 32'h0;
				rd_data[15:0] = 16'ha55a;
				rd_data[31:16] = 16'h1;
			end
			rd_sel_4: begin
				rd_data = 32'h0;
				rd_data[0:0] = ro_busy;
				rd_data[15:8] = ro_code;
			end
			rd_sel_8: begin
				rd_data = 32'h0;
				rd_data[0:0] = rg_enable_q;
				rd_data[10:8] = rg_mode_q;
			end
			rd_sel_c: begin
				rd_data = 32'h0;
				rd_data[15:0] = rg_capture_q;
			end
			rd_sel_10: begin
				rd_data = 32'h0;
				rd_data[31:0] = ext_data;
			end
			rd_sel_14: begin
				rd_data = 32'h0;
				rd_data[0:0] = 1'h0;
			end
			rd_sel_18: begin
				rd_data = 32'h0;
				rd_data[0:0] = c_rg_sticky_q;
			end
			rd_sel_1c: begin
				rd_data = 32'h0;
				begin
					logic [7:0] __v;
					__v = 8'h0;
					for (int __c = 0; __c < 4; __c++) begin
						if (mask_bank[__c]) __v |= rg_cfg_q[__c];
					end
					rd_data[7:0] = __v;
				end
			end
			rd_sel_20: begin
				rd_data = 32'h0;
				rd_data[31:0] = rg_key_0_q;
			end
			rd_sel_24: begin
				rd_data = 32'h0;
				rd_data[31:0] = rg_key_1_q;
			end
			rd_sel_28: begin
				rd_data = 32'h0;
				rd_data[31:0] = rg_key_2_q;
			end
			default: rd_data = 32'h0;
		endcase
	end

	assign o_wb_ack = i_wb_cyc && i_wb_stb && hit && !(((wr_sel_10 || rd_sel_10) && !ext_data_ready));
	assign o_wb_dat = rd_data;

endmodule
