// Generated by autowire plugin wishbone (sd_sha). Do not edit.
// SV package: one window per TagFromAddr alias, plus broadcast windows.
// Field bit/mask localparams live in each regfile package.

`ifndef SD_SHA_MAP_PKG_SV
`define SD_SHA_MAP_PKG_SV
package sd_sha_map_pkg;

	localparam logic [31:0] SHA256_BASE = 32'h00000040;

	localparam logic [31:0] SHA256_CTRL_OFFSET = 32'h00000000;
	localparam logic [31:0] SHA256_HASH0_OFFSET = 32'h00000004;
	localparam logic [31:0] SHA256_HASH1_OFFSET = 32'h00000008;
	localparam logic [31:0] SHA256_HASH2_OFFSET = 32'h0000000c;
	localparam logic [31:0] SHA256_HASH3_OFFSET = 32'h00000010;
	localparam logic [31:0] SHA256_HASH4_OFFSET = 32'h00000014;
	localparam logic [31:0] SHA256_HASH5_OFFSET = 32'h00000018;
	localparam logic [31:0] SHA256_HASH6_OFFSET = 32'h0000001c;
	localparam logic [31:0] SHA256_HASH7_OFFSET = 32'h00000020;

	localparam logic [31:0] SHA256_CTRL = SHA256_BASE + SHA256_CTRL_OFFSET;
	localparam logic [31:0] SHA256_HASH0 = SHA256_BASE + SHA256_HASH0_OFFSET;
	localparam logic [31:0] SHA256_HASH1 = SHA256_BASE + SHA256_HASH1_OFFSET;
	localparam logic [31:0] SHA256_HASH2 = SHA256_BASE + SHA256_HASH2_OFFSET;
	localparam logic [31:0] SHA256_HASH3 = SHA256_BASE + SHA256_HASH3_OFFSET;
	localparam logic [31:0] SHA256_HASH4 = SHA256_BASE + SHA256_HASH4_OFFSET;
	localparam logic [31:0] SHA256_HASH5 = SHA256_BASE + SHA256_HASH5_OFFSET;
	localparam logic [31:0] SHA256_HASH6 = SHA256_BASE + SHA256_HASH6_OFFSET;
	localparam logic [31:0] SHA256_HASH7 = SHA256_BASE + SHA256_HASH7_OFFSET;

endpackage : sd_sha_map_pkg
`endif // SD_SHA_MAP_PKG_SV
