// Software map from a BusDef that attaches RegfileDef leaves.
// Leaf C / uvm_reg stay field-layout only; this file adds window + cell offset.

import { Access, effectiveSheet } from "../wishbone-regfile/dsl.ts";
import type { LaidCell, LaidRegfile } from "../wishbone-regfile/layout.ts";
import { layoutRegfile } from "../wishbone-regfile/layout.ts";
import type { BusDef, WbSlave } from "./dsl.ts";

function ident(raw: string): string {
	let s = raw.replace(/[^A-Za-z0-9_]/g, "_");
	if (s.length === 0 || /^[0-9]/.test(s)) s = `_${s}`;
	return s;
}

function hexU(n: number): string {
	return `0x${n.toString(16).padStart(8, "0")}u`;
}

function hexSv(n: number): string {
	return `32'h${n.toString(16).padStart(8, "0")}`;
}

export function attachedSlaves(def: BusDef): WbSlave[] {
	return def.slaves.filter((s) => s.regfile !== undefined);
}

/** Direct + nested `SlaveRegfile` hangs, with parent-window bases and prefixed ids. */
export function mapHangsDeep(def: BusDef): WbSlave[] {
	const out: WbSlave[] = [];
	const walk = (bus: BusDef, absBase: number, prefix: string): void => {
		for (const slave of bus.slaves) {
			const name = prefix ? `${prefix}${slave.name}` : slave.name;
			const base = (absBase + slave.base) >>> 0;
			if (slave.regfile) {
				out.push({ ...slave, name, base });
			}
			if (slave.bus) walk(slave.bus, base, `${name}_`);
		}
	};
	walk(def, 0, "");
	return out;
}

export function busMapHeaderName(def: BusDef): string {
	return `${def.name.toLowerCase()}_map.h`;
}

export function busRalBlockName(def: BusDef): string {
	return `ral_block_${ident(def.name)}`;
}

type Hang = {
	slave: WbSlave;
	laid: LaidRegfile;
	sheet: string;
	sheetUp: string;
};

function hangsOf(def: BusDef): Hang[] {
	const out: Hang[] = [];
	for (const slave of mapHangsDeep(def)) {
		const rf = slave.regfile;
		if (!rf) continue;
		const laid = layoutRegfile(rf);
		const sheet = effectiveSheet(rf);
		out.push({
			slave,
			laid,
			sheet,
			sheetUp: ident(sheet).toUpperCase(),
		});
	}
	return out;
}

function unionName(sheetUp: string, cell: LaidCell): string {
	return `${sheetUp}_${ident(cell.name).toUpperCase()}`;
}

function offsetMacro(busUp: string, sheetUp: string, cell: LaidCell): string {
	return `${busUp}_${sheetUp}_${ident(cell.name).toUpperCase()}_OFFSET`;
}

function baseMacro(busUp: string, slave: string): string {
	return `${busUp}_${ident(slave).toUpperCase()}_BASE`;
}

function absMacro(busUp: string, slave: string, cell: LaidCell): string {
	return `${busUp}_${ident(slave).toUpperCase()}_${ident(cell.name).toUpperCase()}`;
}

function shadowNote(cell: LaidCell, laid: LaidRegfile): string | null {
	if (!cell.shadow) return null;
	const sh = laid.shadows.find((s) => s.name === cell.shadow);
	const copies = sh?.copies;
	const tag = laid.tga_width;
	const n = copies !== undefined ? `, ${copies} copies` : "";
	return `shadow ${cell.shadow}${n}; bank select is fabric TGA (${tag} bit)`;
}

/** C: BASE / OFFSET / absolute cell macros + packed overlay per hang. */
export function emitBusMapC(def: BusDef): string {
	const hangs = hangsOf(def);
	const busUp = ident(def.name).toUpperCase();
	const guard = `${busUp}_MAP_H`;
	const lines: string[] = [
		`// Generated by autowire plugin wishbone (${def.name}). Do not edit.`,
		"// Software map: Slave window + cell byte offset. Field layout is packed beside this header.",
		"",
		`#ifndef ${guard}`,
		`#define ${guard}`,
		"",
		"#include <stdint.h>",
		"",
	];
	const sheets = [...new Set(hangs.map((h) => h.sheet))];
	for (const sh of sheets) {
		lines.push(`#include "${sh}.h"`);
	}
	if (sheets.length > 0) lines.push("");

	for (const h of hangs) {
		lines.push(
			`#define ${baseMacro(busUp, h.slave.name)} ${hexU(h.slave.base)}`,
		);
	}
	if (hangs.length > 0) lines.push("");

	const offsetSeen = new Set<string>();
	for (const h of hangs) {
		for (const cell of h.laid.cells) {
			const mac = offsetMacro(busUp, h.sheetUp, cell);
			if (offsetSeen.has(mac)) continue;
			offsetSeen.add(mac);
			lines.push(`#define ${mac} ${hexU(cell.byte_offset)}`);
		}
	}
	if (offsetSeen.size > 0) lines.push("");

	for (const h of hangs) {
		for (const cell of h.laid.cells) {
			const sh = shadowNote(cell, h.laid);
			const comment = sh ? ` /* ${sh} */` : "";
			lines.push(
				`#define ${absMacro(busUp, h.slave.name, cell)} (${baseMacro(busUp, h.slave.name)} + ${offsetMacro(busUp, h.sheetUp, cell)})${comment}`,
			);
		}
		lines.push("");
	}

	for (const h of hangs) {
		const st = ident(`${def.name}_${h.slave.name}`).toLowerCase();
		const cells = [...h.laid.cells].sort(
			(a, b) => a.byte_offset - b.byte_offset,
		);
		lines.push(
			`/* Overlay ${h.slave.name} @ ${hexU(h.slave.base)} (${h.sheet}) */`,
		);
		lines.push(`struct ${st} {`);
		let cursor = 0;
		let res = 0;
		for (const cell of cells) {
			while (cursor < cell.byte_offset) {
				lines.push(`\tvolatile uint32_t reserved_${res};`);
				res += 1;
				cursor += 4;
			}
			const sh = shadowNote(cell, h.laid);
			const cmt = sh
				? ` /* +${hexU(cell.byte_offset)} ${sh} */`
				: ` /* +${hexU(cell.byte_offset)} */`;
			lines.push(
				`\tunion ${unionName(h.sheetUp, cell)} ${ident(cell.name).toLowerCase()};${cmt}`,
			);
			cursor = cell.byte_offset + 4;
		}
		lines.push("};", "");
	}

	lines.push(`#endif /* ${guard} */`, "");
	return lines.join("\n");
}

function ralRegClass(sheet: string, cell: LaidCell): string {
	return `ral_reg_${ident(sheet)}_${ident(cell.name)}`;
}

function ralFile(sheet: string): string {
	return `ral_${ident(sheet).toUpperCase()}.sv`;
}

function accessHint(cell: LaidCell): string {
	const acc = cell.fields.map((f) => f.field.access);
	if (acc.every((a) => a === Access.RO || a === Access.RC)) return "RO";
	return "RW";
}

/** uvm_reg_block: one map, add_reg at Slave.base + cell offset. */
export function emitBusMapUvm(def: BusDef): string {
	const hangs = hangsOf(def);
	const block = busRalBlockName(def);
	const macro = `${ident(block).toUpperCase()}_SV`;
	const lines: string[] = [
		`// Generated by autowire plugin wishbone (${def.name}). Do not edit.`,
		"// uvm_reg_block map: Slave.base + cell offset. Cell classes are packed beside this file.",
		"",
		`\`ifndef ${macro}`,
		`\`define ${macro}`,
		"",
		"import uvm_pkg::*;",
		'`include "uvm_macros.svh"',
		"",
	];
	const files = [...new Set(hangs.map((h) => ralFile(h.sheet)))];
	for (const f of files) {
		lines.push(`\`include "${f}"`);
	}
	if (files.length > 0) lines.push("");

	lines.push(`class ${block} extends uvm_reg_block;`);
	for (const h of hangs) {
		for (const cell of h.laid.cells) {
			const inst = `${ident(h.slave.name)}_${ident(cell.name)}`;
			lines.push(`\trand ${ralRegClass(h.sheet, cell)} ${inst};`);
		}
	}
	lines.push("");
	lines.push(`\tfunction new(string name = "${block}");`);
	lines.push("\t\tsuper.new(name, build_coverage(UVM_NO_COVERAGE));");
	lines.push("\tendfunction: new");
	lines.push("");
	lines.push("\tvirtual function void build();");
	lines.push(
		'\t\tdefault_map = create_map("default_map", 0, 4, UVM_LITTLE_ENDIAN);',
	);
	for (const h of hangs) {
		for (const cell of h.laid.cells) {
			const inst = `${ident(h.slave.name)}_${ident(cell.name)}`;
			const cls = ralRegClass(h.sheet, cell);
			const off = hexSv(h.slave.base + cell.byte_offset);
			const acc = accessHint(cell);
			const sh = shadowNote(cell, h.laid);
			if (sh) lines.push(`\t\t// ${h.slave.name}.${cell.name}: ${sh}`);
			lines.push(
				`\t\tthis.${inst} = ${cls}::type_id::create("${inst}",, get_full_name());`,
			);
			lines.push(`\t\tthis.${inst}.configure(this);`);
			lines.push(`\t\tthis.${inst}.build();`);
			lines.push(`\t\tdefault_map.add_reg(this.${inst}, ${off}, "${acc}");`);
		}
	}
	lines.push("\tendfunction: build");
	lines.push("");
	lines.push(`\t\`uvm_object_utils(${block})`);
	lines.push(`endclass : ${block}`);
	lines.push("");
	lines.push(`\`endif // ${macro}`, "");
	return lines.join("\n");
}
