// Software map from a BusDef.
// C and uvm_reg name every TagFromAddr alias and every broadcast window.
// Only the uvm_reg model is generated (no RALF); field classes stay in the
// regfile emit.

import { REGFILE_DIR } from "../wishbone/id.ts";
import { effectiveSheet } from "../wishbone-regfile/dsl.ts";
import type { LaidCell, LaidRegfile } from "../wishbone-regfile/layout.ts";
import { layoutRegfile } from "../wishbone-regfile/layout.ts";
import type { BusDef, WbSlave } from "./dsl.ts";
import {
	broadcastNodes,
	type MapNode,
	mapTree,
	regfileNodes,
} from "./sw-map.ts";

function ident(raw: string): string {
	let s = raw.replace(/[^A-Za-z0-9_]/g, "_");
	if (s.length === 0 || /^[0-9]/.test(s)) s = `_${s}`;
	return s;
}

function hexU(n: number): string {
	return `0x${(n >>> 0).toString(16).padStart(8, "0")}u`;
}

function hexSv(n: number): string {
	return `32'h${(n >>> 0).toString(16).padStart(8, "0")}`;
}

/** Direct + nested regfile hangs. Shadow copies are separate hangs. */
export function mapHangsDeep(def: BusDef): WbSlave[] {
	return regfileNodes(def).map((node) => ({
		...node.slave,
		name: node.name,
		base: node.base,
	}));
}

export function attachedSlaves(def: BusDef): WbSlave[] {
	return def.slaves.filter((s) => s.regfile !== undefined);
}

export function busMapHeaderName(def: BusDef): string {
	return `${def.name.toLowerCase()}_map.h`;
}

export function busRalBlockName(def: BusDef): string {
	return `ral_block_${ident(def.name)}`;
}

type Hang = {
	node: MapNode;
	laid: LaidRegfile;
	sheet: string;
	sheetUp: string;
};

function hangsOf(def: BusDef): Hang[] {
	const out: Hang[] = [];
	for (const node of regfileNodes(def)) {
		const rf = node.slave.regfile;
		if (!rf || !node.regfile) continue;
		const sheet = node.sheet ?? effectiveSheet(rf);
		out.push({
			node,
			laid: node.regfile ?? layoutRegfile(rf),
			sheet,
			sheetUp: ident(sheet).toUpperCase(),
		});
	}
	return out;
}

function unionName(sheetUp: string, cell: LaidCell): string {
	return `${sheetUp}_${ident(cell.name).toUpperCase()}`;
}

function offsetMacro(busUp: string, sheetUp: string, cell: LaidCell): string {
	return `${busUp}_${sheetUp}_${ident(cell.name).toUpperCase()}_OFFSET`;
}

function baseMacro(busUp: string, slave: string): string {
	return `${busUp}_${ident(slave).toUpperCase()}_BASE`;
}

function absMacro(busUp: string, slave: string, cell: LaidCell): string {
	return `${busUp}_${ident(slave).toUpperCase()}_${ident(cell.name).toUpperCase()}`;
}

function shadowLabel(node: MapNode): string | null {
	if (node.shadows.length === 0) return null;
	return node.shadows.map((s) => `${s.domain}=${s.copy}`).join(", ");
}

function cellNote(cell: LaidCell, laid: LaidRegfile): string | null {
	if (!cell.shadow) return null;
	const sh = laid.shadows.find((s) => s.name === cell.shadow);
	const copies = sh?.copies;
	const n = copies !== undefined ? `, ${copies} copies` : "";
	return `cell shadow ${cell.shadow}${n}; selected by the address alias, not by a second offset`;
}

function broadcastComment(node: MapNode): string {
	const name = node.slave.broadcast;
	return `broadcast ${name}: one write at this window hits every subscriber`;
}

/** C: BASE / OFFSET / absolute cell macros, broadcast windows, packed overlay. */
export function emitBusMapC(def: BusDef): string {
	const hangs = hangsOf(def);
	const bcasts = broadcastNodes(def);
	const busUp = ident(def.name).toUpperCase();
	const guard = `${busUp}_MAP_H`;
	const lines: string[] = [
		`// Generated by autowire plugin wishbone (${def.name}). Do not edit.`,
		"// Software map: one window per TagFromAddr alias, plus broadcast windows.",
		"// A child that only passes a tag through is not split again.",
		"",
		`#ifndef ${guard}`,
		`#define ${guard}`,
		"",
		"#include <stdint.h>",
		"",
	];
	const sheets = [...new Set(hangs.map((h) => h.sheet))];
	for (const sh of sheets) lines.push(`#include "../${REGFILE_DIR}/${sh}.h"`);
	if (sheets.length > 0) lines.push("");

	for (const h of hangs) {
		const sh = shadowLabel(h.node);
		const cmt = sh ? ` /* ${sh} */` : "";
		lines.push(
			`#define ${baseMacro(busUp, h.node.name)} ${hexU(h.node.base)}${cmt}`,
		);
	}
	for (const b of bcasts) {
		const sh = shadowLabel(b);
		const extra = sh ? `; ${sh}` : "";
		lines.push(
			`#define ${baseMacro(busUp, b.name)} ${hexU(b.base)} /* ${broadcastComment(b)}${extra} */`,
		);
	}
	if (hangs.length > 0 || bcasts.length > 0) lines.push("");

	const offsetSeen = new Set<string>();
	for (const h of hangs) {
		for (const cell of h.laid.cells) {
			const mac = offsetMacro(busUp, h.sheetUp, cell);
			if (offsetSeen.has(mac)) continue;
			offsetSeen.add(mac);
			lines.push(`#define ${mac} ${hexU(cell.byte_offset)}`);
		}
	}
	if (offsetSeen.size > 0) lines.push("");

	for (const h of hangs) {
		const fixed = shadowLabel(h.node);
		for (const cell of h.laid.cells) {
			const notes = [fixed, cellNote(cell, h.laid)].filter(
				(s): s is string => s !== null,
			);
			const comment = notes.length > 0 ? ` /* ${notes.join("; ")} */` : "";
			lines.push(
				`#define ${absMacro(busUp, h.node.name, cell)} (${baseMacro(busUp, h.node.name)} + ${offsetMacro(busUp, h.sheetUp, cell)})${comment}`,
			);
		}
		lines.push("");
	}

	for (const h of hangs) {
		const st = ident(`${def.name}_${h.node.name}`).toLowerCase();
		const cells = [...h.laid.cells].sort(
			(a, b) => a.byte_offset - b.byte_offset,
		);
		const fixed = shadowLabel(h.node);
		lines.push(
			`/* Overlay ${h.node.name} @ ${hexU(h.node.base)} (${h.sheet}${fixed ? `; ${fixed}` : ""}) */`,
		);
		lines.push(`struct ${st} {`);
		let cursor = 0;
		let res = 0;
		for (const cell of cells) {
			while (cursor < cell.byte_offset) {
				lines.push(`\tvolatile uint32_t reserved_${res};`);
				res += 1;
				cursor += 4;
			}
			const note = cellNote(cell, h.laid);
			const cmt = note
				? ` /* +${hexU(cell.byte_offset)} ${note} */`
				: ` /* +${hexU(cell.byte_offset)} */`;
			lines.push(
				`\tunion ${unionName(h.sheetUp, cell)} ${ident(cell.name).toLowerCase()};${cmt}`,
			);
			cursor = cell.byte_offset + 4;
		}
		lines.push("};", "");
	}

	lines.push(`#endif /* ${guard} */`, "");
	return lines.join("\n");
}

function ralFile(sheet: string): string {
	return `ral_${ident(sheet).toUpperCase()}.sv`;
}

/** uvm_reg_block: sub-blocks per child bus, one leaf-block submap per regfile hang. */
export function emitBusMapUvm(def: BusDef): string {
	const block = busRalBlockName(def);
	const macro = `${ident(block).toUpperCase()}_SV`;
	const tree = mapTree(def);
	const hangs = hangsOf(def);
	const lines: string[] = [
		`// Generated by autowire plugin wishbone (${def.name}). Do not edit.`,
		"// uvm_reg_block: one sub-block per child bus, one leaf block per regfile hang.",
		"// TagFromAddr aliases are separate submap instances; broadcast windows are comments (no frontdoor).",
		"",
		`\`ifndef ${macro}`,
		`\`define ${macro}`,
		"",
		"import uvm_pkg::*;",
		'`include "uvm_macros.svh"',
		"",
	];
	const files = [...new Set(hangs.map((h) => ralFile(h.sheet)))];
	for (const f of files) lines.push(`\`include "../${REGFILE_DIR}/${f}"`);
	if (files.length > 0) lines.push("");

	const childBuses = childBusNames(tree);
	for (const name of childBuses) {
		lines.push(`\`include "${busRalBlockNameOf(name)}.sv"`);
	}
	if (childBuses.length > 0) lines.push("");

	lines.push(`class ${block} extends uvm_reg_block;`);
	for (const node of tree) {
		if (node.slave.bus) {
			lines.push(
				`\trand ${busRalBlockNameOf(node.slave.bus.name)} ${ident(node.name)};`,
			);
		}
	}
	for (const h of hangs.filter((h) => isDirect(tree, h.node))) {
		lines.push(`\trand ral_block_${ident(h.sheet)} ${ident(h.node.name)};`);
	}
	lines.push("");
	lines.push(`\tfunction new(string name = "${block}");`);
	lines.push("\t\tsuper.new(name, build_coverage(UVM_NO_COVERAGE));");
	lines.push("\tendfunction: new");
	lines.push("");
	lines.push("\tvirtual function void build();");
	lines.push(
		'\t\tdefault_map = create_map("default_map", 0, 4, UVM_LITTLE_ENDIAN);',
	);
	for (const b of broadcastNodes(def).filter((n) => isDirect(tree, n))) {
		lines.push(`\t\t// ${b.name} @ ${hexSv(b.base)}: ${broadcastComment(b)}`);
	}
	for (const node of tree) {
		if (!node.slave.bus) continue;
		const inst = ident(node.name);
		const cls = busRalBlockNameOf(node.slave.bus.name);
		const sh = shadowLabel(node);
		if (sh) lines.push(`\t\t// ${node.name}: ${sh}`);
		lines.push(
			`\t\tthis.${inst} = ${cls}::type_id::create("${inst}",, get_full_name());`,
		);
		lines.push(`\t\tthis.${inst}.configure(this, "");`);
		lines.push(`\t\tthis.${inst}.build();`);
		lines.push(
			`\t\tdefault_map.add_submap(this.${inst}.default_map, ${hexSv(node.base)});`,
		);
	}
	for (const h of hangs.filter((h) => isDirect(tree, h.node))) {
		const inst = ident(h.node.name);
		const cls = `ral_block_${ident(h.sheet)}`;
		const sh = shadowLabel(h.node);
		if (sh) lines.push(`\t\t// ${inst}: ${sh}`);
		lines.push(
			`\t\tthis.${inst} = ${cls}::type_id::create("${inst}",, get_full_name());`,
		);
		lines.push(`\t\tthis.${inst}.configure(this, "");`);
		lines.push(`\t\tthis.${inst}.build();`);
		lines.push(
			`\t\tdefault_map.add_submap(this.${inst}.default_map, ${hexSv(h.node.base)});`,
		);
	}
	lines.push("\tendfunction: build");
	lines.push("");
	lines.push(`\t\`uvm_object_utils(${block})`);
	lines.push(`endclass : ${block}`);
	lines.push("");
	lines.push(`\`endif // ${macro}`, "");
	return lines.join("\n");
}

function busRalBlockNameOf(busName: string): string {
	return `ral_block_${ident(busName)}`;
}

function childBusNames(nodes: readonly MapNode[]): string[] {
	const names: string[] = [];
	for (const node of nodes) {
		const name = node.slave.bus?.name;
		if (name && !names.includes(name)) names.push(name);
	}
	return names;
}

function isDirect(roots: readonly MapNode[], node: MapNode): boolean {
	return roots.some((r) => r.name === node.name);
}
