// wishbone fabric SV + Type-A wrapper. Packed software lives in
// src/plugins/wishbone/generate.ts.

import { mkdir } from "node:fs/promises";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import type { WorkspaceConfig } from "../../workspace.ts";
import { PLUGIN_ID } from "../wishbone/id.ts";
import { type BusDef, isBusDef } from "./dsl.ts";
import { busModuleName, busSystemModuleName, emitBusSv } from "./emit.ts";
import { emitBusSystemSv } from "./emit-attach.ts";
import { emitBusIcl, emitBusPdl, MASTER_MODULES } from "./emit-master.ts";

export { PLUGIN_ID };

export async function loadBusDef(
	tsPath: string,
	exportName: string,
): Promise<BusDef> {
	const abs = resolve(tsPath);
	const mod = (await import(pathToFileURL(abs).href)) as Record<
		string,
		unknown
	>;
	const v = mod[exportName];
	if (v === undefined) {
		throw new Error(`wishbone: export "${exportName}" not found in ${abs}`);
	}
	if (!isBusDef(v)) {
		throw new Error(`wishbone: export "${exportName}" is not a BusDef`);
	}
	if (v.name !== exportName) {
		throw new Error(
			`wishbone: BusDef.name "${v.name}" must equal export "${exportName}"`,
		);
	}
	return v;
}

export const PIPE_MODULE = "wb_cfg_pipe";
async function writeTemplateModule(
	outDir: string,
	mod: string,
): Promise<string> {
	const template = `docs/plugins/rtl/${mod}_template.sv`;
	const body = await Bun.file(
		join(import.meta.dir, "../../..", template),
	).text();
	const outPath = join(outDir, `${mod}.sv`);
	await Bun.write(
		outPath,
		`// Generated by autowire plugin wishbone (${mod}). Do not edit.\n` +
			`// Template: ${template}\n` +
			body,
	);
	return outPath;
}

export async function generatePipeModule(outDir: string): Promise<string> {
	return writeTemplateModule(outDir, PIPE_MODULE);
}

/** Shared master-face modules (sync cell, CDC, APB / JTAG bridges). */
export async function generateMasterModules(outDir: string): Promise<string[]> {
	const paths: string[] = [];
	for (const mod of MASTER_MODULES) {
		paths.push(await writeTemplateModule(outDir, mod));
	}
	return paths;
}

export async function generateDef(
	ws: WorkspaceConfig,
	def: BusDef,
): Promise<string[]> {
	const sv = emitBusSv(def);
	const outDir = join(ws.pluginsDir, PLUGIN_ID);
	await mkdir(outDir, { recursive: true });
	const paths: string[] = [];
	const outPath = join(outDir, `${busModuleName(def)}.sv`);
	await Bun.write(outPath, sv);
	paths.push(outPath);
	const wrap = emitBusSystemSv(def);
	if (wrap) {
		const wrapPath = join(outDir, `${busSystemModuleName(def)}.sv`);
		await Bun.write(wrapPath, wrap);
		paths.push(wrapPath);
	}
	const icl = emitBusIcl(def);
	const pdl = emitBusPdl(def);
	if (icl && pdl) {
		const stem = join(outDir, busSystemModuleName(def));
		await Bun.write(`${stem}.icl`, icl);
		await Bun.write(`${stem}.pdl`, pdl);
		paths.push(`${stem}.icl`, `${stem}.pdl`);
	}
	return paths;
}
