// wishbone fabric SV + Type-A wrapper. Packed software lives in
// src/plugins/wishbone/generate.ts.

import { mkdir } from "node:fs/promises";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { writeIfChanged } from "../../core/write.ts";
import type { WorkspaceConfig } from "../../workspace.ts";
import { BUS_DIR, PLUGIN_ID } from "../wishbone/id.ts";
import { type BusDef, isBusDef } from "./dsl.ts";
import { busModuleName, busSystemModuleName, emitBusSv } from "./emit.ts";
import { emitBusSystemSv } from "./emit-attach.ts";
import { emitBusIcl, emitBusPdl, MASTER_MODULES } from "./emit-master.ts";

export { PLUGIN_ID };

export async function loadBusDef(
	tsPath: string,
	exportName: string,
): Promise<BusDef> {
	const abs = resolve(tsPath);
	const mod = (await import(pathToFileURL(abs).href)) as Record<
		string,
		unknown
	>;
	const v = mod[exportName];
	if (v === undefined) {
		throw new Error(`wishbone: export "${exportName}" not found in ${abs}`);
	}
	if (!isBusDef(v)) {
		throw new Error(`wishbone: export "${exportName}" is not a BusDef`);
	}
	if (v.name !== exportName) {
		throw new Error(
			`wishbone: BusDef.name "${v.name}" must equal export "${exportName}"`,
		);
	}
	return v;
}

export const PIPE_MODULE = "wb_cfg_pipe";
async function writeTemplateModule(
	outDir: string,
	mod: string,
	force = false,
): Promise<string | null> {
	const template = `docs/plugins/rtl/${mod}_template.sv`;
	const outPath = join(outDir, `${mod}.sv`);
	const body =
		`// Generated by autowire plugin wishbone (${mod}). Do not edit.\n` +
		`// Template: ${template}\n` +
		(await Bun.file(join(import.meta.dir, "../../..", template)).text());
	return (await writeIfChanged(outPath, body, force)) ? outPath : null;
}

export async function generatePipeModule(
	outDir: string,
	force = false,
): Promise<string | null> {
	return writeTemplateModule(outDir, PIPE_MODULE, force);
}

/** Shared master-face modules (sync cell, CDC, APB / JTAG bridges). */
export async function generateMasterModules(
	outDir: string,
	force = false,
): Promise<string[]> {
	const paths: string[] = [];
	for (const mod of MASTER_MODULES) {
		const path = await writeTemplateModule(outDir, mod, force);
		if (path) paths.push(path);
	}
	return paths;
}

export async function generateDef(
	ws: WorkspaceConfig,
	def: BusDef,
	force = false,
): Promise<string[]> {
	const sv = emitBusSv(def);
	const outDir = join(ws.pluginsDir, PLUGIN_ID, BUS_DIR);
	await mkdir(outDir, { recursive: true });
	const paths: string[] = [];
	const outPath = join(outDir, `${busModuleName(def)}.sv`);
	if (await writeIfChanged(outPath, sv, force)) paths.push(outPath);
	const wrap = emitBusSystemSv(def);
	if (wrap) {
		const wrapPath = join(outDir, `${busSystemModuleName(def)}.sv`);
		if (await writeIfChanged(wrapPath, wrap, force)) paths.push(wrapPath);
	}
	const icl = emitBusIcl(def);
	const pdl = emitBusPdl(def);
	if (icl && pdl) {
		const stem = join(outDir, busSystemModuleName(def));
		if (await writeIfChanged(`${stem}.icl`, icl, force))
			paths.push(`${stem}.icl`);
		if (await writeIfChanged(`${stem}.pdl`, pdl, force))
			paths.push(`${stem}.pdl`);
	}
	return paths;
}
