// Generated by autowire plugin wishbone (table sha256). Do not edit.
// SV package: field layout only. Address map and shadow tag are packed with the bus.

`ifndef SHA256_PKG_SV
`define SHA256_PKG_SV
package sha256_pkg;

	// Cell CTRL — Control / status
	localparam int unsigned CTRL_SOFT_RESET_LSB   = 0;
	localparam int unsigned CTRL_SOFT_RESET_WIDTH = 1;
	localparam logic [31:0] CTRL_SOFT_RESET_MASK  = 32'h00000001;
	localparam logic [31:0] CTRL_SOFT_RESET_RESET = 32'h00000000; // RW bit [0] Soft reset hash core
	localparam int unsigned CTRL_DONE_CLEAR_LSB   = 1;
	localparam int unsigned CTRL_DONE_CLEAR_WIDTH = 1;
	localparam logic [31:0] CTRL_DONE_CLEAR_MASK  = 32'h00000002;
	localparam logic [31:0] CTRL_DONE_CLEAR_RESET = 32'h00000000; // W1P bit [1] Write 1 → pulse; glue clears sticky done
	localparam int unsigned CTRL_BUSY_LSB   = 8;
	localparam int unsigned CTRL_BUSY_WIDTH = 1;
	localparam logic [31:0] CTRL_BUSY_MASK  = 32'h00000100;
	localparam logic [31:0] CTRL_BUSY_RESET = 32'h00000000; // RO bit [8] Hash core busy
	localparam int unsigned CTRL_DONE_LSB   = 9;
	localparam int unsigned CTRL_DONE_WIDTH = 1;
	localparam logic [31:0] CTRL_DONE_MASK  = 32'h00000200;
	localparam logic [31:0] CTRL_DONE_RESET = 32'h00000000; // RO bit [9] Sticky done (from glue)

	// Cell HASH0 — Digest word 0
	localparam int unsigned HASH0_HASH0_LSB   = 0;
	localparam int unsigned HASH0_HASH0_WIDTH = 32;
	localparam logic [31:0] HASH0_HASH0_MASK  = 32'hffffffff;
	localparam logic [31:0] HASH0_HASH0_RESET = 32'h00000000; // RO bit [31:0] hash0

	// Cell HASH1 — Digest word 1
	localparam int unsigned HASH1_HASH1_LSB   = 0;
	localparam int unsigned HASH1_HASH1_WIDTH = 32;
	localparam logic [31:0] HASH1_HASH1_MASK  = 32'hffffffff;
	localparam logic [31:0] HASH1_HASH1_RESET = 32'h00000000; // RO bit [31:0] hash1

	// Cell HASH2 — Digest word 2
	localparam int unsigned HASH2_HASH2_LSB   = 0;
	localparam int unsigned HASH2_HASH2_WIDTH = 32;
	localparam logic [31:0] HASH2_HASH2_MASK  = 32'hffffffff;
	localparam logic [31:0] HASH2_HASH2_RESET = 32'h00000000; // RO bit [31:0] hash2

	// Cell HASH3 — Digest word 3
	localparam int unsigned HASH3_HASH3_LSB   = 0;
	localparam int unsigned HASH3_HASH3_WIDTH = 32;
	localparam logic [31:0] HASH3_HASH3_MASK  = 32'hffffffff;
	localparam logic [31:0] HASH3_HASH3_RESET = 32'h00000000; // RO bit [31:0] hash3

	// Cell HASH4 — Digest word 4
	localparam int unsigned HASH4_HASH4_LSB   = 0;
	localparam int unsigned HASH4_HASH4_WIDTH = 32;
	localparam logic [31:0] HASH4_HASH4_MASK  = 32'hffffffff;
	localparam logic [31:0] HASH4_HASH4_RESET = 32'h00000000; // RO bit [31:0] hash4

	// Cell HASH5 — Digest word 5
	localparam int unsigned HASH5_HASH5_LSB   = 0;
	localparam int unsigned HASH5_HASH5_WIDTH = 32;
	localparam logic [31:0] HASH5_HASH5_MASK  = 32'hffffffff;
	localparam logic [31:0] HASH5_HASH5_RESET = 32'h00000000; // RO bit [31:0] hash5

	// Cell HASH6 — Digest word 6
	localparam int unsigned HASH6_HASH6_LSB   = 0;
	localparam int unsigned HASH6_HASH6_WIDTH = 32;
	localparam logic [31:0] HASH6_HASH6_MASK  = 32'hffffffff;
	localparam logic [31:0] HASH6_HASH6_RESET = 32'h00000000; // RO bit [31:0] hash6

	// Cell HASH7 — Digest word 7
	localparam int unsigned HASH7_HASH7_LSB   = 0;
	localparam int unsigned HASH7_HASH7_WIDTH = 32;
	localparam logic [31:0] HASH7_HASH7_MASK  = 32'hffffffff;
	localparam logic [31:0] HASH7_HASH7_RESET = 32'h00000000; // RO bit [31:0] hash7

endpackage : sha256_pkg
`endif // SHA256_PKG_SV
