// Generated by autowire plugin wishbone (table smoke). Do not edit.
// SV package: field layout only. Address map and shadow tag are packed with the bus.

`ifndef SMOKE_PKG_SV
`define SMOKE_PKG_SV
package smoke_pkg;

	// Cell ID — RC identity
	localparam int unsigned ID_MAGIC_LSB   = 0;
	localparam int unsigned ID_MAGIC_WIDTH = 16;
	localparam logic [31:0] ID_MAGIC_MASK  = 32'h0000ffff;
	localparam logic [31:0] ID_MAGIC_RESET = 32'h0000a55a; // RC bit [15:0] Magic
	localparam int unsigned ID_VERSION_LSB   = 16;
	localparam int unsigned ID_VERSION_WIDTH = 16;
	localparam logic [31:0] ID_VERSION_MASK  = 32'hffff0000;
	localparam logic [31:0] ID_VERSION_RESET = 32'h00000001; // RC bit [31:16] Version

	// Cell STATUS — RO status
	localparam int unsigned STATUS_BUSY_LSB   = 0;
	localparam int unsigned STATUS_BUSY_WIDTH = 1;
	localparam logic [31:0] STATUS_BUSY_MASK  = 32'h00000001;
	localparam logic [31:0] STATUS_BUSY_RESET = 32'h00000000; // RO bit [0] Busy (tied in HTML)
	localparam int unsigned STATUS_CODE_LSB   = 8;
	localparam int unsigned STATUS_CODE_WIDTH = 8;
	localparam logic [31:0] STATUS_CODE_MASK  = 32'h0000ff00;
	localparam logic [31:0] STATUS_CODE_RESET = 32'h00000000; // RO bit [15:8] Status code

	// Cell CFG — RW config
	localparam int unsigned CFG_ENABLE_LSB   = 0;
	localparam int unsigned CFG_ENABLE_WIDTH = 1;
	localparam logic [31:0] CFG_ENABLE_MASK  = 32'h00000001;
	localparam logic [31:0] CFG_ENABLE_RESET = 32'h00000000; // RW bit [0] Enable
	localparam int unsigned CFG_MODE_LSB   = 8;
	localparam int unsigned CFG_MODE_WIDTH = 3;
	localparam logic [31:0] CFG_MODE_MASK  = 32'h00000700;
	localparam logic [31:0] CFG_MODE_RESET = 32'h00000001; // RW bit [10:8] Mode

	// Cell FEED — RWW capture
	localparam int unsigned FEED_CAPTURE_LSB   = 0;
	localparam int unsigned FEED_CAPTURE_WIDTH = 16;
	localparam logic [31:0] FEED_CAPTURE_MASK  = 32'h0000ffff;
	localparam logic [31:0] FEED_CAPTURE_RESET = 32'h00000000; // RWW bit [15:0] Capture

	// Cell FIFO — RWE window
	localparam int unsigned FIFO_DATA_LSB   = 0;
	localparam int unsigned FIFO_DATA_WIDTH = 32;
	localparam logic [31:0] FIFO_DATA_MASK  = 32'hffffffff;
	localparam logic [31:0] FIFO_DATA_RESET = 32'h00000000; // RWE bit [31:0] External data

	// Cell CMD — W1P pulse
	localparam int unsigned CMD_GO_LSB   = 0;
	localparam int unsigned CMD_GO_WIDTH = 1;
	localparam logic [31:0] CMD_GO_MASK  = 32'h00000001;
	localparam logic [31:0] CMD_GO_RESET = 32'h00000000; // W1P bit [0] Go pulse

	// Cell IRQ — W1C sticky
	localparam int unsigned IRQ_STICKY_LSB   = 0;
	localparam int unsigned IRQ_STICKY_WIDTH = 1;
	localparam logic [31:0] IRQ_STICKY_MASK  = 32'h00000001;
	localparam logic [31:0] IRQ_STICKY_RESET = 32'h00000000; // W1C bit [0] Sticky IRQ

	// Cell BANK — Shadowed RW
	//   shadow: bank, 4 copies (bank select is a bus TGA concern)
	localparam int unsigned BANK_CFG_LSB   = 0;
	localparam int unsigned BANK_CFG_WIDTH = 8;
	localparam logic [31:0] BANK_CFG_MASK  = 32'h000000ff;
	localparam logic [31:0] BANK_CFG_RESET = 32'h00000010; // RW bit [7:0] Per-bank cfg

	// Cell BANKSEL — Saved working bank
	localparam int unsigned BANKSEL_BANK_SEL_LSB   = 0;
	localparam int unsigned BANKSEL_BANK_SEL_WIDTH = 2;
	localparam logic [31:0] BANKSEL_BANK_SEL_MASK  = 32'h00000003;
	localparam logic [31:0] BANKSEL_BANK_SEL_RESET = 32'h00000000; // RW bit [1:0] Working bank

	// Cell ACTIVE — Muxed working cfg
	localparam int unsigned ACTIVE_VALUE_LSB   = 0;
	localparam int unsigned ACTIVE_VALUE_WIDTH = 8;
	localparam logic [31:0] ACTIVE_VALUE_MASK  = 32'h000000ff;
	localparam logic [31:0] ACTIVE_VALUE_RESET = 32'h00000000; // RO bit [7:0] Working copy of BANK.cfg

	// Cell FABRIC — Wishbone interconnect fabric controls
	localparam int unsigned FABRIC_RB_GRANT_EN_LSB   = 0;
	localparam int unsigned FABRIC_RB_GRANT_EN_WIDTH = 1;
	localparam logic [31:0] FABRIC_RB_GRANT_EN_MASK  = 32'h00000001;
	localparam logic [31:0] FABRIC_RB_GRANT_EN_RESET = 32'h00000000; // RW bit [0] Arbiter: 0=fixed prio, 1=round-robin

	// Cell key_key_0 — 96-bit key (key[31:0] of [95:0])
	localparam int unsigned KEY_KEY_0_KEY_0_LSB   = 0;
	localparam int unsigned KEY_KEY_0_KEY_0_WIDTH = 32;
	localparam logic [31:0] KEY_KEY_0_KEY_0_MASK  = 32'hffffffff;
	localparam logic [31:0] KEY_KEY_0_KEY_0_RESET = 32'h00000000; // RW bit [31:0] 96-bit key (key[31:0] of [95:0])

	// Cell key_key_1 — 96-bit key (key[63:32] of [95:0])
	localparam int unsigned KEY_KEY_1_KEY_1_LSB   = 0;
	localparam int unsigned KEY_KEY_1_KEY_1_WIDTH = 32;
	localparam logic [31:0] KEY_KEY_1_KEY_1_MASK  = 32'hffffffff;
	localparam logic [31:0] KEY_KEY_1_KEY_1_RESET = 32'h00000000; // RW bit [31:0] 96-bit key (key[63:32] of [95:0])

	// Cell key_key_2 — 96-bit key (key[95:64] of [95:0])
	localparam int unsigned KEY_KEY_2_KEY_2_LSB   = 0;
	localparam int unsigned KEY_KEY_2_KEY_2_WIDTH = 32;
	localparam logic [31:0] KEY_KEY_2_KEY_2_MASK  = 32'hffffffff;
	localparam logic [31:0] KEY_KEY_2_KEY_2_RESET = 32'h00000000; // RW bit [31:0] 96-bit key (key[95:64] of [95:0])

endpackage : smoke_pkg
`endif // SMOKE_PKG_SV
